### ISSUE TITLE
[Question] How to log UserId for Crashes in Diagnostics - Xamarin 

### ISSUE THREAD

**Issue by soooraj** [microsoft/appcenter-sdk-dotnet#1000]
From this [https://devblogs.microsoft.com/appcenter/introducing-diagnostics-search-and-user-id-support/](Blog) Blog i get to know that we can save /send User Id for Crashes / Diagnostics. But not sure how i can pass this information through SDK(Xamarin). Could you please let me know how I can share this information through SDK. Now I am not sending the UserId and hence it is very difficult to track the user information related to crash.

**Comment by russelarms** [comment]
You can set user id in the SDK using the following code:

`AppCenter.SetUserId("your-user-id");`

https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#identify-users
