### ISSUE TITLE
Xamarin Forms iOS Crashes not sent

### ISSUE THREAD

**Issue by stealthjong2** [microsoft/appcenter-sdk-dotnet#1041]
### **Description**

After adding AppCenter Crashes to a Xamarin Forms iOS app, unhandled exceptions are not showing up in App Center. However, they do show up for Android, and handled exceptions logged using Crashes.TrackError are also showing up for both iOS and Android.

### **Repro Steps**

1. Create a Xamarin.Forms app.
2. Add nuget packages Microsoft.AppCenter, Microsoft.AppCenter.Crashes, and Microsoft.AppCenter.Analytics to the iOS project, the Android project, and the .NET standard project.
3. In App.xaml.cs, call AppCenter.Start("ios=...;android=...;uwp=...", typeof(Analytics), typeof(Crashes));
4. Start app (without debugger attached)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
**Xamarin.Forms on all 3 platforms (Android, iOS and UWP).**
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
**.NET standard 2.0.**
2. Which SDK version are you using?
**SDK version 2.1.1**
4. Which OS version did you experience the issue on?
**iOS 12.3.1, 12.2.2**
5. What device version did you see this error on?  Were you using an emulator or a physical device?
**iPhone Xs simulator, iPad Air 2**
6. What third party libraries are you using? 
**A whole bunch, most notably Prism, SQlite-NET, and Unity, but I doubt any of them would influence this. 
I have no Xamarin.Insights or HockeyApp.**
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

[AppCenter_iOS_undhandle_exception_not_showing.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/3392282/AppCenter_iOS_undhandle_exception_not_showing.txt)

**Comment by stealthjong2** [comment]
probably closely related to #621 , #974 , #272

**Comment by AnastasiaKubova** [comment]
Hi! I tried to reproduce your steps and I didn't get such a problem. Could you please clarify some moments:
- Make sure that you follow this document https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/Xamarin#423-xamarinforms
- Could you please share a code snippet with use our SDK?

**Comment by stealthjong2** [comment]
```
public partial class App : PrismApplication //which extends PrismApplicationBase, which extends Xamarin.Forms.Application
{
    ...
    public App(IPlatformInitializer platformInitializer = null, NavigationParameters parameters = null)
        : base(platformInitializer)
    {
            AppCenterSetup.StartAppCenter(); // I also have had this line in the OnStart() of this class, also to no avail
            ...
    }

    public static class AppCenterSetup
    {
        private const string AndroidKey = "0000000a-000a-000a-000a-00000000000a";
        private const string IosKey = "0000000b-000b-000b-000b-00000000000b";
        private const string UwpKey = "0000000c-000c-000c-000c-00000000000c";

        public static void StartAppCenter() 
        {
            var appCenterStartString = $"android={AndroidKey};ios={IosKey};uwp={UwpKey}";
            AppCenter.LogLevel = LogLevel.Verbose;
            AppCenter.Start(appCenterStartString, typeof(Analytics), typeof(Crashes));
            Crashes.NotifyUserConfirmation(UserConfirmation.AlwaysSend); // tried with and without this line
            System.Diagnostics.Debug.WriteLine("ENABLED? " + Crashes.IsEnabledAsync().Result);
            System.Diagnostics.Debug.WriteLine("ERRORS? " + Crashes.HasCrashedInLastSessionAsync().Result);
        }
    }
}
```

**Comment by AnastasiaKubova** [comment]
Hi! Looks like this related that AppCenter did not have time to start. Please try to call this
```Crashes.NotifyUserConfirmation(UserConfirmation.AlwaysSend);
            System.Diagnostics.Debug.WriteLine("ENABLED? " + Crashes.IsEnabledAsync().Result);
            System.Diagnostics.Debug.WriteLine("ERRORS? " + Crashes.HasCrashedInLastSessionAsync().Result);
```
a little later.

**Comment by stealthjong2** [comment]
Just tried the above, but it doesn't seem to make a difference. I created a manual button which triggers the above code, but `HasCrashedInLastSessionAsync` keeps returning `false`, no matter how long I wait.

I also read through https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin

**Comment by AnastasiaKubova** [comment]
Please make sure you launch the app without debug mode. 
Also please make sure that if you have a ```Xamarin.Forms``` app (with App Center apps for each platform), then the ```Start()``` call should be inside ```App.xaml.cs```.
If you have a ```Xamarin.iOS``` project, then the call to ```Start()``` should be inside ```AppDelegate.cs```

**Comment by AnastasiaKubova** [comment]
Also please remove this line `Crashes.NotifyUserConfirmation(UserConfirmation.AlwaysSend);`. You should only add it if you are implementing crash confirmation dialog and only inside button pressed callback.

**Comment by stealthjong2** [comment]
I will try running the app in release mode, however, the AppCenter troubleshooting docs specifically talk about an attached debugger, not whether the app is launched in debug mode:

> Make sure the debugger is not attached when you crash the iOS app

**Comment by AnastasiaKubova** [comment]
Yes, you understood correct. I meant that you should not attach debugger.

**Comment by stealthjong2** [comment]
So far, no luck at all. I've made sure `Start()` is called on the main thread, I've tried just supplying the AppSecret for iOS in the `Start()` method, I've tried downgrading to v2.0.0; I've done everything that's in the Getting Started, so I'm very curious as to why I can't get it to work, as it seems extremely straightforward to implement. Any more hints or things I should try?

Here are the packages I use, as defined in the iOS csproj.

AutoMapper 7.0.1
IdentityModel 2.12.0
Microsoft.AppCenter 2.1.1
Microsoft.AppCenter.Analytics 2.1.1
Microsoft.AppCenter.Crashes 2.1.1
NETStandard.Library 2.0.3
Plugin.Permissions 3.0.0.12
Polly 6.1.2
Prism.Unity.Forms 7.1.0.431
SkiaSharp 1.60.0
SkiaSharp.Views.Forms 1.60.0
sqlite-net-pcl 1.5.231
Toasts.Forms.Plugin 3.3.2
Xam.Plugin.Connectivity 3.1.1
Xam.Plugin.ExternalMaps 4.0.1
Xam.Plugin.Geolocator 4.5.0.6
Xam.Plugin.Media 4.0.1.5
Xam.Plugin.WebView 2.1.3
Xamarin.Controls.SignaturePad.Forms 3.0.0
Xamarin.Forms 3.6.0.264807
Xamarin.Plugin.FilePicker 2.0.135
ZXing.Net.Mobile.Forms 2.4.1

Maybe some of those raise a red flag immediately?

**Comment by AnastasiaKubova** [comment]
Could you please try to insert this code snippet to the `OnStart()` method in `App.xaml.cs` file:
``` protected override void OnStart()
        {
            AppCenter.LogLevel = LogLevel.Verbose;
            AppCenter.Start("ios={your-secret};", typeof(Crashes));
            Crashes.HasCrashedInLastSessionAsync().ContinueWith(hasCrashed =>
            {
                System.Diagnostics.Debug.WriteLine(LogTag, "Crashes.HasCrashedInLastSession=" + hasCrashed.Result);
            });
            Crashes.GetLastSessionCrashReportAsync().ContinueWith(task =>
            {
                System.Diagnostics.Debug.WriteLine(LogTag, "Crashes.LastSessionCrashReport.Exception=" + task.Result?.Exception);
            });
        }```
And perform the next steps:
1. Launch your app without debugger attached.
2. Crash your app.
3. Launch your app from VS and check your console log.
Let me know if crash result display in the console log.

**Comment by stealthjong2** [comment]
Sorry for wasting your and my time. Apparently, there was a try/catch statement around `UIApplication.Main()`. I now stumble onto another problem like the one in #873 (Log Flow shows UNHANDLEDERROR, but it doesn't show in Diagnostics). However, that's a server team issue, so I'll close this issue. Thanks for the support.
