### ISSUE TITLE
Standard way for getting user's permission to obtain data

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter-sdk-dotnet#1054]
### **Description**

Would it be possible to build in obtaining user permission to send this data? First of all is this required? You usually get asked this kind of information when you first start using an app.

Is there a recommended approach for how this should work?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Start-up app
2. Request permission for obtaining data
3. App Center then operates based on this setting

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin Forms + WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.
2. Which SDK version are you using?
    - 2.1
4. Which OS version did you experience the issue on?
    - All
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
6. What third party libraries are you using? 
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
N/A

**Comment by russelarms** [comment]
There’s no recommended approach for this, it depends on the local laws in the countries where your software operates.
You can disable services using `SetEnabledAsync(false)` until the user grants you the necessary permission:

```
AppCenter.Start….
AppCenter.SetEnabledAsync(MyStorage.Enabled); // or detect first launch and call with false only inside a if
```

Then from opt-in UI: Set with true.
You can do it at the core level, or by service.
