### ISSUE TITLE
WPF/mixed stack Support and Issues encountered

### ISSUE THREAD

**Issue by zsbzsb** [microsoft/appcenter-sdk-dotnet#1066]
This probably belongs as several issues, but as I'm not sure what the roadmap/goals are for this project or where else to post I'll just bundle my experiences using this SDK and my suggestions/requests in this one issue. I can also break this out to multiple issues if that is desired. Keeping it together I think helps you guys better understand the use case I'm dealing with here (and apologies for the wall of text you are about to see).

What I am developing is primarily a C#/WPF desktop app that calls extensively into a C/C++ codebase. The C/C++ side of things also utilizes callbacks to invoke managed code. This results in mixed stacks between managed and unmanaged/native code. Due to this setup it makes catching unhandled exceptions tricky to say the least. Let me be clear here -- I would not expect the SDK to catch unmanaged/native code SEH exceptions and I'm not asking for that. At the moment I'm also primarily using just the crash reporting, but I plan on taking full advantage of the analytics in the near future. Also I'm using VS 2019 with .NET Framework 4.7.2 and the v2.2.1-preview AppCenter NuGet packages.

I've already written code to catch and deal with managed and unmanaged/native exceptions including writing a minidump to disk for later debugging. This is where my issues with the AppCenter SDK start and where I would like to see improvements made. If I'm missing something quite obvious in what I mention below please point it out to me, but I've actually checked out the repo and scoured the source so I don't think I really missed anything.

The first issue I ran into was that the v2.2.1-preview NuGet package wants a mile long list of dependencies. I saw this [mentioned here](https://github.com/microsoft/appcenter-sdk-dotnet/issues/620#issuecomment-508806448) but nothing ever came of it. To me this is a pretty major issue that needs to be resolved. After manual testing and trial and error I was able to narrow down the list of dependencies, but that shouldn't be necessary. In a brand-new project after adding the v2.2.1-preview NuGet package this is what my `packages.config` [looked like](https://gist.github.com/zsbzsb/8af03af7be1b0eb7ddbcfc0da7df68e8).

The second issue that I encountered is what I would describe as the API is quite rigid and tries too hard to be a black box. I understand that automatic crash reporting is a selling point of this SDK to many users, but to someone in my situation where it is a requirement to handle both managed and unmanged/native exceptions myself I just need a simple and flexible API to push unhandled exceptions to AppCenter. This issue manifested itself in two different ways: First the current API has no way to disable automatic unhandled exception handling. Secondly there is no public API to report a "crash", only an "error".

Calling `Crashes.SetEnabledAsync(false);` is the only way to unhook the internal handler of `ApplicationLifecycleHelper.Instance.UnhandledExceptionOccurred` that does the automatic exception handling... But this also results in no crashes being reported to AppCenter. The way I worked around this is that I made sure to hookup up my own unhandled exception handlers before the SDK had a chance to hookup its handlers. Then I also made sure that my app died before the SDK handler had a chance to fire. May I suggest `Crashes.SetUnhandledExceptionHandling(true|false)` as a possible API to handle this use case?

`Crashes.PlatformTrackError(...)` is the only public API to push an exception object to the SDK, but the issue here is that it appears in the console as an "error" and not a "crash". I would like to keep the distinction between "error" and "crash" as well as be able to push my own exceptions. As mentioned above I need to push unhandled unmanaged/native exceptions to AppCenter. The way I worked around this was by using reflection to invoke the private `ApplicationLifecycleHelper.InvokeUnhandledException(...)` method. This should be obvious that it isn't maintainable in the longterm and is an ugly workaround. I would suggest adding a `Crashes.PlatformTrackCrash(...)` method that complements the `Crashes.PlatformTrackError(...)` method.

The third issue is something that I still don't have a solution to. There is a possibility given the nature of my app that it may crash on startup and from what I have seen the SDK will just after startup of itself begin asynchronously uploading reports. What I've noticed is that if the SDK is interrupted (say my app crashes again) those reports that were in-progress of being uploaded will not be uploaded again and are lost forever. This isn't the end of the world, but it would be nice to have an API to push exceptions that is synchronous... Or at the very least a way to block until the upload is complete. Before switching to AppCenter I used Bugsnag for a while and that API was dead simple -- all I had to do was call a single function that would block while sending the exception and then I knew I could safely finish exiting the app.

Another issue I'd like to see addressed is adding attachments to reports. Maybe this is because I'm reflect invoking a private method... but what I encountered was a huge disconnect between sending an exception and then adding attachments to the report. Since the `Crashes.GetErrorAttachments` callback happens well after the fact of me sending an exception I struggled to determine which attachments to send (e.g. my minidump files are stored on disk with a datetime stamp). The solution that I ended up with (which I don't care for) is to match on the date/time, but that has a small chance to not be 100% right all the time resulting in some reports without attachments. It'd be nice to put some arbitrary data in each report that I could easily access in the attachment callback to find the right attachments for the report.

The final issue that absolutely needs addressing is where the SDK stores the `AppCenter.config` file by default. Currently `DefaultApplicationSettings.OpenConfiguration()` attempts to put the file next to the AppCenter SDK DLL. That is a no-go in release when your app installs to the program files folder and then runs without admin permissions. The only workaround I got for this issue (short of recompiling the SDK) is to call `AppCenter.SetApplicationSettingsFactory(...)` (which for some unknown reason is marked as obsolete and hidden) with a custom factory class that then creates a custom settings storage class... All just to change where the config file is stored. Please add a `DefaultApplicationSettings.SetConfigPath(...)` method.

**Comment by guperrot** [comment]
Hi, any chance you can create separate issues? This will make it easier to follow up and track on each item.

**Comment by winnieli1208** [comment]
Hi @zsbzsb, 

This is Winnie from the PM team. Thank you for the thoughtful and detailed feedback. I'll try and address each of your points here but if you don't mind creating a separate issue for each request, that would make it much easier for us (and the community) to follow. You can follow our public roadmap and file your feature requests [here](https://github.com/Microsoft/appcenter/wiki/Roadmap). 


1. List of dependencies: our engineering team will take a look at this and get back to you. We didn't experience this behavior in our test apps and will need some to investigate. Thank you for your patience.

2a) `Crashes.SetUnhandledExceptionHandling(true|false)` - if you create a feature request in the App Center repo, this will help our team investigate and prioritize this feature. We don't have any immediate plans to address this but it sounds like an interesting use case that could be very helpful for other customers.

2b) `Crashes.PlatformTrackCrash(...)` - same as above. Semi-related - we do plan on implementing public API that allows you to upload a custom crash  ([Feature request #31](https://github.com/microsoft/appcenter/issues/31)) in the next few weeks.

3) Attachments - we have plans to support adding attachments to handled errors in the future. No exact ETA yet but there's already a similar feature requests being tracked: [#345](https://github.com/microsoft/appcenter/issues/345)

4) Default path of .config file - my colleague Guillaume has worked on this issue as linked above. 

Thank you again for your feedback! If you create separate feature requests [here](https://github.com/microsoft/appcenter/issues), we can continue the conversation and post updates in those threads. 

Thanks!

**Comment by james1301** [comment]
Hi @winnieli1 I wanted to bring up the list of dependencies issue. This seems to be because of sqlite-net.pcl.1.3.1 requires NETStandard.Library which then brings in a load of references for a .net framework project. Ideally that package would have the .net framework as a target, then it wouldn't possibly?

Any feedback on this would be good, thanks.

**Comment by AnastasiaKubova** [comment]
Hi, @james1301! This was fixed in the v1.4 version of [sqlite-net.pcl](https://github.com/praeclarum/sqlite-net/releases/tag/v1.4.118) . You can try to update this dependence to fix it.

**Comment by james1301** [comment]
Thanks @AnastasiaKubova, any reason the minimum version the SDK is pointing at, hasn't been updated? This will create a mess on installing won't it, unless you happen to have those dependencies at later versions.

**Comment by AnastasiaKubova** [comment]
@james1301 It is pointing at the minimum version that SDK supported.

**Comment by james1301** [comment]
But this is making problems. I've just spent an hour removing all of the additional references. Now it is supported for WPF and Winforms it doesn't make much sense to create this mess for everybody does it? I'm going to have to go through a similar problem for every project I install it on.

This is especially bad if people don't notice this problem, like I haven't until further down the line.

**Comment by james1301** [comment]
@AnastasiaKubova

**Comment by michaelsmitha** [comment]
@james1301 You are right, that is a mess. We are currently investigating removing the sqlite-net-pcl wrapper altogether, so hang tight with us 😸 . I'm sorry this hasn't been a smooth experience for you.

**Comment by DmitriyKirakosyan** [comment]
Hi folks, we've addressed most of the requests in this issue, except `Crashes.SetUnhandledExceptionHandling(true|false)` API. However, if your goal is to prevent sending caught crash reports to App Center, you can use [ShouldProcessErrorReport](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms#should-the-crash-be-processed) API or use [ShouldAwaitUserConfirmation](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms#ask-for-the-users-consent-to-send-a-crash-log) to ask user whether they want to send the crash report.

I'm closing this issue but feel free to reopen if you have additional questions.
