### ISSUE TITLE
Support Avalonia as a target?

### ISSUE THREAD

**Issue by alessandrofrancesconi** [microsoft/appcenter-sdk-dotnet#1083]
[Avalonia](https://avaloniaui.net/) is a very interesting UI framework that combines XAML and .NET Core to provide cross-platform desktop development.

Since it is actually based on .NET Core, would it be easily added as a target for App Center?
Currently the output says `"[AppCenter] ASSERT: Cannot use App Center on this target. If you are on Android or iOS or UWP, you must add the NuGet packages in the Android and iOS and UWP projects as well. Other targets are not yet supported."`

**Comment by winnieli1208** [comment]
Hey @alessandrofrancesconi thanks for the feature request!  We don't currently support Avalonia but we plan to release our SDK that supports .NET Core 3 Windows applications this month. After this release, our team will investigate how we can expand the SDK to support other .NET Core apps as well.

I'll post here if I have any updates. Thanks!

**Comment by alessandrofrancesconi** [comment]
That's a good news! Keep us updated, thanks

**Comment by alessandrofrancesconi** [comment]
Just tried using 2.3.0-preview ([this](https://www.nuget.org/packages/Microsoft.AppCenter.Analytics/2.3.0-preview)) but I still see `[AppCenter] ASSERT: Cannot use App Center on this target.`

The TargetFrameworks for my app is `netcoreapp2.2`. Is it supported?

**Comment by guperrot** [comment]
Hi, we support only WPF/WinForms running on the .NET Core 3.0 (which is in preview).

**Comment by ShadowDancer** [comment]
I've tried running in avalonia recently and got error:
```
System.TypeInitializationException: 'The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelper' threw an exception.'

FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

**Comment by alessandrofrancesconi** [comment]
Generally speaking, what is strange to me is that the AppCenter SDK needs components like `System.Windows.Forms` to work (as reported by @ShadowDancer ).
I assumed AppCenter to be agnostic to the frontend (WinForms, in this case). For example, crashes can happen also on console applications, so AppCenter should "just" get the exception and send it to the cloud. Same goes for analytics and event tracking.

Without the requirement of having `System.Windows.Forms` loaded, the AppCenter might work on a broader set of environments (as .NET Core itself does).

**Comment by AigioL** [comment]
@alessandrofrancesconi  Hi, I have created a package you can try
```
Install-Package Aigio.Avalonia.AppCenter -Version 4.4.0
Install-Package Aigio.Avalonia.AppCenter.Crashes -Version 4.4.0
Install-Package Aigio.Avalonia.AppCenter.Analytics -Version 4.4.0
```

https://github.com/SteamTools-Team/appcenter-sdk-dotnet/commit/9166f90f4b6cc4912ff65f757811fd9efae41bbb#diff-e12f9d0fcf20d59e66dff260c556fefb82e81de92b4b6d47074ea39403130956

**Comment by pawelmajda** [comment]
@AigioL does your package only supports Windows platform? I was trying to use it in Avalonia app on macOS and it gave me following exception: 

```
System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'user32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libuser32.dll, 1): image not found
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop.SetWinEventHook(UInt32 eventMin, UInt32 eventMax, IntPtr eventHookAssemblyHandle, WinEventDelegate eventHookHandle, UInt32 processId, UInt32 threadId, UInt32 dwFlags)
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformConfigure(String appSecret)
   at Microsoft.AppCenter.AppCenter.Configure(String appSecret)
   at Mailbird.App.OnFrameworkInitializationCompleted() in 
```

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
