### ISSUE TITLE
Xamarin Auth Android manifest requires workaround

### ISSUE THREAD

**Issue by Jjagg** [microsoft/appcenter-sdk-dotnet#1094]
When Xamarin merges AndroidManifest.xml files together in its build step it does not correctly fold elements together when it should (https://github.com/xamarin/xamarin-android/issues/3428). This causes issues for the AppCenter Auth setup in the AndroidManifest.xml file as described in the AppCenter [docs](https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#androidmanifestxml).

The docs tell us to add the following to the manifest:
```
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="auth"
            android:scheme="msal{Your App Secret}" />
    </intent-filter>
</activity>
```
This should complement the generated activity from the BrowserTabActivity class that gets pulled in:
```
    <activity android:name="com.microsoft.identity.client.BrowserTabActivity" android:exported="true" />
```

However adding the first snippet to the manifest causes a build crash on Xamarin because the elements aren't properly merged:
```
[....]\Xamarin\Android\Xamarin.Android.Common.targets(2789,3): error : jav a.lang.IllegalArgumentException: already added :  Lcom/microsoft/identity/client/BrowserTabActivity
```

I don't think there's an easy workaround for this issue currently. Proper workarounds need to fix the manifest as part of the build process.

**Comment by amchew** [comment]
Hey @Jjagg, to update you we’re going to repro this and investigate further. Thanks for the patience and bearing with us! 🙏🏻

**Comment by AnastasiaKubova** [comment]
Hi, @Jjagg! Thank you for contacting us. Unfortunately, I could not reproduce your issue.  Could you please try to reproduce this issue on the empty project and let me know about the results? Also, could you please clarify do you use Xamarin or Xamarin.Forms?

**Comment by Jjagg** [comment]
I failed to reproduce this as well on a new project, but also on the project I originally had this issue with. I removed my workaround and it's working just fine. The merged AndroidManifest.xml file has two entries for the BrowserTabActivity.
The one pulled in by AppCenter.Auth:
```
<activity android:name="com.microsoft.identity.client.BrowserTabActivity" android:exported="true" />
```
The one in the user AndroidManifest.xml as required for AppCenter.Auth:
```
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:host="auth" android:scheme="msal2c2d8a5d-6e1f-4916-870b-2dcc26a87e5c" />
   </intent-filter>
</activity>
```

But this does not cause any issues. I don't know what went wrong previously, but I'll go ahead and close this issue. Thanks for looking into this so quickly :)

**Comment by amchew** [comment]
Good to hear that it was resolved @Jjagg! :D
