### ISSUE TITLE
Need a way to add attachments to Errors

### ISSUE THREAD

**Issue by danAtAllworx** [microsoft/appcenter-sdk-dotnet#1102]
### **Description**

The `Crashes.GetErrorAttachments` callback is not called when `Crashes.TrackError()` is invoked. As far as I can see, there is no way to add an attachment to an Error report.

### **Repro Steps**

    Crashes.GetErrorAttachments = report => new List<ErrorAttachmentLog>
    { ErrorAttachmentLog.AttachmentWithText("This attachment is not sent.", "file.txt") };

    Crashes.TrackError(new NotImplementedException());

### **Details**

Platform: WinForms, .NET Framework 4.5.1
SDK Version: 2.3.0
OS: Windows 10

**Comment by guperrot** [comment]
It was also asked at https://github.com/microsoft/appcenter/issues/160

**Comment by hamswan** [comment]
Thanks @danAtAllworx , we will add it to our feature request.

**Comment by guperrot** [comment]
Hi, we released this feature in version [2.6.1](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.6.1).
