### ISSUE TITLE
Need a way to add a custom exception handler

### ISSUE THREAD

**Issue by danAtAllworx** [microsoft/appcenter-sdk-dotnet#1103]
### **Description**

When AppCenter is initialized, it either overrides or is overridden by any custom exception handler. Cross reference with [this SO question](https://stackoverflow.com/q/57717007/3119991). There does not appear to be any clean way to allow both AppCenter and a custom handler to both be executed in the event of an exception.

AppCenter should either provide a way for a custom exception handler to call it, or (probably better) should provide a callback hook for a custom exception handler.

### **Repro Steps**

Here is a simple example:

    internal class Form1 : Form
    {
        [STAThread]
        static void Main()
        {
            Application.ThreadException += (sender, args) =>
            {
                Console.WriteLine(@"Handler called");
                MessageBox.Show(@"Something bad happened. The application will now close.");
                Application.Exit();
            };
            AppCenter.Start("id", typeof(Crashes));

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        public Form1()
        {
            var button = new Button {Text = @"CRASH!"};
            button.Click += (sender, args) => throw new NotImplementedException();
            Controls.Add(button);
        }
    }

Note that in the code above, a custom handler is added before the call to `AppCenter.Start()`. This will result in only AppCenter being called when the button is clicked. The custom handler will not be called. If the custom handler is added after the call to `AppCenter.Start()` then only the custom handler will be called. AppCenter will not be called.

### **Details**

Platform: WinForms, .NET Framework 4.5.1
SDK Version: 2.3.0
OS: Windows 10

**Comment by nanabite** [comment]
I agree - I have tried to use AppCenter in my application, but was not able to due to this behaviour. We use DevExpress and throw a ValidationException in cases where we want to surface validation issues to the user. Because this gets handled by AppCenter, the DevExpress framework is never made aware of the exception and doesn't show the validation.

Personally, I think there should be an option to completely disable the "crash" handling functionality and allow us to handle sending "Errors" and "Crashes" to AppCenter manually - I created an NLog target which works well for this purpose.

**Comment by Jamminroot** [comment]
Hey, @nanabite, @danAtAllworx, thanks for bringing this to our attention, Ill let our PMs team look at your request.

**Comment by danAtAllworx** [comment]
Additionally, I'd like to request that, if you implement this feature, you would provide some way to discover the report ID at exception time. I want to record some information at the time that the exception occurs so that I can include it as an attachment later when the report is sent.

**Comment by guperrot** [comment]
This will be possible in the next SDK version as commented in https://github.com/microsoft/appcenter-sdk-dotnet/issues/1104#issuecomment-531976900.

However do not use ThreadException and Application.Exit as we won't be able to capture the crash that way anymore.

Instead you should use:

```
Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);
AppDomain.UnhandledException += (sender, args) =>
{
     // your code
}
```

**Comment by guperrot** [comment]
The previous example was if the app has to crash (basically don't use ThreadException + exit but rather use the previous example).

If the app must continue running then you can use ThreadException + TrackError (not a crash but an error). As mentioned in the updated docs and updated SDK 2.4.0-preview: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms. The doc change seems to not be live yet, but there was a copy in https://github.com/microsoft/appcenter-sdk-dotnet/issues/1104#issuecomment-531976900 in the meantime.
