### ISSUE TITLE
W/System.err( 6127): remove failed: ENOENT (No such file or directory) 

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/appcenter-sdk-dotnet#1105]
During app initialization on android, before I get to the MainPage I get following error: 08-30 13:46:19.081 W/System.err( 6127): remove failed: ENOENT (No such file or directory) : /data/user/0/com.app.myapp/files/appcenter/database_large_payloads/group_analytics/10.json
After this the splashscreen stays on my screen until I kill the app, if I press pause in visual studio, I don't see any c# threads, I only see a worker thread
Not Flagged 6 0 Worker Thread System.Threading.WaitHandle.Wait_internal()
[External Code]

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    -  all 3 platforms (Android, iOS and UWP).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.
2. Which SDK version are you using?
    - e.g. 2.1.1
4. Which OS version did you experience the issue on?
    - e.g. iOS 11, Android 8

**Comment by Jamminroot** [comment]
Hello, @KSemenenko, thanks for getting in touch.
So far it's hard to tell what is not working as expected - can you share verbose logs with us?
Which platform is it in this case - Xamarin.Forms or Xamarin Native app?
Where did you initialize AppCenter?

**Comment by Jamminroot** [comment]
We'll keep you updated in this thread.
[android](https://github.com/microsoft/appcenter-sdk-android/issues/1233/) [appcenter](https://github.com/microsoft/appcenter/issues/964)

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if it's still the issue for you.
