### ISSUE TITLE
xamarin.appcenter.push depends on an old version of xamarin.firebase.messaging preventing the use of the latest version of 

### ISSUE THREAD

**Issue by softlion** [microsoft/appcenter-sdk-dotnet#1106]
### **Description**
The current prerelease version of xamarin.appcenter.push for Xamarin Android, available on nuget, depends on an old version of xamarin.firebase.messaging preventing the use of the latest version of xamarin.GooglePlayServices.Location/Maps (v71).

Is there a way to get more recent packages ?

**Comment by hamswan** [comment]
Hi @dtrabo we are looking into this.

**Comment by AnastasiaKubova** [comment]
The fix has been released in [2.4.0-preview](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.4.0-preview).
