### ISSUE TITLE
Xamarin.Android InstrumentationRegistry not found when building with r8 and linker

### ISSUE THREAD

**Issue by jamesmontemagno** [microsoft/appcenter-sdk-dotnet#1108]
Noticed this warning in the output. 

### **Description**

Warning in obj\Debug\90\lp\15\jl\bin\classes.jar:com/microsoft/appcenter/utils/InstrumentationRegistryHelper.class:
  Type `android.support.test.InstrumentationRegistry` was not found, it is required for default or static interface methods desugaring of `android.os.Bundle com.microsoft.appcenter.utils.InstrumentationRegistryHelper.getArguments()`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Build release version of: https://github.com/jamesmontemagno/Hanselman.Forms

### **Details**

1. What is your app platform Xamarin.Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.
2. Which SDK version are you using?
    - 2.2.1
4. Which OS version did you experience the issue on?
    - Android 9.0 compile 
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Device
6. What third party libraries are you using? 
    - example
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by achocron** [comment]
Out of curiosity, are there any observable effects other than the warning itself?

**Comment by guperrot** [comment]
Please share AppCenter verbose logs on that one.

**Comment by jamesmontemagno** [comment]
There was not observable effect, just in the output. This was in a build in VS itself, not in app center. just local on my machine.

**Comment by guperrot** [comment]
Are you saying the warning is visible only in Build output and not in runtime/console output log?

**Comment by guperrot** [comment]
Oh it's R8, the successor of Proguard. We don't have R8 rules automatically but in Proguard we use `-dontwarn` because this class is available only in a Test environment (like when using UI tests on the cloud). You can add the equivalent of `-dontwarn` there.

**Comment by guperrot** [comment]
Don't hesitate to reopen if there is another warning or error, we don't have R8 support at this time.
