### ISSUE TITLE
[Question] Data sync with Auth - token expiration

### ISSUE THREAD

**Issue by spatialguy** [microsoft/appcenter-sdk-dotnet#1111]
Please note - this is a question rather than issue report.

In AppCenter Data, 

> To use the private document partitions, you must be authenticated via App Center Auth.

according to [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/data/xamarin) 

I could not find anywhere in the documentation how AppCenter Data handles expired tokens. 
I read in the docs how to sign in using AppCenter Auth, but it is not clear to me what will happen when access token expires. Default access token expiration [is 1 hour](https://docs.microsoft.com/en-us/appcenter/sdk/data/xamarin)

Does the SDk throw an exception which developers are assumed to handle and obtain new token? Also, how AppCenter Data SDK obtains access token - is it so that the Auth. SignInAsync stores the token somewhere and Data SDK knows where to look for it?

**Comment by guperrot** [comment]
The MSAL library that is used to manage authentication also stores the refresh token, which enables refreshing silently the token when expired. That's for Auth.

For Data the auth token is exchanged with another one specific to Data which is also refreshed automatically.

**Comment by dtrabo** [comment]
Hi @spatialguy. Could you please tell, do you have any other questions?

**Comment by spatialguy** [comment]
> Hi @spatialguy. Could you please tell, do you have any other questions?

No, thank you!
