### ISSUE TITLE
iOS 13 exception on SignInAsync: Cannot start ASWebAuthenticationSession without providing presentation context

### ISSUE THREAD

**Issue by TomSoderling** [microsoft/appcenter-sdk-dotnet#1124]
Today I updated to VS for Mac v8.3 and to Xcode 11.0 and I started getting this exception each time I try to sign in using:
`UserInformation userInfo = await Auth.SignInAsync();`

Exception message:
> Foundation.NSErrorException: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
>   at AppCenterBaaS.ViewModels.AuthPageViewModel.SignIn () [0x00034] in /[myAppName]/ViewModels/AuthPageViewModel.cs:102

This was working yesterday before I updated. Please let me know what I can do. I'm using AppCenter.Auth v2.1.1
VS for Mac version details attached.

[VSforMacversionInfo.txt](https://github.com/microsoft/appcenter/files/3644286/VSforMacversionInfo.txt)

**Comment by annakocheshkova** [comment]
Np. I transferred the issue.

**Comment by TomSoderling** [comment]
> Hello everyone! The new SDK version with partial iOS 13 support for Auth is released today, please [check it out](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/2.4.0). Full support will come in one of the next releases, but it already should work as it is.

Thank you for the quick response. Like Rich, I'll have to wait till this comes to appcenter-sdk-dotnet so I can consume it in my Xamarin.Forms app

**Comment by annakocheshkova** [comment]
Hello there. The [App Center SDK DotNet 2.4.0-preview](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.4.0-preview) is released! 🎉

**Comment by richp582** [comment]
Just tried the new package on my iOS 13 device and it still is not working.  It asks if I want to use B2C to Login pops a browser page for a split second then drops back to the app.

**Comment by TomSoderling** [comment]
This worked for me on iOS for my Xamarin.Forms app. I was able to authenticate and pull down docs from my App Center backend. 
I updated both the AppCenter & AppCenter.Auth packages in my Shared and iOS projects to version 2.4.0-preview. I'm still using Xcode 10.3 and VS for Mac v8.2.6 however

**Comment by annakocheshkova** [comment]
@richp582 This is very interesting, can I ask you to open a separate issue and provide all the details (environment info, verbose logs). Looks like something different than before.

**Comment by annakocheshkova** [comment]
@TomSoderling great to hear that! I'm closing this issue, if anyone sees the original exception again on the new version feel free to re-open it.

**Comment by TomSoderling** [comment]
@annakocheshkova Thanks very much!

**Comment by matt-goldman** [comment]
I am still getting this issue after upgrading packages to 2.4.0 in core and IOS project. IOS 13 simulator, VS Mac 8.3.1 build 18, XCode 11.0

Foundation.NSErrorException: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
  at MyProject.ViewModels.LoginPageViewModel.SignIn () [0x00025] in /Users/me/Projects/MyProject/MyProject/ViewModels/LoginPageViewModel.cs:23
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178

**Comment by AnastasiaKubova** [comment]
Hi @matt-goldman! Could you please share the verbose [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level)?

**Comment by matt-goldman** [comment]
> Hi @matt-goldman! Could you please share the verbose [logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level)?

See attached - hope that helps!
[AppCenterAuth.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/3689486/AppCenterAuth.log)

**Comment by matt-goldman** [comment]
Apologies - I rolled back to grab you the logs as I'd started testing with MSAL direct to the tenant. and rolled back the package version too. Reinstalled 2.4.0 and now all is working.
