### ISSUE TITLE
[Feature request] Support for command line applications

### ISSUE THREAD

**Issue by claunia** [microsoft/appcenter-sdk-dotnet#1125]
### **Description**

Make it work on command line applications.

### **Repro Steps**

1. Add Analytics and Crashes to a dotnet core app
2. run in Linux
3. nothing happens.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - .NET Core 2.2
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - Not applicable
3. Which SDK version are you using?
    - 2.3.0-preview
4. Which OS version did you experience the issue on?
    - ArchLinux rolling
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Not applicable
6. What third party libraries are you using? 
    - Not applicable
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
`[AppCenter] ASSERT: Cannot use App Center on this target. If you are using the SDK from a .NET standard library, you must also add the App Center NuGet packages in the Android, iOS and UWP/WPF/WinForms projects as well. Other targets are not yet supported.`

**Comment by annakocheshkova** [comment]
Hi @claunia, thank you, we will create a feature request for this.

**Comment by alessandrofrancesconi** [comment]
I totally agree with this as it is somehow related to #1083

**Comment by corradolab** [comment]
2 year and half later, .NET up to version 6, still no support for console apps. The only "improvement" is now the app crash because it looks for System.Windows.Forms even on console apps...

**Comment by AnastasiaKubova** [comment]
Hi there! Unfortunately, there is no ETA for this feature at this moment, but we are keeping an eye on this thread.
See more info in our [Roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap).

**Comment by maxkatz6** [comment]
Pretty weird that after these years there are still no framework agnostic SDK.

**Comment by r-o-d-p** [comment]
So you are waiting for people to comment, well I've been waiting a while for this too.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
