### ISSUE TITLE
.NET Core 3.0 WinForms NuGet issue

### ISSUE THREAD

**Issue by EatonZ** [microsoft/appcenter-sdk-dotnet#1136]
### **Description**

When installing Microsoft.AppCenter version 2.4.0-preview in a fresh .NET Core 3.0 WinForms app, a warning is shown related to the Newtonsoft.Json dependency.

### **Repro Steps**

1. Using the latest version of Visual Studio 2019, create a .NET Core 3.0 WinForms app.
2. Install the Microsoft.AppCenter version 2.4.0-preview package.
3. Take a look at the Error List.
![2019-10-02_13-00-27](https://user-images.githubusercontent.com/3020941/66065067-a57c3c80-e514-11e9-91e6-41d1d6ff95ef.png)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WinForms
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET Core 3.0
2. Which SDK version are you using?
    - 2.4.0-preview
4. Which OS version did you experience the issue on?
    - Windows 10 1903 64bit
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical desktop PC
6. What third party libraries are you using? 
    - No others

**Comment by michaelsmitha** [comment]
Thank you for the report @EatonZ . I've reproduced the issue and we are tracking it as a bug.

**Comment by michaelsmitha** [comment]
Hello @EatonZ , just wanted to let you know I have a PR out for this :) https://github.com/microsoft/appcenter-sdk-dotnet/pull/1161

**Comment by EatonZ** [comment]
@michaelsmitha One thing I noticed when using another pre-release package with 
Newtonsoft.Json is that it installs the beta version of Newtonsoft.Json, and App Center works just fine with it.

When installing the pre-release App Center by itself, it doesn't pick a newer version, only v6.

Both with the "Include Preleases" checkbox checked.

Maybe you can consider setting it so it will allow for installation of newer json versions?

**Comment by guperrot** [comment]
Version 2.5.0 of the nugets were released last month with updated json dependencies. Please check it out and reopen if you see the issue again.
