### ISSUE TITLE
Auth.SignInAsync() not persisting data on Xamarin Forms / iOS13

### ISSUE THREAD

**Issue by acmngmbh** [microsoft/appcenter-sdk-dotnet#1137]
### **Description**

After calling Auth.SignInAsync() and successfully signing in a user, I was expecting that subsequent calls of Auth.SignInAsync() will NOT present the UI again. However, the UI is displayed over and over again.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    Xamarin.Forms 4.2.0
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.
2. Which SDK version are you using?
    - Xamarin.iOS Version: 13.2.0.42 (Visual Studio Community)
4. Which OS version did you experience the issue on?
    - iOS 13
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone XS physical device, Simulator

**Comment by michaelsmitha** [comment]
Hello @acmngmbh , could you provide your device logs? Can you also check that you set up your keychain settings - https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#add-keychain-sharing-capability - and make sure it is set up for all combinations of build type and SDK.

**Comment by acmngmbh** [comment]
> Hello @acmngmbh , could you provide your device logs? Can you also check that you set up your keychain settings - https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#add-keychain-sharing-capability - and make sure it is set up for all combinations of build type and SDK.

Hi, i had a typo in the keychain group settings - fixing it resolved the issue! Thank you :)
