### ISSUE TITLE
Custom stack traces from native code

### ISSUE THREAD

**Issue by macmade** [microsoft/appcenter-sdk-dotnet#1149]
### **Description**

On a project I'm working on, we generate custom crash reports for native code.  
The report is generated when a C++ or SEH exceptions is thrown, and passed to the managed code.
The managed code then creates a custom .NET exception and throws it, so it can be caught by the AppCenter SDK as any other managed exception.

The crash reports we generate are similar to the ones on macOS or iOS.  
Like: https://gist.githubusercontent.com/macmade/e5c7b975c751876ed8833515213c768c/raw/caae71200ac68c24dac8765dea96a1639fcdf8af/gistfile1.txt

I'm trying to make AppCenter display the stack trace correctly for such reports (with the nice syntax highlight).  
I know managed exceptions only contain the stack trace for the responsible thread, and I don't mind stripping down the full report, since I can upload it as attachement.

But unfortunately I can't make the AppCenter recognize a valid stack trace.  
I tried different variations for the exception stack trace, such as:

```
   at pdflib.PDF_set_gstate in pdflib.dll
   at pdflib.PDF_set_gstate in pdflib.dll
   at pdflib.PDF_set_gstate in pdflib.dll
   at pdflib.PDF_set_gstate in pdflib.dll
   at pdflib.PDF_set_gstate in pdflib.dll
   at pdflib.PDF_fit_textflow in pdflib.dll
   at KERNEL32.BaseThreadInitThunk in KERNEL32.dll
   at ntdll.RtlUserThreadStart in ntdll.dll
```

This is to mimic the stack trace of managed exceptions.
But no matter what I try, the stack trace is not well recognized nor highlighted.

**Is there a way to generate custom stack traces from subclasses of `System.Exception` so they are recognized by AppCenter?**

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - **Windows WPF**
2. Which SDK version are you using?
    - **2.4.0-preview**
4. Which OS version did you experience the issue on?
    - **Windows 10**
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - All

**Comment by Jamminroot** [comment]
Hey, @macmade, thanks for getting in touch. Let me discuss it with a team before giving any advices

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Comment by macmade** [comment]
lol
