### ISSUE TITLE
ASSERT: Cannot use App Center on this target with DesktopBridge WPF app

### ISSUE THREAD

**Issue by lostmsu** [microsoft/appcenter-sdk-dotnet#1155]
### **Description**

In a WPF app packaged using DesktopBridge app package for Windows Store, AppCenter fails to initialize with

> [AppCenter] ASSERT: Cannot use App Center on this target. If you are on Android or iOS or UWP, you must add the NuGet packages in the Android and iOS and UWP projects as well. Other targets are not yet supported.

### **Repro Steps**

1. Create new WPF app, add AppCenter SDK 2.1.1 from NuGet
2. Add code to run `AppCenter.Start(...)` at startup
3. Create new Windows Application Packaging Project in the same solution
4. Add WPF app to Windows Application Packaging Project
5. Set Windows Application Packaging Project as startup project and launch

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WPF packaged for Windows Store
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - N/A
2. Which SDK version are you using?
    - 2.1.1
4. Which OS version did you experience the issue on?
    - Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - PC
6. What third party libraries are you using?
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

> [AppCenter] ASSERT: Cannot use App Center on this target. If you are on Android or iOS or UWP, you must add the NuGet packages in the Android and iOS and UWP projects as well. Other targets are not yet supported.

**Comment by guperrot** [comment]
The WPF support is currently only in the preview package.
Can you try version `2.4.0-preview` as mentioned in https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms#3-add-the-app-center-sdk-modules?

**Comment by lostmsu** [comment]
Update to `2.4.0-preview` solved the problem
