### ISSUE TITLE
App center Auth doesn't support latest Xamarin form 4.2.0.848062

### ISSUE THREAD

**Issue by nithinshiriya** [microsoft/appcenter-sdk-dotnet#1164]
1. Xamarin.Forms [4.2.0.848062] on all 3 platforms (Android, iOS and UWP).
   Xamarin.Android.Support.v7.AppCompat (>= 28.0.0.3)
2. Appcenter.Auth  support only > 28.0.0.1

Can we bump up the android support version to 28.0.0.3?

**Comment by russelarms** [comment]
Hi, @nithinshiriya! Thanks for reaching out!
> Appcenter.Auth support only > 28.0.0.1
28.0.0.3 > 28.0.0.1 or am I missing something?
Are you able to build your project with the latest Appcenter.Auth version or you're getting compile-time errors that abort the build?

**Comment by nithinshiriya** [comment]
With latest latest xamarin I am getting build error because latest Xamarin uses 28.0.0.3.

**Comment by nithinshiriya** [comment]
If you bump these package to 28.0.0.3 should work fine with latest Xamarin.
Xamarin.Android.Support.CustomTabs (>= 28.0.0.1)
Xamarin.Android.Support.Design (>= 28.0.0.1)
Xamarin.Android.Support.v4 (>= 28.0.0.1)
Xamarin.Android.Support.v7.AppCompat (>= 28.0.0.1)
Xamarin.Android.Support.v7.CardView (>= 28.0.0.1)
Xamarin.Android.Support.v7.MediaRouter (>= 28.0.0.1)

**Comment by MatkovIvan** [comment]
Hi @nithinshiriya 

Due to https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution it should be resolved in with `28.0.0.3` automatically.
Please fill the issue template with all required data including what error did you get and repro steps, it allows us get a fuller picture of what's going on.

**Comment by guperrot** [comment]
@MatkovIvan can repro in android demo solution, this triggered a problem during the release where we test updating xamarin forms

**Comment by MatkovIvan** [comment]
Okay. It's because `Xamarin.Android.Support.*` requires their dependencies with exact version match.

@nithinshiriya you add `28.0.0.3` libraries directly to project to resolve this issue for now.

**Comment by guperrot** [comment]
Version [2.6.1](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.6.1) now depends on support 28.0.0.3.
