### ISSUE TITLE
Xamarin Forms iOS crash with LLVM activated

### ISSUE THREAD

**Issue by ricavir11** [microsoft/appcenter-sdk-dotnet#1168]
### **Description**

Xamarin Forms app crashes when calling AppCenter.Configured method > only if LLVM is activated.
Deactivating LLVM makes app work again.

### **Repro Steps**

1. Activate LLVM on Xamarin Forms iOS project
2. Run app on real iOS device (Build with ARM64 only)
3. App crashes when executing App.configured method

### **Details**

1. Platform :  Xamarin.Forms iOS project 
2. Xamarin.Forms .NET standard 2.0.
3. AppCenter v4.0.30319
4. OS version : iOS 13
5. Using physical device
6. Third party libraries : syncfusion components, ModernHttpClient, MonkeyCache, AutoMapper

**Comment by annakocheshkova** [comment]
Hi there @ricavir11!
I reproduced your issue, thanks for reporting, we will look into that.

**Comment by annakocheshkova** [comment]
Hey, I found out how to deal with this issue. I removed the old app (built with the previous settings) from device, **cleaned the project**, changed the settings to enable LLVM, and installed again. Then it worked perfectly.
I don't have an answer why this happens, but hope it resolves your issue.

**Comment by ricavir11** [comment]
Hi, I had the same behavior aa yours but the prolem cames again after app delivery on appstore over testflight. I have tested the app on several devices with same issue. So right now, I choose to deactivte LLVM to deliver my app ; even if I don't like to do so.

**Comment by annakocheshkova** [comment]
Let me get this right: the issue appears if you install LLVM-enabled app from TestFlight, _even if the app was not installed on the device previously_?
If so, do you have any logs?

**Comment by ricavir11** [comment]
Exactly, the app was not installed on the device. I don't have logs coming from the device when app installed with testflight.
I had logs when I tried with simulator (release configuration). I didn't store them. I just can tell that it was linked with AppCenter "configured" method.

**Comment by annakocheshkova** [comment]
Well it's hard to investigate without any logs. Do you have a possibility of getting those logs? It should be just about connecting the ios device to mac and opening its console.

**Comment by ricavir11** [comment]
Yes I will do. Maybe not now but for next delivery.

**Comment by russelarms** [comment]
Hi @ricavir11,
we haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.
