### ISSUE TITLE
Is Session ID passed to http dependencies?

### ISSUE THREAD

**Issue by felipebrito1** [microsoft/appcenter-sdk-dotnet#1189]
Hi,

If my Xamarin application (instrumented in AppCenter and exporting to Application Insights) makes an Http call to an API (which is also instrumented in Application Insights), is the Xamarin application session id logged in the API app insights event request?

**Comment by guperrot** [comment]
Hi, I am not sure to understand the context of that question, what is the Xamarin application session id? What http call are you referring to?
