### ISSUE TITLE
Cannot use App Center on Xamarin Forms target.

### ISSUE THREAD

**Issue by kevingy** [microsoft/appcenter-sdk-dotnet#1190]
### **Description**

When I call AppCenter.Start() in my Xamarin.Forms (with MvvmCross), I get the error message "[AppCenter] ASSERT: Cannot use App Center on this target."

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Follow the instructions on the app overview page for adding the App Center SDK to the application. (Add Nuget packages, add usings, add call to AppCenter.Start()

Note: My application does not have a OnStart() method in a class that inherits from Xamarin.Forms.Application. The application uses MvvmCross. This code was added to the Start() method in a class that implements the IMvxAppStart interface from MvvmCross. I can confirm that the AppStart method is being run by debugging the Start method with a breakpoint.

2. Update Android app secret to match the app.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
  Xamarin.Forms with MvvmCross on Android and iOS (currently only looking at Android build)
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    .Net Framework 4.5, specifically portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10
2. Which SDK version are you using?
   2.5.0
4. Which OS version did you experience the issue on?
   Android 8.1.0
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    Google Pixel emulator
6. What third party libraries are you using? 
    MvvmCross
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

I placed a breakpoint on the line with AppCenter.Start(). This is the output from a step over that line:

```
11-06 09:13:26.054 D/Mono    (23313): Unloading image System.Diagnostics.Debug.dll [0x8410d500].
11-06 09:13:26.054 D/Mono    (23313): Image addref System.Diagnostics.Debug[0x8bd9caa0] -> System.Diagnostics.Debug.dll[0x8bfa0b00]: 5
11-06 09:13:26.054 D/Mono    (23313): Config attempting to parse: 'System.Diagnostics.Debug.dll.config'.
11-06 09:13:26.054 D/Mono    (23313): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-x86-release/etc/mono/assemblies/System.Diagnostics.Debug/System.Diagnostics.Debug.config'.
11-06 09:13:26.054 D/Mono    (23313): Assembly Ref addref Microsoft.AppCenter[0xa1515460] -> System.Diagnostics.Debug[0x8bd9cb00]: 3
[0:] [AppCenter] ASSERT: Cannot use App Center on this target. If you are using the SDK from a .NET standard library, you must also add the App Center NuGet packages in the Android, iOS and UWP/WPF/WinForms projects as well. Other targets are not yet supported.
```

**Comment by guperrot** [comment]
The nugets need to be explicitly installed in the Android project in addition to the portable project.
Is that the case? With the same versions matching.
If yes, please share the Android csproj (if you still have the old system with packages.config or project.json please share the Android project version of those, do not share the portable project ones).

**Comment by kevingy** [comment]
That was it. I went back and re-read the Overview page. I clearly missed the text saying that the Nuget packages had to be installed in both projects.

Thank you, @guperrot !
