### ISSUE TITLE
Auth on iOS 13 emulator redirects from b2clogin to microsoftonline and fails strangely

### ISSUE THREAD

**Issue by madtownchris** [microsoft/appcenter-sdk-dotnet#1200]
### **Description**

I have replaced the MSAL.NET based authentication (which I had working in both) in my Xamarin Android and iOS app with AppCenter Auth and carefully double-checked all the documentation steps. It is hooked up to my B2C tenant that has a customized login page. Android launches the system browser and shows my login page and login works as expected. iOS launches the system browser first to the xxx.b2clogin.com which appears to redirect to login.microsoftonline.com which then shows a strange page saying nativeclient instead of the expected login page.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create an iOS Xamarin app
2. Integrate Auth via AppCenter with existing B2C tenant
3. Attempt login

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - e.g. Xamarin.Forms on Android and iOS
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
NET standard 2.0.
2. Which SDK version are you using?
AppCenter 2.5
4. Which OS version did you experience the issue on?
iOS 13.2
5. What device version did you see this error on?  Were you using an emulator or a physical device?
iPhone emulator
6. What third party libraries are you using? 
CardsView 2.3.6
NewtonsoftJson 12.0.2
Stripe.net 32.1.3
(a few other MS ones but maybe Microsoft.Identity.Client 4.5.1 is problematic here)

7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
[logfile.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/3825301/logfile.txt)
![ios-auth-problem](https://user-images.githubusercontent.com/19333647/68490341-68d7eb00-020e-11ea-90f0-1e99b414c9ae.png)

**Comment by guperrot** [comment]
Hi, we would need some information about your application, to the very least the app name and owner name so we can look at how it's configured. If that is confidential, please contact us via the support portal button on any page of https://appcenter.ms.

**Comment by richp582** [comment]
I'm seeing the same thing, Xamarin.Forms iOS w/ App Center 2.6.1

**Comment by richp582** [comment]
Actually this was on me... My redirect URL for the App in Azure B2C was incorrect.  I'd double check that compared to the url in your info.plist... the Azure B2C one also needs that ://auth

Hope that helps

**Comment by madtownchris** [comment]
Yup that was the problem. Thanks!
