### ISSUE TITLE
Issue in Installing Microsoft.AppCenter.Crashes Nuget

### ISSUE THREAD

**Issue by anubhavranjan** [microsoft/appcenter-sdk-dotnet#1211]
### **Description**
When installing the _Microsoft.AppCenter.Crashes_ NuGet package, it doesn't automatically install the _Microsoft.AppCenter_ NuGet package, even though it's listed as a dependency.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Open VS 2019 Enterprise
2. Create a blank UWP App
3. Open NuGet Package Manager for Project
4. Search for Microsoft.AppCenter.Crashes
5. Select version to 2.6.1 and Install

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    UWP
2. Which SDK version are you using?
    2.6.1
3. Which OS version did you experience the issue on?
    Windows 10 1903

In the image below, you can clearly see that the NuGet package is not installing the **Microsoft.AppCenter** package on which the **Microsoft.AppCenter.Crashes** is dependent on.
![image](https://user-images.githubusercontent.com/6568809/68746050-c492e180-061d-11ea-8db9-64f20c5b08fc.png)

Here, once the UWP App is built, it results in this error:
![image](https://user-images.githubusercontent.com/6568809/68746186-0b80d700-061e-11ea-9916-b51206418766.png)

**Comment by anubhavranjan** [comment]
Notifying as we saw this issue with a Customer. Installing the dependent package explicitly resolved the error. Also, this is seen when you install v2.5.0 as well. Dependent package was not installed

**Comment by Jamminroot** [comment]
Hey, @anubhavranjan, thanks for reporting this!
We'll have a look at this problem and update you in a thread once we have sometihng to share.

**Comment by guperrot** [comment]
We released a fix for this issue in version [2.6.2](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.6.2).
