### ISSUE TITLE
AppCenter.Crashes has no support if disabled

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter-sdk-dotnet#1231]
I have reported this as a problem as I don't think it works very well. We want to take out our existing unhandled exception handling and replace it with yours. Our issue is that we have allowed for privacy reasons for App Center to be disabled, this then means we have no error handling in our system. We would still have to fall back to some of our event handling logic in the cases where App Center is disabled. If App Center could only be disabled for sending the crash reports then that would be a huge advantage as we could still listen and use your API for detecting that a crash has occurred when it was last run and uploading it to their local database if required.

As it is disabled App Center when just the actually sending of data wants disabling means we have to double up on detecting and handling crashes.

### **Description**

Cannot use App Center for detecting crashes when disabled.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Run the attached sample.
[Test WPF App (2).zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/3897365/Test.WPF.App.2.zip)
2. Click Login (App Center is enabled
3. Click Test Crash
4. Restart the application and you should see a message about the error
5. Click login again and uncheck the enable app center
6. Hit Crash
7. Restart Application and you have no message that it crashed

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - N/A
2. Which SDK version are you using?
    - e.g. 2.6.2
4. Which OS version did you experience the issue on?
    - Windows 10 (1909)
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - PC
6. What third party libraries are you using? 
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here: N/A

**Comment by MatkovIvan** [comment]
Hi @james1301,

Thanks for getting in touch!
When App Center SDK is disabled, it doesn't collect any information and crashes. This is by design.

App Center SDK supports user confirmation dialog for sending a crash report. Also, you can customize it and just don't call any callback until it's allowed. See "[ask for the user's consent to send a crash log](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/wpf-winforms#ask-for-the-users-consent-to-send-a-crash-log)" documentation page for details.

**Comment by james1301** [comment]
So I should always enable crashes, then control using this whether to send?

The Analytics I just enable/disable. If Analytics is disabled and I have the user confirmation for crashes then no data will be sent to App Center without the user confirming?

**Comment by MatkovIvan** [comment]
> So I should always enable crashes, then control using this whether to send?

App Center Crashes module should be enabled to collect crashes, yes.

> The Analytics I just enable/disable. If Analytics is disabled and I have the user confirmation for crashes then no data will be sent to App Center without the user confirming?

No, some piece of data still will be sent - the core package sends the data about started services.

I got your case, but I guess there is no officially supported way to do this.
_If you interested in "any undocumented, unofficial way", you can try to replace `INetworkStateAdapter` to make SDK think that the device is offline._

**Comment by james1301** [comment]
So if I call AppCenter.Start. Then I call AppCenter.SetEnabledAsync(false) straight away will data still be sent to App Center?

**Comment by james1301** [comment]
How do you envisage this working with regards to privacy etc? They select this in like the installer or a first run of the application? Then you never start App Center.

We currently don't have this information until the User logs in.

**Comment by MatkovIvan** [comment]
> So if I call AppCenter.Start. Then I call AppCenter.SetEnabledAsync(false) straight away will data still be sent to App Center?

No, in this case no data will be sent, but it disables all modules include crashes.


> How do you envisage this working with regards to privacy etc? 

There are two ways:
1. Start App Center SDK later (when it's allowed)
2. `AppCenter.SetEnabledAsync`

**Comment by james1301** [comment]
OK so based on this information my initial point at the beginning of this Issue is valid. I cannot use Crashes without the user essentially agreeing to sending some form of data.

Is this something that could be looked at? 

Either:
Being able to disable the base App Center data? But still allowing use of the other services such as crashes

or

Enable crashes to still store and raise events regardless of App Center enabled/disabled, as long as it has been Started

Otherwise due to privacy reasons we either lose visibility of the error or have to right our own code to do the same thing. I would rather not try tampering as that is a big plus for us we are using app center to save on our own code and overriding such things may be liable to break in future.

**Comment by MatkovIvan** [comment]
Currently, App Center SDK doesn't support this scenario. You can [file a feature request](https://github.com/Microsoft/appcenter/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=) and our PMs will triage it.

**Comment by james1301** [comment]
Can do, thanks for your help @MatkovIvan.
