### ISSUE TITLE
MissingMethodException in Microsoft.AppCenter.AppCenter.Start method in Android (Xamarin.Forms) built via AppCenter

### ISSUE THREAD

**Issue by fperez2511** [microsoft/appcenter-sdk-dotnet#1247]
I created a brand new Xamarin.Forms (v4.3.0.991211) app (Android/iOS) then added AppCenter packages (Crash & Analytics) and tried to build it via AppCenter (Debug configuration) and the app fails at runtime with the following exception when trying to call the AppCenter.Start() method:

`
System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions) at Microsoft.AppCenter.AppCenter.PlatformStart (System.String appSecret, System.Type[] services) [0x00021] in <265360be1550438cb9721e9deae216f8>:0 at Microsoft.AppCenter.AppCenter.Start(System.String appSecret, System.Type[] services) [0x00000] in <365360be1550438cb9721e9deae216f8>:0 at ACBasicTest.App.OnStart() [0x00014] in <36bfac746a5b4f9a92c1fbca8ff866eb>:0
`

**Repro Steps**

Please list the steps used to reproduce your issue.

1. Start new project in Visual Studio 2017 Version 15.9.16
2. Choose Xamarin.Forms (Android/iOS) with Shared Project.
3. Configure Android project to compile against Android 9.0 (Pie) as Target and set Minimum Android Version to 7.1.
4. Upgrade Xamarin.Android.Support packages (to versions specified below [6]).
5. Upgrade Xamarin.Forms package (to version specified below [6]).
6. Add Microsoft.AppCenter.Crashes package (version specified below [3]). 
7. Add Microsoft.AppCenter.Analytics package (version specified below [3]).
8. Commit code into repository and configure AppCenter to build branch using Debug configuration and with Android SDK 9.0.
9. Try to run the apk in device/emulator... the error will appear as soon as code tries to call AppCenter.Start().

**Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms on 2 platforms (Android, iOS).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
   - shared project.
2. Which SDK version are you using?
    - 2.6.2
4. Which OS version did you experience the issue on?
    - e.g. Android 7.1 and Android 8.0
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - LG LM-X210 physical device and Android 8.0 emulator
6. What third party libraries are you using? 
    - Xamarin.Forms  Version="4.3.0.991211"
    - Xamarin.Android.Support.Design  Version="28.0.0.3"
    - Xamarin.Android.Support.v7.AppCompat  Version="28.0.0.3"
    - Xamarin.Android.Support.v4  Version="28.0.0.3"
    - Xamarin.Android.Support.v7.CardView  Version="28.0.0.3"
    - Xamarin.Android.Support.v7.MediaRouter  Version="28.0.0.3"
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
    - Unable to collect that information as the app is running from the generated APK and not via a debug session in Visual Studio.

![AppCenter exception 20191205](https://user-images.githubusercontent.com/11177836/70263949-0fa39e80-175d-11ea-882f-594aa9c50f7e.jpeg)

**Comment by fperez2511** [comment]
FYI when you try to build the same code in **AppCenter** but with a **Release configuration** the build fails with the following error:

`
_StripEmbeddedLibraries:
  Creating "obj/Release/strip.flag" because "AlwaysCreate" was specified.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly. [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'Android.App.Application Microsoft.AppCenter.AppCenter::SetWrapperSdkAndGetApplication()' in assembly: 'Microsoft.AppCenter.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.String[] System.String::Split(System.Char,System.StringSplitOptions) [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00013] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x0004a] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00040] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x00098] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00162] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001b] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:    --- End of inner exception stack trace --- [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00047] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue () [0x0000a] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process () [0x00102] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x0000d] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.Process (Mono.Linker.LinkContext context) [0x0000b] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001c] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.ILogger logger, Mono.Linker.LinkContext& context) [0x00071] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x002d4] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute () [0x0021f] in <c304dcc9c82e4174bfeded58a523ee7b>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <2338fdb301034c1d9c6b95e564d514b0>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x00212] in <2338fdb301034c1d9c6b95e564d514b0>:0  [/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj]
Done Building Project "/Users/runner/runners/2.160.1/work/1/s/ACBasicTest/ACBasicTest.Android/ACBasicTest.Android.csproj" (PackageForAndroid target(s)) -- FAILED.

Build FAILED.
`

**Comment by annakocheshkova** [comment]
Hey! Thanks for reporting that, we were able to reproduce it.

**Comment by guperrot** [comment]
This bug should be fixed in version [3.0.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/3.0.0).
