### ISSUE TITLE
MissingMethodException for Crashes.TrackError introduced in ver. 2.6.1

### ISSUE THREAD

**Issue by snakefoot** [microsoft/appcenter-sdk-dotnet#1250]
### **Description**

Breaking change causing MissingMethodException when upgrading from ver. 2.1.1 to ver. 2.6.2 without recompiling everything.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Call method `Microsoft.AppCenter.Crashes.Crashes.TrackError(exception, null)`;
2. Update library without recompiling

### **Details**

Breaking change was introduced with #1170

Removes this method in `Crashes.cs`:

`public static void TrackError(Exception exception, IDictionary<string, string> properties = null)`

And replaces it with this method:

`public static void TrackError(Exception exception, IDictionary<string, string> properties = null, params ErrorAttachmentLog[] attachments)`

Possible to make this a non-breaking change?

**Comment by guperrot** [comment]
Adding an optional parameter at the end of the signature is not a breaking change.

The only way to repro is to have mismatching versions of nugets on the portable project (for example xamarin.forms) and the UWP or Xamarin project for example. We don't support mismatching versions in that case.

**Comment by snakefoot** [comment]
There are different types of breaking changes:

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes

But adding new parameter (even with default parameter) is a "Binary breaking change":

> A binary breaking change happens when you change the public API of your library, so assemblies compiled against older versions of your library are no longer able to call the API. For example, changing a method's signature by adding a new parameter will cause assemblies compiled against the older version of the library to throw a **MissingMethodException**.

**Comment by ahdbilal** [comment]
Thanks for raising this issue. I do acknowledge your point of view and apologize for the trouble it is creating.  In the new version, we have added the capability to send an attachment and that is why we needed this additional parameter. I will work with the team to continue to monitor this change and we will explore possibilities to mitigate the impact of this change.

**Comment by snakefoot** [comment]
Have nothing against new features. But curious why you have chosen `params ErrorAttachmentLog[] attachments` as the final last parameter for this method. Any new extra details that you want to add in the future, will now always become breaking changes unless you start using a new method-name instead of TrackError (Suddenly have multiple method names that will confuse users)

Not sure I understand why email-attachment should have special treatment. Why does it have to use `params` (mostly for `string.Format` and friends), and not just an object that support chaining multiple attachments together. Ex:

`Microsoft.AppCenter.Crashes.Crashes.TrackError(ex, null, emailAttachment.Add(emailAttachment2).Add(emailAttachment3));`

**Comment by ahdbilal** [comment]
Thanks for the suggestion! I will bring this up in my discussion with the team. I will update you once I have more information.

**Comment by pnda489** [comment]
Any hope we can get an overload?

I would like to keep using 

...TrackError(ex)

Took a while to find this error.

**Comment by MatkovIvan** [comment]
Hi @pnda489 ,

Usage of this method with one parameter is still valid. As mentioned above, it's mismatching version problem (between native library and C# wrapper). Please make sure that you are using the same version in a platform and portable projects. Also, try to clean build cache (bin/obj folders) and rebuild the project.

**Comment by guperrot** [comment]
Also we did release a major version that has other breaking changes: [3.0.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/3.0.0). As it is a major version, we allow breaking changes and thus please make a full build again with all projects having a matching version.
