### ISSUE TITLE
Unable to send push notification for android 

### ISSUE THREAD

**Issue by ArchanaMCHP** [microsoft/appcenter-sdk-dotnet#1262]
I am using app center push notifications. I have it configured for android as per the documentation , but when i send a notification , i see 0/0 sent. What does this mean?
Thanks,
Archana

**Comment by Jamminroot** [comment]
Hey!
That usually means that your device wasn't recognized by our backend and wasn't registered for sending push notifications. 
Want you some more help, can you provide more details on what's going on? Having verbose log outputs would really be appreciated.
To enable that, put
```java
AppCenter.setLogLevel(Log.VERBOSE);
```
Right before calling `AppCenter.start(...)`

**Comment by Jamminroot** [comment]
I'm closing the issue since it looks like a question. But please feel free to reopen, need you more support, I'd then change it to support and proceed with the investigation.
