### ISSUE TITLE
When will AppCenter use the latest major Sqlite version?

### ISSUE THREAD

**Issue by jay1891** [microsoft/appcenter-sdk-dotnet#1264]
Currently we can't upgrade the sqlite library because AppCenter is not following the latest major sqlite version. When will AppCenter use the latest major sqlite version?

**Comment by dragnilar** [comment]
+1 to this; this causes a conflict with one of my production apps which uses the latest version of EF Core's Sqlite provider. I had to roll back the provider since it was causing App Center to fail to start in the background. :(

**Comment by MatkovIvan** [comment]
Hi there,

It's already in our radar and this is not the first issue related to it (but it is not exact duplicate).
Unfortunately it's not just about changing the dependency version, it requires some changes in App Center SDK and probably bumping minimal supported OS version.

We'll keep you updated.

**Comment by seankanderson** [comment]
+1 Had to remove all AppCenter SDK packages from my application because the SDK brought an earlier version with it causing build failures on a Xamarin Forms UWP application.

**Comment by Jamminroot** [comment]
Hey, @seankanderson 
[Pull request](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1246) is pending, [milestone](https://github.com/microsoft/appcenter-sdk-dotnet/milestone/2) assigned. No ETAs we could provide yet, though.

**Comment by seankanderson** [comment]
Good to hear.  Just today I had to commit to upping my EFCore and Sqlite versions which meant I had to dump AppCenter again.  Going to try AppInsights until this fix is released.

**Comment by bruzkovsky** [comment]
@Jamminroot great news! Any chance of an ETA now? We are on our toes waiting for the release! 😃

**Comment by Jamminroot** [comment]
Can't provide any determined ETA - just as per the milestone name, it will be out somewhere soon in January :)

**Comment by mklemarczyk** [comment]
The SQLite issue right now causes the issue with sending app to the store.
It does not pass the certification step: "Supported API test".

**Comment by jwallra** [comment]
Hi all, just wanted to give everyone who's waiting on this fix a heads up that we had to move our next release back to February.  Sorry for the delay, we'll get it to you as soon as we can.

**Comment by guperrot** [comment]
We released the sqlite update in version [3.0.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/3.0.0).
