### ISSUE TITLE
PushNotificationReceived is getting called multiple times periodically

### ISSUE THREAD

**Issue by adrianknight89** [microsoft/appcenter-sdk-dotnet#1277]
### **Description**

I have integrated the Push framework with a Xamarin Forms application. Recently, I noticed `PushNotificationReceived` is being fired periodically (once every few minutes) after a push is received from the server. I feel that this issue cropped up in one of the latest updates. In the logs, I frequently see `Error while delivering the message: ServiceIntent not found.` errors.

```
protected override void OnStart()
{
    base.OnStart();

    if (!AppCenter.Configured)
    {
         Push.PushNotificationReceived += (sender, e) =>
         {
         };
     }

    AppCenter.Start("...");
}
```

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms on Android and iOS
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.1.
2. Which SDK version are you using?
    - 2.6.4
4. Which OS version did you experience the issue on?
    - iOS 13, Android 9
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - physical device / iPhone XR and Samsung S9
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
    - I can only email it to you if you like.

**Comment by olmisa** [comment]
Hi @adrianknight89, thanks for bringing this to our sight.
We are looking at the issue. Please share the logs through the 'Intercom' support channel (blue button on the App Center portal at the right bottom).

**Comment by ilyashumihin** [comment]
Hi!
We haven't heard from you in a while, so I am going to close this conversation. Should you still have any questions, please contact us again.
