### ISSUE TITLE
Push throwing ClassNotFoundException using Xamarin.Android 10.1.1.0

### ISSUE THREAD

**Issue by ElteHupkes** [microsoft/appcenter-sdk-dotnet#1283]
### **Description**

After updating Visual Studio for Mac yesterday to the version that includes Xamarin.Android 10.1.1.0, my app crashes with a `ClassNotFoundException` (wrapped in a `TypeLoadException`) upon launch:

```
Didn't find class "md5f5913e8e0b500178c9303bd577a3f1aa.PushListener" on path: DexPathList[[zip file "/data/app/our-app-name-1/base.apk"],nativeLibraryDirectories=[/data/app/our-app-name-1/lib/x86, /data/app/our-app-name-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
```

The problem appears to be the [breaking change for generate Java type names](https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.1#breaking-change-for-generated-java-type-names), because after adding the fallback to my csproj:

```
<PropertyGroup>
    <AndroidPackageNamingPolicy>LowercaseMD5</AndroidPackageNamingPolicy>
</PropertyGroup>
```

the error disappears. That's an acceptable workaround for now, but it will stop working with Xamarin.Android 10.2.

### **Repro Steps**

I'm assuming this will happen for any Xamarin.Android app with Push (and maybe other components). For me the exception is thrown when doing `Push.PushNotificationReceived += SomeMethod;`.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - e.g. .NET standard 2.0.
2. Which SDK version are you using?
    - e.g. 2.6.4
4. Which OS version did you experience the issue on?
    - Android MarshMallow (API 23)
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Emulator
6. What third party libraries are you using? 
    - A lot, but I don't think they're relevant. If I'm wrong please let me know.
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
 - Since the error seems pretty clear to me I'm going to lazy out on this one unless it's necessary too ;).

**Comment by olmisa** [comment]
Hi @ElteHupkes.
Thanks for getting in touch! We are looking at the issue but I was not able to reproduce it. I need a little bit more time for investigation.

**Comment by ElteHupkes** [comment]
@olmisa Hm, I assumed it would be an easy repro! I'll see if I can concoct something myself.

**Comment by ElteHupkes** [comment]
Ok this is strange, a fresh project does indeed not reproduce it for me, although I've been trying to set all Android options the same. My actual project still definitely does reproduce the problem and it still definitely goes away setting `AndroidPackageNamingPolicy`. I'll try to see if I can work backwards (i.e. delete stuff from my existing project instead of trying to match its structure) to figure out what the hell is going on here. Something, somewhere is holding on to that old `md5...` name...

**Comment by ElteHupkes** [comment]
Haha ok well there's a few hours of my life I'm never getting back... I had previously deleted all `bin` and `obj` folders to no avail, but finally I started with a fresh repository with no caching directories that I didn't know about whatsoever. Lo and behold: now it works. I hate this magic 😆. Oh well, nothing to see here, sorry for wasting your time ✌️.
