### ISSUE TITLE
Cannot install in .NET Core 3.1 WinForms project

### ISSUE THREAD

**Issue by EatonZ** [microsoft/appcenter-sdk-dotnet#1305]
### **Description**

I am getting a lot of errors when trying to install AppCenter in my .NET Core 3.1 project. I think this issue may go away with the next version since you're removing sqlite-net-pcl, but I wanted to make sure...
![2020-01-22_23-59-31](https://user-images.githubusercontent.com/3020941/72958356-fee2d280-3d74-11ea-9bb3-b8d55e45eaac.png)

### **Repro Steps**

The issue seems to be unique to my project - doesn't seem to happen in new apps.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WinForms
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET Core 3.1
2. Which SDK version are you using?
    - 2.6.4
4. Which OS version did you experience the issue on?
    - Windows 10 1909 64bit
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical desktop PC
6. What third party libraries are you using? 
    - DevExpress, ServiceStack.Text

**Comment by annakocheshkova** [comment]
Hi! As mentioned in the error itself, the temporary solution is either to silence those warnings (for example, on my project they are not errors, just warnings), or to reference the mentioned libraries directly in your project. 
Yes, this error should go away in the next releases.

**Comment by EatonZ** [comment]
@annakocheshkova I'll see how things look in the next version.🙂

**Comment by EatonZ** [comment]
Issue no longer occurs in App Center 3.0.0.
