### ISSUE TITLE
Do we need to initialize SDK from Xamarin.Forms when we already initialize it from Xamarin Native?

### ISSUE THREAD

**Issue by xyfoo** [microsoft/appcenter-sdk-dotnet#1309]
## Background
Xamarin.Forms app running on Android & iOS.
The app will be calling native platform's background services (WorkManager/NSUrlSession).

## What we want to do
Tracking events & crashes from logics residing both in Xamarin.Forms layer as well as Xamarin Native layer.

_Example: Able to track attempt upload request (using Analytics) from Xamarin.Forms, and track it's completion from Xamarin Native's services._

## What we're doing now

| Platform | |
|--|--|
| Xamarin.Forms | Initialize in `App() `in `App.xaml.cs` |
| Xamarin.Android | Initialize in `Application.OnCreate` callback |
| Xamarin.iOS | Initialize in the `FinishedLaunching()` of the `AppDelegate.cs` |

We're able to receive crashes & events both from Xamarin.Forms & Xamarin Native logic.

## Question

Is this the right way to start the SDK or is there any gotcha despite the result? Is the `Start()` method an idempotent operation?

**Comment by AnastasiaKubova** [comment]
Hi, @xyfoo ! Thanks for getting in touch with us!
`AppCenter.Start` should be called only once either in `Xamarin. Forms` or in the both `Xamarin.Native` projects for iOS and Android. After that, the events and crashes will be work expected for both `Xamarin.Forms` and `Xamarin.Native`. If you call `AppCenter.Start` more than one time that all these calls will be ignored.

**Comment by xyfoo** [comment]
Thanks for the answer, @AnastasiaKubova !
