### ISSUE TITLE
App Center Crashes don't use previous userid at the time of crash

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter-sdk-dotnet#1322]
### **Description**

Our application always starts up and then the user chooses a database and logs in. If a crash occurs, the app center sdk doesn't allow for that crash to be sent with those previous user details. We could wait until they login to start crashes but then it could be a different user or a different database. This would also miss prior crashes in the start-up before logging in.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create application whereby the user id is set after logging in
2. Create crash
3. Re-run application
4. Crash report gets sent with no user id

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - N/A
2. Which SDK version are you using?
    - 2.6.4
4. Which OS version did you experience the issue on?
    - Windows 10 1909
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - PC
6. What third party libraries are you using? 
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
N/A

**Comment by russelarms** [comment]
Hi @james1301, thanks for reaching out!

Have you tried to save **userId** after logging in [LocalSettings](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.ApplicationData?redirectedfrom=MSDN#Windows_Storage_ApplicationData_LocalSettings) and apply it after restarting the application?

**Comment by james1301** [comment]
@russelarms could do yeah that sounds good. 

Is it OK to then change it again then later? When they do actually sign in.

**Comment by guperrot** [comment]
We actually support setting userId before crash as all properties, including userId and application version are snapshotted at crash time. If it does not work for you we need to troubleshoot what went wrong.

Can you please enable verbose logging as suggested in the issue template and share logs for the run that crashes and also the run that restart to send it? Can you add an handled error (trackError) before crashing to verify that one has userId?

**Comment by guperrot** [comment]
We haven’t heard from you in a while, do you have any more questions? If so, please let us know and reopen the ticket if needed.
Thanks for using App Center!
