### ISSUE TITLE
UWP compiler error of duplicated e_sqlite3.dll when using EFCore.SQLite

### ISSUE THREAD

**Issue by chrisweihu** [microsoft/appcenter-sdk-dotnet#1323]
### **Description**
AppCenter UWP has a dependency on sqlitepclraw.lib.e_sqlite3.v140\1.1.12\...\e_sqlite3.dll. It causes compiler to throw this error when trying to Microsoft.EntityFrameworkCore.Sqlite.

Error: Payload contains two or more files with the same destination path 'e_sqlite3.dll'. Source files:
C:\Users\chu\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.0.2\runtimes\win10-x64\nativeassets\uap10.0\e_sqlite3.dll
C:\Users\chu\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.12\runtimes\win10-x64\native\e_sqlite3.dll

People tried to log this bug on EFCore but EFCore said this is an AppCenter bug. 
https://github.com/dotnet/efcore/issues/19156

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create an Xamarin.Forms project which will include a UWP project
2.Install AppCenter and Microsoft.EntityFrameworkCore.Sqlite nugets on UWP projekt
3. compile, and see the error pops up

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
   Xamarin.Forms on all 3 platforms (Android, iOS and UWP).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    NET standard 2.0.
2. Which SDK version are you using?
    - 2.6.4
4. Which OS version did you experience the issue on?
    UWP
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    Windows 10
6. What third party libraries are you using? 
Xamarin.Forms
Microsoft.EntityFrameworkCore
Microsoft.EntityFrameworkCore.Sqlite
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by MatkovIvan** [comment]
Hi @chrisweihu ,

The current version uses sqlite 1.x that incompatible with 2.x. It is mentioned in the issue that you posted. The next version of SDK will use 2.x, the release is planned this month.

Closing as duplicate.
Related issues: #1092 #1313 #1085 https://github.com/microsoft/appcenter/issues/1460
