### ISSUE TITLE
System.MissingMethodException: 'Method not found'

### ISSUE THREAD

**Issue by Orgbrat** [microsoft/appcenter-sdk-dotnet#1340]
### **Description**

Running sqlite-net (v1.6.292) in latest xamarin forms (v4.5.0.282) application along side Microsoft.AppCenter.Analytics and Crashes (v2.6.4) with no issues. I upgraded Microsoft.AppCenter.* from 2.6.4 to 3.0.0 today and now sqlite-net crashes on first execution of CreateTable such as database.CreateTable

(); with the below error message.
System.MissingMethodException: 'Method not found: 'System.String SQLitePCL.raw.sqlite3_column_name(SQLitePCL.sqlite3_stmt, Int32)'.'

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. With sqlite-net v1.6.292 installed, upgrade Appcenter.Crash and AppCenter Analytics from v2.6.4 to v3.0.0 and now xamarin app crashes.

### **Details**

1. Xamarin.Forms on all 3 platforms (Android, iOS and UWP).
2. .NET standard 2.0.
2. Which SDK version are you using?
    - e.g. 1.5.0
4.  iOS 12.1, Android 9.0.0, Windows 10.0.16299
5.. iPhone X simulator, Google Pixel 2 emulator, UWP physical deviuce
6.   <ItemGroup>
    <PackageReference Include="Acr.UserDialogs" Version="7.0.35" />
    <PackageReference Include="Dropbox.Api" Version="4.9.4" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.43.0.1860" />
    <PackageReference Include="Humanizer" Version="2.7.9" />
    <PackageReference Include="LiveXAML" Version="2.1.73" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="2.6.4" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="2.6.4" />
    <PackageReference Include="Microsoft.Graph" Version="1.21.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.8.2" />
    <PackageReference Include="Refractored.MvvmHelpers" Version="1.6.1-beta" />
    <PackageReference Include="sqlite-net-pcl" Version="1.6.292" />
    <PackageReference Include="Syncfusion.Xamarin.Buttons" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.Pdf" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfBusyIndicator" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfCalendar" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfComboBox" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfMaskedEdit" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfNumericTextBox" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfNumericUpDown" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfPdfViewer" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfPicker" Version="17.4.0.50" />
    <PackageReference Include="Syncfusion.Xamarin.SfPopupLayout" Version="17.4.0.50" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="4.5.0.282-pre4" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.0-pre1" />
    <PackageReference Include="Xamarin.Forms.DebugRainbows" Version="1.1.4" />
    <PackageReference Include="Xamarin.Plugin.FilePicker" Version="2.1.36-beta" />
  </ItemGroup>
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by guperrot** [comment]
AppCenter SDK v3.0.0 is not compatible with sqlite-net-pcl v1.6.292 because AppCenter needs to use SQLitePCLRaw.bundle_green v2.0.2 for Arm64 support while sqlite-net-pcl v1.6.292 is still using SQLitePCLRaw.bundle_green v1.1.13 (and there are breaking changes in SQLitePCLRaw between v1 and v2).

The only solution today seems to, unfortunately, use the beta of sqlite-net-pcl: https://www.nuget.org/packages/sqlite-net-pcl/1.7.302-beta. This beta version depends on SQLitePCLRaw.bundle_green v2.0.2, the same version as AppCenter now depends on.

**Comment by daltonks** [comment]
I am running into this same issue when using `Microsoft.EntityFrameworkCore.Sqlite` version 2.2.6 in a UWP project.

**Comment by daltonks** [comment]
Attempting to use AppCenter 3.0.0 with EF Core 3.1 looks promising so far, but I notice that EF Core doesn't use bundle_green: https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#microsoftentityframeworkcoresqlite-now-depends-on-sqlitepclrawbundle_e_sqlite3

Could there be any potential SQLite problems using EF Core 3.1 alongside AppCenter 3.0.0?

**Comment by Jamminroot** [comment]
EF Core itself won't have dependency on sqlite; What you might want to look at, is [sqlite provider nuget](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite/3.1.0) which has dependency on SQLitePCLRaw > 2.0.2
And it fits AppCenter dependencies (ver. 3.0.0 and onwards).

**Comment by norton287** [comment]
Same issue on Xamarin.Forms UWP getting the following errors before crash:

Exception thrown: 'System.MissingMethodException' in Microsoft.Azure.Mobile.Client.SQLiteStore.dll
'GroceryList.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\microsoft.net.coreframework.debug.2.2_2.2.27909.0_x64__8wekyb3d8bbwe\System.Diagnostics.StackTrace.dll'. 
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
'GroceryList.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\microsoft.net.coreframework.debug.2.2_2.2.27909.0_x64__8wekyb3d8bbwe\System.IO.FileSystem.dll'. 
Exception thrown: 'System.Reflection.TargetInvocationException' in GroceryList.UWP.exe
The program '[20788] GroceryList.UWP.exe: Program Trace' has exited with code 0 (0x0).
The program '[20788] GroceryList.UWP.exe' has exited with code -1 (0xffffffff).

The v2.6.4 nuget works fine its just after upgrading to 3.0

**Comment by Jamminroot** [comment]
@norton287 can you elaborate a bit - did you try bumping SQLitePCLRaw version to 2.0.2? And by adding SQLite beta nuget which nuget exactly you mean?

**Comment by norton287** [comment]
This beta nuget sqlite-net-pcl 1.7.302-beta and SQLitePCLRaw.bundle_green

 

Even with both of those it still crashes on loading mobileservice tables for azure

**Comment by Jamminroot** [comment]
@norton287 do you mean that azure mobile services SDK crash on attempt to sync tables?

**Comment by norton287** [comment]
With 3.0 of appcenter packages not the 2.6.4.  And it only happens on UWP.
________________________________

**Comment by norton287** [comment]
Yes with appcenter 3.0 packages installed on my Xamarin.Forms UWP app.  It does not occur with Appcenter 2.6.4 packages installed in my UWP App.

The crash occurs as soon as it tries to load the offline tables to sync with azure.

**Comment by owlstronaut** [comment]
@norton287 

Please confirm the following:
* sqlite-net-pcl 1.7.302-beta
* SQLitePCLRaw.bundle_green v2
* App Center 3.0
* Clean, Rebuild

If all those are correct and you still have issues, is **Azure Mobile Services SDK** crashing, or is the **App Center SDK** crashing?

**Comment by norton287** [comment]
The combination of all those factors is causing Azure Mobile Service SDK to crash on loading tables at app start.

**Comment by Jamminroot** [comment]
Sorry for misunderstanding.
I see what you meant now. Yes, with latest release we changed dependencies for AppCenter SDK. For now you are not able to use latest App Center SDK alongside with azure mobile apps.
Can you open an issue on azure mobile apps repo to update sqlite version used?

**Comment by norton287** [comment]
I have opened an issue with Azure Mobile Apps but whether they will do anything is not known.  They have made it known that Azure Mobile Apps is in sunset mode with no new features at all.  Hopefully they will treat it like a bug.

**Comment by Jamminroot** [comment]
I've responded in the [new issue](https://github.com/Azure/azure-mobile-apps-net-client/issues/533/). Progress will be tracked there

**Comment by norton287** [comment]
Ok Dmitrii
