### ISSUE TITLE
Got "ASSERT: Cannot use App Center on this target." error

### ISSUE THREAD

**Issue by baobao1270** [microsoft/appcenter-sdk-dotnet#1350]
### **Description**
I got an "ASSERT: Cannot use App Center on this target." error when I develop an WPF Application on Visual Studio 2019.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install App Center from nuget
2. Add `AppCenter.Start` to my `OnStart` method
3. Start Debugging
4. Got an error:
```
[AppCenter] ASSERT: Cannot use App Center on this target. If you are using the SDK from a .NET standard library, you must also add the App Center NuGet packages in the Android, iOS and UWP/WPF/WinForms projects as well. Other targets are not yet supported.
```

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - e.g. Xamarin.Forms on all 3 platforms (Android, iOS and UWP).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET Framework 4.5
2. Which SDK version are you using?
    - 3.0.0
4. Which OS version did you experience the issue on?
    - Windows 10 Home 18363.657
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - HP Pavilion 15-cx0059dx
6. What third party libraries are you using?
```
<packages>
  <package id="Microsoft.AppCenter" version="3.0.0" targetFramework="net45" />
  <package id="Microsoft.AppCenter.Analytics" version="3.0.0" targetFramework="net45" />
  <package id="Microsoft.AppCenter.Crashes" version="3.0.0" targetFramework="net45" />
  <package id="Microsoft.Graph" version="1.21.0" targetFramework="net45" />
  <package id="Microsoft.Graph.Auth" version="1.0.0-preview.4" targetFramework="net45" />
  <package id="Microsoft.Graph.Core" version="1.20.0" targetFramework="net45" />
  <package id="Microsoft.Identity.Client" version="4.9.0" targetFramework="net45" />
  <package id="Newtonsoft.Json" version="12.0.3" targetFramework="net45" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net45" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.7.0" targetFramework="net45" />
  <package id="System.Memory" version="4.5.3" targetFramework="net45" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.7.0" targetFramework="net45" />
  <package id="System.Security.Principal" version="4.3.0" targetFramework="net45" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net45" />
</packages>
```
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
```
[AppCenter] ASSERT: Cannot use App Center on this target. If you are using the SDK from a .NET standard library, you must also add the App Center NuGet packages in the Android, iOS and UWP/WPF/WinForms projects as well. Other targets are not yet supported.
```

**Comment by baobao1270** [comment]
I changed my application target to .NET 4.7 and reinstall all nuget packages solved the problem. Hoverer, the documention tells me I can use it on .NET Framework 4.5. I hope this problem can be solved.

**Comment by guperrot** [comment]
The 3.0 SDK is not compatible with .NET Framework 4.5. The minimum is 4.6.1 now.
You can find changelog at https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/3.0.0.
Some documentation pages were updated to reflect this but if there is another outdated page we will need to update it.

**Comment by guperrot** [comment]
The docs have been fixed to mention the minimum version of .NET Framework 4.6.1.
