### ISSUE TITLE
How to avoid login to AppCenter when APP is distributed via Stores

### ISSUE THREAD

**Issue by BitProgress** [microsoft/appcenter-sdk-dotnet#1367]
I use "Distribute.UpdateTrack = UpdateTrack.Private;" to force the login to AppCenter during development to support distribution to private groups.
When the APP is going to be released via the Stores, how do I disable the AppCenter login without modifying the code?

**Comment by annakocheshkova** [comment]
Hi there @BitProgress! As I see, there are 2 options here. You can either set the track at the app start based on the app mode (Debug/Release) or add an UI switch if that's more appropriate in your case.

**Comment by annakocheshkova** [comment]
I'm closing the issue, if you have any more questions, feel free to re-open!
