### ISSUE TITLE
Creating generic method for userInfo called AppCenter.SerUser()

### ISSUE THREAD

**Issue by minaairsupport** [microsoft/appcenter-sdk-dotnet#1383]
**Is your feature request related to a problem? Please describe.**
yea we duplicate a lot of code to make the same behavior 

**Describe the solution you'd like**
Create a generic method to track user behavior (crash, analytics ...etc ).
my suggestion is very simple and I got inspired by another framework made it generic method call one time called `AppCenter.SerUser() ` which accept `UserInfo` Object 
UserInfo is object contain at least `Id, userName, Dictionary` for a custom property 

the impact of the change will reduce the push of duplicate code as an example in our project
we called methods to track error or tract event with user data, we keep duplicate this service to get user data and stored it on dictionary format hundreds of times 

`Crashes.TrackError(e, await _userInfo.GetUserInfo()); `
`Analytics.TrackEvent(eventName, await _userInfo.GetUserInfo());`

I hope I could explain the importance of this feature and how it will save time for us

**Comment by DmitriyKirakosyan** [comment]
Hi @minaairsupport 

Thank you for this feature request!
Actually, we already have such request in main repo: https://github.com/microsoft/appcenter/issues/2335, so I'll close this item as a duplicate. Let's follow the progress in main repo's issue.
