### ISSUE TITLE
System.Exception in UWP app

### ISSUE THREAD

**Issue by tipa** [microsoft/appcenter-sdk-dotnet#1396]
### **Description**
In my Windows UWP app I am receiving crash reports that I cannot really figure out how to prevent / fix. Based on the stack trace it feel it seems be related to this SDK.
Interestingly, this crash only seems to happen on one single machine (running 10.0.18362). As there is a crash report coming in every 15 mins (UWP background task), I think it crashes in `AppCenter.Start` which I calling my `Application` constructor

Here's the crash:
```
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)
System.Exception: Element nicht gefunden. Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.
```
```
System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32 hr, RuntimeTypeHandle typeHnd) f:\dd\ndp\fxcore\CoreRT\src\System.Private.Interop\src\Shared\McgMarshal.cs at 1189:13
__Interop
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)
__Interop
ForwardComStubs.Stub_15[TThis] (__ComObject, Int32)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.<ctor>b__17_1 (Object, UnhandledErrorDetectedEventArgs)

```

I am using the latest SDK from NuGet and I am targeting the latest Windows platform 2004.

**Comment by annakocheshkova** [comment]
Hi there! As I understand, your application is [failing here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/26c80e05efaed11f0b3ee2ec79d3b6f0485bd2c1/SDK/AppCenter/Microsoft.AppCenter.UWP/Utils/DefaultScreenSizeProvider.cs#L55). Ideally, it should [fall under the catch statement](https://github.com/microsoft/appcenter-sdk-dotnet/blob/26c80e05efaed11f0b3ee2ec79d3b6f0485bd2c1/SDK/AppCenter/Microsoft.AppCenter.UWP/Utils/DefaultScreenSizeProvider.cs#L85) and log this as warning if MainView is not ready to be accessed yet.

`DisplayInformation.GetForCurrentView` is UI-sensitive, so it depends on the window the current thread is associated with.

Having said that, there are 2 points I would like to clarify:
- Are you starting App Center from background or foreground? Could you share a snippet and place where you start it?
- Is the exception crashing your app or is it logged properly? Could you share Verbose logs?

**Comment by tipa** [comment]
I thought so too - at first. But now I see other (AppCenter unrelated) exceptions with the same stack trace and start to assume it is simply catching an unhandled exception [here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/26c80e05efaed11f0b3ee2ec79d3b6f0485bd2c1/SDK/AppCenter/Microsoft.AppCenter.UWP/Utils/ApplicationLifecycleHelper.cs#L84) (even though I don't call GetForCurrentView() anywhere in my app, but maybe some of the libraries I am using is?!)
Anyways, feel free to close this issue as I think the problem is located somewhere else.

I am starting AppCenter right after my app starts. The exception seems to crash my app has it wasnt handled in my app.
```
public App()
{
    AppCenter.Start("...", typeof(Analytics), typeof(Crashes));
    InitializeComponent();
    ...
}
```

**Comment by annakocheshkova** [comment]
Yeah, this is correct - as part of the Crashes module we catch unhandled exceptions, [track them](https://github.com/microsoft/appcenter-sdk-dotnet/blob/e42944a6345d507c5f19e7769cac764f69807bff/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Windows.Shared/Crashes.cs#L79) and then "re-throw" them, so yeah, `ApplicationLifecycleHelper` appears in the stacktrace. 
It should be tracked in App enter so you might get more info from there. 

Anyway I'm closing this issue, feel free to re-open if you need any more help!
