### ISSUE TITLE
Best way to hide the AppCenter keys (pen test issues)

### ISSUE THREAD

**Issue by developer9969** [microsoft/appcenter-sdk-dotnet#1397]
Hi 
We are currently storing the appcenter keys in the app as we do not have an alternative.
We have placeholders for the keys in code  and in the pipeline when we build the app we substitute those placeholders with the actual keys, however someone can still

Decompile the app and get the keys.

What is  your recommendation to best hide the keys?
What damage can someone do if they get the keys?

Solution

- Make a web api call (secure endpoint) to get the keys (webapi calls keyvault in azure)
- Use certificate pinning (no current example out there on how todo with xamarin forms)
- Store the keys in keychain.

Surely this is an issue !!

Any suggestions?

**Comment by annakocheshkova** [comment]
Hi there! If you are concerned with the app's security, the best way would be to store the keys in the keychain. Key vault is also a good option.

As for the sensibility of the app secret itself, it allows you to do pretty much everything sdk does - send logs, get _public_ releases etc. If that's something you're concerned about, then this is an issue. But all the actually _sensitive_ requests require the app/user token. 

You can take a look at [OpenAPI](https://openapi.appcenter.ms/#/distribute/devices_getReleaseUpdateDevicesStatus) - all the "public" requests require just app secret. All the others - must also provide a token.

You can read more about app/user tokens [here](https://docs.microsoft.com/en-us/appcenter/api-docs/). But pay attention that this is _not_ related to app secret.

**Comment by developer9969** [comment]
Hi there thanks for your reply.
Unless I am missing the  obvious the problem I see with keychain or keyvault is that you still have to have the keys embedded within your app at some point, till you can store them in the keychain, and someone could decompile the app and see the keys...

Regarding using keyvault in the mobile app I have not seen any example out there using keyvault,but I suppose I would have to expose the connectionstring.

Is there an example using keyvault?

Can I store keys in the keychain whilst I am building the app in my pipeline?

**Comment by AnastasiaKubova** [comment]
Hi @developer9969 , unfortunately for now there is no way to be 100% secure about the `app_secret` and it is just token.  
You can have your CI/build system inject your AppSecret into your code via an environment variable so that at least the AppSecret is not in clear in the code.

**Comment by AnastasiaKubova** [comment]
We haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.

**Comment by gersontpm** [comment]
It's been a while since last message here, and currently  we have the same situation. So, what I've learned about this topic, is, as @AnastasiaKubova said: ...there is no way to be 100% secure.., so, at the end, the key is to increase the cost of reveal secret data, comparing to the cost of the data itself.

That way thieves should think twice if is it worth to start the reverse engineering process to get the secrets.

**Comment by gersontpm** [comment]
thanks for reply, @DmitriyKirakosyan. I'm wondering is "Environment variables" section a secure place to store my app_center key?. Where I can get more info about treated app secret as an app id, because I don't understand completely how is that. Thanks!

**Comment by DmitriyKirakosyan** [comment]
@gersontpm , if your environment variables are set in a secure environment, then why not.

> Where I can get more info about treated app secret as an app id, because I don't understand completely how is that.

This is just my personal expression. The app secret is not a secret in a common sense. It can't access your data, it is more like a key that is used to identify your app and send logs to it. That is why I call it app id.

**Comment by gersontpm** [comment]
I mean, "Environment variables" in build configuration on Appcenter platform. ¿Is that a secure place?

**Comment by developer9969** [comment]
> Hi @gersontpm, the app secret cannot be used to reveal secret data. They app secret can be treated as an app id. It is used to send data to AppCenter to a specific application. The worst thing that can happen is that an attacker can send some random analytics data to your application.
> 
> The best practices is to keep the app secret in secure place and inject it into your code at build time.

Hi there , that is what we do - but because .net does not offer obfuscation out of the box the api key is there for all to see , and a keen pen tester will decompile the all app and point out to the client that we are exposing keys!!  then we have to justify to the client that using that key is "harmeless" as they can only send analitcs data but we still have to justify it..  so one option is to get the key only when authenticated via some api call - and anything before that - no logs.. stuffed arent we.

**Comment by gersontpm** [comment]
thanks!! :-)
