### ISSUE TITLE
Optionally use ExecutingAssembly for GetAppVersion()

### ISSUE THREAD

**Issue by keithrowe** [microsoft/appcenter-sdk-dotnet#1405]
We are developing an Outlook addin using Winforms/WPF. We are able to use the AppCenter Analytics and Crash tracking. But, the version presented on the AppCenter site is being retrieved from Outlook rather than our addin.

DeviceInformationHelper.GetAppVersion() seems to get the AssemblyInformationalVersion from Application.ProductVersion. It would be great to optionally be able to get this from Assembly.GetExecutingAssembly(). 

Another alternative would be to allow us to override the version number captured by DeviceInformartionHelper from an API.

To work around this, we currently record the addin's InformationalVersion as part of a custom event. This works when we analyze logs in Application Insights, but we don't have an easy way for the team to find results for a particular build on the AppCenter site.

**Comment by russelarms** [comment]
Hi @keithrowe, thanks for opening the feature request!
I'll discuss it within the team and get back to you soon.

**Comment by russelarms** [comment]
I think it would be a reasonable fix for plugins and addins. I've notified our PM, but there's no ETA yet.

**Comment by EatonZ** [comment]
Related: https://github.com/microsoft/appcenter/issues/1313

**Comment by vvechkanov** [comment]
@EatonZ thank you for mentioning related request.

**Comment by vvechkanov** [comment]
Hi @keithrowe!

As @EatonZ mentioned there is an existing feature request about manually set appVersion. I suggest that we track this feature in one place.

I'll close this for now, but if you think that microsoft/appcenter#1313 does not cover your request, please feel free to comment and/or reopen this issue.

**Comment by keithrowe** [comment]
This request is a new wrinkle on [microsoft/appcenter#1313](https://github.com/microsoft/appcenter/issues/1313). I agree that it can be covered in the same feature work.
