### ISSUE TITLE
Customize AppCenter.config file location

### ISSUE THREAD

**Issue by Fampov** [microsoft/appcenter-sdk-dotnet#1409]
**Problem:**
Every update of my application creates a new directory and AppCenter.config file rather than reusing the existing one. This appears to be due to us using squirrel to auto-update. 

All of our updates do install to a single directory, but all the dlls and version specific content are stored in a separate sub-directory. This is one of squirrel’s best features in that users can be working in our app, have an update download and install in the background, and then on the next startup the new updates are used automatically without prior sessions being affected. Squirrel then hangs on to the old dlls as a backup until the next update comes in which the old directory is deleted, the current becomes the old, and a new directory for the updated dlls is created.

![image](https://user-images.githubusercontent.com/23152866/86388044-4f7a2800-bc51-11ea-8655-7ce3eed66108.png)

Our problem then seems to be that because the directories that are being referenced by the SDK have a version number on them, each update is viewed as a new install rather than an update. This then results in all data being sent to app center duplicating users and displaying inaccurate information.

**Ideal solution**
It seems like this issue could easily be solved by allowing applications to specify where the AppCenter.config file is stored. By allowing us to set it alongside other config files for the application, it would simplify finding and interacting with all application files as well as prevent duplication issues when different technologies differ in where the executable and dlls are stored.

**Alternative solution that works just as well**
If specifying a location is more problematic than it seems, alternatively some way to configure what file path to use in relation to the executable when generating the hash for the directory would also suffice. It even seems like this is already being done to a degree in order to avoid my same problem, difference being it goes up one level where I'd need it to go up two:

https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DefaultApplicationSettings.cs#L140

**Comment by AnastasiaKubova** [comment]
Thanks for getting in touch, our team will discuss this feature request.
To anyone who also interested in this: please upvote/like this feature request so we can proper triage and prioritize it.

**Comment by EatonZ** [comment]
I ran into a similar problem where AppData\\Local\\[name] was getting filled with a lot of folders by AppCenter. As soon as the exe's path is changed, a new folder is created with a hash based on the path.

My workaround was to strong-name sign the application. This ensures that, no matter the path, it will use the same folder as the hash appears to be generated based on the key and not the path. I have found this to work really well and you may want to try it, @Fampov.

**Comment by Fampov** [comment]
> I ran into a similar problem where AppData\Local\[name] was getting filled with a lot of folders by AppCenter. As soon as the exe's path is changed, a new folder is created with a hash based on the path.
> 
> My workaround was to strong-name sign the application. This ensures that, no matter the path, it will use the same folder as the hash appears to be generated based on the key and not the path. I have found this to work really well and you may want to try it, @Fampov.

Thanks for the suggestion @EatonZ. I've been struggling with strong-name signing the application as we leverage several nuget packages and other dependencies that are not strong-name signed. Once I get it working to validate, I'll report back if that worked for me.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
