### ISSUE TITLE
Expose method to set Transmission Interval 

### ISSUE THREAD

**Issue by claudiosanchez** [microsoft/appcenter-sdk-dotnet#1414]
**Is your feature request related to a problem? Please describe.**
The .NET SDK does not expose the ability to configure the transmission interval when batching event logs. 
https://docs.microsoft.com/en-us/appcenter/sdk/analytics/ios#batching-event-logs

**Describe the solution you'd like**
Update the bindings to include the ability to set an interval value.
i.e.:
```
// Change transmission interval to 10 minutes.
MSAnalytics.setTransmissionInterval(600)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by olmisa** [comment]
@claudiosanchez Thanks for using App Center. Our team will discuss this feature request.
We'll keep this issue open for now.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
