### ISSUE TITLE
Client Error with AppCenter SDK

### ISSUE THREAD

**Issue by james1301** [microsoft/appcenter-sdk-dotnet#1420]
### **Description**

I am getting crash reports for the following callstack:

Microsoft.AppCenter.Utils.Synchronization.StatefulMutexException: Cannot lock mutex with expired state
Microsoft.AppCenter.Utils.Synchronization.StatefulMutex
<GetLockAsync>d__9.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
Microsoft.AppCenter.Channel.Channel
<TriggerIngestionAsync>d__47.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
Microsoft.AppCenter.Channel.Channel.<>c__DisplayClass51_0
<<CheckPendingLogs>b__1>d.MoveNext ()

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Unknown

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - e.g. WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - e.g. .N/A
2. Which SDK version are you using?
    - e.g. 3.2.1
4. Which OS version did you experience the issue on?
    - e.g. Windows 10.0.17763
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. VMware Virtual Platform
6. What third party libraries are you using? 
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here: Cannot get the logs as it is happening on a client.

**Comment by olmisa** [comment]
Hello @james1301 
Thanks for getting in touch! There is no chance at all to get the verbose logs? The logs could be very useful for the investigation. 
It would be very useful for us to get repro steps. Could you, please, provide this information?
Thanks

**Comment by james1301** [comment]
It is a struggle! It is just crashes reported into App Center. It may take some time to try to get that information from an end user and they may not be able to duplicate it.

There is also this error occurring:

Microsoft.AppCenter.Utils.Synchronization.StatefulMutexException: Cannot lock mutex with expired state
Microsoft.AppCenter.Utils.Synchronization.StatefulMutex
<GetLockAsync>d__9.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
Microsoft.AppCenter.Channel.Channel
<TriggerIngestionAsync>d__47.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
Microsoft.AppCenter.Channel.Channel.<>c__DisplayClass51_0
<<CheckPendingLogs>b__1>d.MoveNext ()

And here they are in App Center:

![image](https://user-images.githubusercontent.com/17780517/87684086-ba5f4f00-c779-11ea-95ae-eaa63dd52bd0.png)

**Comment by james1301** [comment]
Hi @olmisa any further help with this?

**Comment by AnastasiaKubova** [comment]
Hi, @james1301 ! I investigated your problem and found only one way when this error can happen. For me, it’s happening when I disable the App Center via `setEnabled(false)` call right after the `AppCenter.Start`.
Looks like in this case the App Center to this moment still not finalize “start” tasks and after calling the disable App Center it changed the state and as a consequence influenced unfinished tasks and throw an error, but it should not crash the app.
I label this issue as a bug.

Could you please clarify do you enable/disable the App Center in you app via method `setEnabled`? Also could you please clarify do you send crashes from background threads?

**Comment by james1301** [comment]
@AnastasiaKubova we have the following:

`AppCenter.Start(useTestAppCenter ? "36a74255-5854-4f93-a75b-f20629c40424" : "3314a086-5a9e-4b54-86bf-3d1d44fba147", typeof(Analytics), typeof(Crashes));

            if (!await AppCenter.IsEnabledAsync())
                await AppCenter.SetEnabledAsync(true);

            if (!string.IsNullOrWhiteSpace(previousSessionInfo))
                AppCenter.SetUserId(previousSessionInfo);

            if (!(previousAllowAnalytics || StaticProperties.AllowAnalytics))
                await Analytics.SetEnabledAsync(false);`

**Comment by james1301** [comment]
We have this set in our config, if this is what you mean?

`    <ThrowUnobservedTaskExceptions enabled="true" />`

**Comment by AnastasiaKubova** [comment]
Yes, thanks for the clarification.

**Comment by james1301** [comment]
@AnastasiaKubova so this would potentially duplicate like you have?

**Comment by AnastasiaKubova** [comment]
Hi @james1301 ! The fix has been released in [3.4.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/3.4.0). Please update `App Center SDK` to the latest version and let me know if you will have this error again.

**Comment by james1301** [comment]
Thanks @AnastasiaKubova will do!
