### ISSUE TITLE
System.Diagnostics.Tracing.EventSource integration

### ISSUE THREAD

**Issue by MagicAndre1981** [microsoft/appcenter-sdk-dotnet#1427]
**Is your feature request related to a problem? Please describe.**

I already have instrumented my code via [EventSource ](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netcore-3.1) and can capture it on Windows (UWP part of Xamarin.Forms app and classic desktop application) with WPR.exe, but I have no idea how to do it on Android. 

How can I configure appcenter to use already EventSource infrastructure to send those events? 

**Describe the solution you'd like**

Full integration to EventSource to send fully payload/ActivityIds with Provider/Events and not the primitive [custom Events that are currently supported](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/xamarin#custom-events).

**Comment by MagicAndre1981** [comment]
any update on this? Azure Application Insights [EventSource](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-trace-logs#use-eventsource-events).

**Comment by russelarms** [comment]
Hi there! Thank you for opening the feature request.
AppCenter team is [focused on reliability improvements until mid-2021](https://github.com/microsoft/appcenter#planning), so until then we have no ETA for this feature request.

**Comment by MagicAndre1981** [comment]
> AppCenter team is [focused on reliability improvements until mid-2021](https://github.com/microsoft/appcenter#planning), so until then we have no ETA for this feature request.

ok, thanks for the information

**Comment by DmitriyKirakosyan** [comment]
Hi @MagicAndre1981 ,

Do you think an API for providing a custom logger would resolve the issue for you?
Possibly related feature request: #779.

**Comment by MagicAndre1981** [comment]
> Do you think an API for providing a custom logger would resolve the issue for you? Possibly related feature request: #779.

that would require rewrite of all logging code. I'm not sure how large that change would be.

**Comment by DmitriyKirakosyan** [comment]
Hi @MagicAndre1981 , may I ask you to share an example of data which you would like to send using EventSource? How would such payload look like and how would you expect it to be observable on the App Center Portal?

Could you also clarify why listening EventSource events and sending them via Analytics.TrackEvent wouldn't be enough for you?

**Comment by MagicAndre1981** [comment]
> Could you also clarify why listening EventSource events and sending them via Analytics.TrackEvent wouldn't be enough for you?

As said, codebase is large and rewrite no real option. Looks like we need to test Application Insights and see how it works.

**Comment by MagicAndre1981** [comment]
> > Could you also clarify why listening EventSource events and sending them via Analytics.TrackEvent wouldn't be enough for you?
> 
> This is what my request is for your lib. Do this in background, translate the captured data and send them with Analytics.TrackEvent. It doesn't make sense that all users have to do it in their own.

thinking of this I would say this is the way to go for you. Add such a log capturing (and for other frameworks like NLog, log4net), translate them and send them.

It makes no sense to let users do this over and over again. @DmitriyKirakosyan

**Comment by wisdeom** [comment]
Hi @MagicAndre1981, thank you for reaching out to us. We had a team discussion on this feature request. Unfortunately, given the engineering team's roadmap this year and the size of engineering work on this feature, we're afraid to share this won't be prioritized in the near future. Application Insights SDK supports this feature, and we recommend checking AI for your advanced scenarios. Sorry for the inconvenience.
