### ISSUE TITLE
Distribute not working

### ISSUE THREAD

**Issue by TsplayerT** [microsoft/appcenter-sdk-dotnet#1441]
I would like to update my Xamarin.Forms application using the AppCenter Distribute tool, I can't find explanatory videos this year (2020). In addition to the fact that on the website https://status.appcenter.ms/ the distribution service found the status: **Degraded Performance**

![image](https://user-images.githubusercontent.com/6465230/93497658-0ac46b80-f8e7-11ea-92d8-64802ad91c22.png)

Can anybody help me?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Not sure that it related to App Center SDK. Could you please open the Intercom ticket about this issue (question symbol on the right top corner in the App Center portal).

Thanks
