### ISSUE TITLE
AppCenter 3.4.3 uses derecated FirebaseInstanceIdService

### ISSUE THREAD

**Issue by miko1258** [microsoft/appcenter-sdk-dotnet#1457]
### **Description**

Use of deprecated Firebase API which cause build error. Full build log attached.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create Xamarin Forms project
2. Install Microsoft.AppCenter packages (v. 3.4.3)
3. Install newest Xamarin.Firebase.Iid (v. 120.0.2) (Last version without issue: 71.1740.4)

### **Details**

Build error: 
Error processing method: 'System.Void Microsoft.AppCenter.Push.TokenService::OnTokenRefresh()' in assembly: 'Microsoft.AppCenter.Push.dll'  ---> Mono.Cecil.ResolutionException: Failed to resolve Firebase.Iid.FirebaseInstanceIdService 

Full log: [log.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/5415598/log.txt)

FirebaseInstanceIdService was deprecated for some time. From version 119.0.1 and newer it was deleted. AppCenter package still has reference to it and causes build error.

**Comment by MatkovIvan** [comment]
Hi @miko1258,

Thanks for getting in touch!
App Center Push will be removed from the SDK in next version. It will be [retired on December 31st, 2020](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/). 
As an alternative to App Center Push, we recommend you migrate to [Azure Notification Hubs](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-overview) by following the [Push Migration Guide](https://docs.microsoft.com/en-us/appcenter/migration/push/).

**Comment by miko1258** [comment]
Thanks for quick response and solution.
