### ISSUE TITLE
[BUG] Migration from AppCenter Push to Azure NotificationHub not clear at all, installation fails

### ISSUE THREAD

**Issue by andrekiba** [microsoft/appcenter-sdk-dotnet#1458]
This issue is linked to [https://github.com/Azure/azure-notificationhubs-xamarin/issues/21](url)

Could you please provide us a solution with a clear path for the migration without breaking everything??

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for highlighting this issue. We're in touch with Notification Hub team to escalate and resolve this.
However, since this problem is not directly related in App Center .NET SDK, I'm going to close this issue. Please stay tuned for updates in the original issue.

**Comment by andrekiba** [comment]
Next time you hastily decide to close an issue please try to be sure that the problem is really solved and that there is a clear migration path.

To date it is not clear whether the Push service will actually be discontinued on December 31st (a May post on a blog does not seem to me the official way...) and in any case, for Xamarin Forms at least, we don not have a clear path (that also supports update of previous apps) to migrate nor an official nuget package.

Do you think this is a good way to go on?

Another time after HockeyApp transition you break everything and without any attention to the customer...afterwards don't complain that people don't trust AppCenter...change idea every 6 months is not a good way to get it.

So can you confirm that the Push service will be discontinued in a few days, where is it officially written?

**Comment by MatkovIvan** [comment]
Hi there,

Thanks for your feedback and sorry for the delay and missing some pieces of info from our side.
The plan is the same as announced in [the blog post](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/) - retiring App Center Push on December 31st, 2020.
The Notification Hub team is working on resolving your migration issue, thank you for your collaboration on it!

**Comment by andrekiba** [comment]
Oh wow... sincerely I'm very disappointed for this. 
The issue is still not solved https://github.com/Azure/azure-notificationhubs-xamarin/issues/21 that practically means disservice starting from tomorrow...
With half of the world on vacation for Christmas...perfect timing guys...
And please try to answer at least some questions if you decide to reply...tell me...is there a clear path for the migration?
Da you think that a blog post without without a package (that works) it could be a clear path???
It's really unbelievable.
