### ISSUE TITLE
Use winsqlite3 on UWP

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/appcenter-sdk-dotnet#1460]
**Describe the solution you'd like**
It would be great if UWP package could use `SQLitePCLRaw.bundle_winsqlite3` rather than `SQLitePCLRaw.bundle_green`, to save some space in the final package.

**Comment by Sergio0694** [comment]
For reference, duplicate of https://github.com/microsoft/appcenter/issues/2039.
