### ISSUE TITLE
Update Android platform support packages on Xamarin to AndroidX

### ISSUE THREAD

**Issue by butler1233** [microsoft/appcenter-sdk-dotnet#1478]
**The problem.**
As [detailed in the Xamarin.Android docs](https://docs.microsoft.com/en-us/xamarin/android/platform/androidx), the old Android support libraries (and as a result, the Xamarin.Android.Support.* libs) are no longer maintained, and have been replaced with their counterpart AndroidX (Xamarin.AndroidX) counterparts. As it stands, when using the Appcenter packages in a Xamarin Forms/Android project, the package dependencies currently has a huge list of the older, unsupported versions. As of API Level 28 the older support libs are not updated. 

On a tangentally related note, Xamarin Forms 5 has a minimum target/build level of 29, meaning that in order to update to Xamarin Forms 5, projects must be migrated to the AndroidX system (although they should probably be updated anyway). 

**The solution**
The Appcenter packages should be updated to use the new AndroidX support libraries instead of the classic versions. I've noticed that the AppCenter packages were updated a couple of weeks back with the release of major version 4, which probably should have included the updated packages but 🤷 

**Additional context**
It doesn't seem like it's a dealbreaker at the moment, but it definitely results in a very messy project file and is definitely not ideal.

**Comment by olmisa** [comment]
@butler1233  Thanks for using App Center. Our team will discuss this feature request.
We'll keep this issue open for now.
Thanks

**Comment by AnastasiaKubova** [comment]
Currently the App Center SDK doesn't use Android Support dependency so I'm going to close this issue but feel free to reopen it if you will have additional questions.
