### ISSUE TITLE
Missing DLLs?

### ISSUE THREAD

**Issue by lvandal** [microsoft/appcenter-sdk-dotnet#1480]
### **Description**

Deployed app will not launch because of a crash in AppCenter:

> 

Application: MyApp.exe Framework Version: v4.0.30319 Description: The  process was terminated due to an unhandled exception. Exception Info:  System.IO.FileNotFoundException at  Microsoft.AppCenter.Ingestion.Models.Serialization.LogSerializer..cctor()  Exception Info: System.TypeInitializationException at  Microsoft.AppCenter.Ingestion.Models.Serialization.LogSerializer.AddLogType(System.String,  System.Type) at Microsoft.AppCenter.AppCenter..ctor() at  Microsoft.AppCenter.AppCenter.get_Instance() at  Microsoft.AppCenter.AppCenter.PlatformStart(System.String, System.Type[]) at  ScreensConnect.Program.Main()
--

I assume there are missing DLLs but couldn't find any info about which one to include. App runs fine from /bin/Release

### **Repro Steps**

1. Created a package via InnoSetup
2. Added command to include Microsoft.AppCenter.Analytics.dll, Microsoft.AppCenter.Crashes.dll and Microsoft.AppCenter.dll
3. Ran the installer and tried to launch the app
4. App crashes with error mentioned above

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    Standard Windows Application (C#)

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    N/A

3. Which SDK version are you using?
    4.0.0

4. Which OS version did you experience the issue on?
    Windows 10 with .NET 4.7.2

5. What device version did you see this error on?  Were you using an emulator or a physical device?
    MacBook Pro running Bootcamp

6. What third party libraries are you using? <!-- For .NET, you can find these in your .csproj, package.json, or package.config files
   
"Microsoft.AppCenter" version="4.0.0" targetFramework="net472"
"Microsoft.AppCenter.Analytics" version="4.0.0" targetFramework="net472"
"Microsoft.AppCenter.Crashes" version="4.0.0" targetFramework="net472"
"Newtonsoft.Json" version="12.0.2" targetFramework="net472"
"SQLitePCLRaw.bundle_green" version="2.0.2" targetFramework="net472"
"SQLitePCLRaw.core" version="2.0.2" targetFramework="net472"
"SQLitePCLRaw.lib.e_sqlite3" version="2.0.2" targetFramework="net472"
"SQLitePCLRaw.provider.dynamic_cdecl" version="2.0.2" targetFramework="net472"
"System.Buffers" version="4.4.0" targetFramework="net472"
"System.Memory" version="4.5.3" targetFramework="net472"
"System.Numerics.Vectors" version="4.4.0" targetFramework="net472"
"System.Runtime.CompilerServices.Unsafe" version="4.5.2" targetFramework="net472"

7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

N/A

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
I tried to reproduce your issue based on your steps, but for me all work well. Have you a chance to share a sample project with reproducing this issue?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
