### ISSUE TITLE
Provide Privacy Report for App Store

### ISSUE THREAD

**Issue by ivanicin** [microsoft/appcenter-sdk-dotnet#1482]
**Is your feature request related to a problem? Please describe.**
Currently the App Store requires developers to self report data usage in the privacy self-reporting. Among other things crash and analytics data is addressed there.

**Describe the solution you'd like**
You should provide data for Crash and Analytics packages. It is not possible for developers to know for sure how Microsoft is storing/using data on its servers.

**Describe alternatives you've considered**
For now I have posted this data by guessing, but that is not the solution.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us. 
Let me discuss it with the team.

**Comment by russelarms** [comment]
We're considering creating a helper document for the App Store submissions.
@ivanicin have you checked our documentation on what data is collected by the SDK?
https://docs.microsoft.com/en-us/appcenter/sdk/data-collected

> It is not possible for developers to know for sure how Microsoft is storing/using data on its servers.

It's probably covered by the GDPR part of our docs: https://docs.microsoft.com/en-us/appcenter/gdpr/

**Comment by Jamminroot** [comment]
Docs are updated now, so I'm closing the issue.
Have you anything to add or other concerns - feel free to reopen this issue or open a different one.
Thanks for pointing this out, and have a nice day!

**Comment by ivanicin** [comment]
@Jamminroot can you point me where I can find the new/changed docs? I couldn't find anything at first spot.

**Comment by MatkovIvan** [comment]
Apart of links that shared above, we added an additional question to [FAQ](https://docs.microsoft.com/en-us/appcenter/gdpr/faq#app-store-privacy-report) and links to these in Getting Started page to make it more visible.
