### ISSUE TITLE
AppCenter Push retirement confirmation

### ISSUE THREAD

**Issue by tharindup** [microsoft/appcenter-sdk-dotnet#1486]
8 months ago, AppCenter has announced that Push service will be retiring at the end of this year (https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/). On May, there was another article regarding appcenter migration guide for notification hubs, and that's it. Currently, we are working on the migration, and when we update apps which have been using appcenter, to notification hub, notifications are not receiving. But if we uninstall the old app reinstall the app which uses notification hub notifications work as expected. So now we are going through the issue to find a solution. 
Can you confirm that AppCenter Push surely will retire on December 31st, 2020? There's no news, any article or anything that would confirm the retirement.

**Comment by andrekiba** [comment]
No words...this is simple unbelievable [https://github.com/microsoft/appcenter-sdk-dotnet/issues/1458](url)

**Comment by MatkovIvan** [comment]
Hi there.

The customers of Push services received emails about the retirement date some time ago, but I just want to duplicate the information here: Based on developers' feedback, retirement has been postponed. You can find the information about it in [the blog post](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/):
> We want to hear from you along every step of your migration journey and want you to try out the new Notification Hubs SDKs in your apps. We will continue to operate the App Center Push service until February 15th, 2021.
