### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by Marv51** [microsoft/appcenter-sdk-dotnet#1490]
Please consider moving away from 'master' as a branch name. I suggest renaming the branch to 'main'.

With the [tools ](https://github.com/github/renaming)put in place by GitHub this should be fairly straight forward.

**Comment by AnastasiaKubova** [comment]
Thanks for getting in touch!
We're aware of this recommendation, but it's not in our short-term plan.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
