### ISSUE TITLE
Private NuGet Feed

### ISSUE THREAD

**Issue by Marv51** [microsoft/appcenter-sdk-dotnet#1491]
Is the private NuGet feed really needed?

I was trying to build this project and the first experience with continued prompts for sign-in with a microsoft account make it pretty annoying. 
Once I figured out what was going on and removed the private feed all seems to work fine.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Could you please clarify do you try to build our test apps or your own app?

**Comment by Marv51** [comment]
Trying (and succeeding) to build the SDK for my own app. 

Issue is that when you open any of the cloned solutions in VisualStudio, it repeatedly asks for a MS account and no matter if you provide it with one or cancel it will ask again a couple seconds later.

**Comment by AnastasiaKubova** [comment]
Hi there! The fix has been released in the [4.2.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.2.0) version of App Center SDK.
