### ISSUE TITLE
Add event when crash occurs

### ISSUE THREAD

**Issue by Marv51** [microsoft/appcenter-sdk-dotnet#1498]
We use an in-memory logger to log events in our app. There seems to be no way that AppCenter could attach that log without us creating all the exception handling in our own code to dump the log content to a file when an exception occurs and then add that file as an ErrorAttachment.

I understand that storing the attachments when an exception occurs, is a somewhat complicated feature.

However, it would be a very nice convenience to have an event on AppCenter.Crashes that occurs when a fatal exception occurs. To prepare any attachments needed to send the report on the next launch.

So I propose adding "CrashOccured" on AppCenter.Crashes to abstract all the exception handling logic and let AppCenter deal with that.

**Comment by russelarms** [comment]
Hi @Marv51, thanks for reaching out!
What environment do you use, is it mobile (Xamarin iOS/Android/Forms) or desktop (WPF/UWP)?

**Comment by Marv51** [comment]
Is use desktop WPF and UWP.

**Comment by russelarms** [comment]
We have discussed this issue internally and it seems that it is not possible to reliably trigger an event/callback after a crash has occurred if we are talking about an unmanaged environment.
For the managed environment it is possible to add your own custom listener, e.g.:
```
Application.ThreadException += new ThreadExceptionEventHandler(Application_ThreadException);
AppDomain.CurrentDomain.UnhandledException += new UnhandledExceptionEventHandler(CurrentDomain_UnhandledException);
```
