### ISSUE TITLE
Request for guide on Microsoft.AppCenter 4.2.0 integration with Uno 3.6 Platform Wasm Head

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/appcenter-sdk-dotnet#1513]
**Please provide a guide how to use the nuget package in a `net5` Uno Wasm Head**

The current Wasm head is a net5 project aims to use the AppCenter but the Mono Linker isn't quite happy with the reference on `System.Windows.Forms`.

**A clear and concise description of what you want to happen.**

Have you a got guide how to build the library with the different Uno Platform Heads ? Perhaps #ifdef and/or project level conditional compiling ?

 **Current Context**

![image](https://user-images.githubusercontent.com/43340959/114712833-d3108b80-9d30-11eb-85f9-2f20b497861b.png)

**Comment by russelarms** [comment]
Hi @sigmarsson, thanks for reaching out!
We don't officially support Uno Platform for WebAssembly at the moment, so I'll leave it as a feature request for future work.

System.Winforms is used to determine the app state and device information in the Windows environment.

https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/ApplicationLifecycleHelper.cs
https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DeviceInformationHelper.cs

Probably you can play around with these imports and their usages in the Uno project.

**Comment by sigmarsson** [comment]
Thank you @russelarms

Do you plan to extend this suit's scope to make it cross platform?  Currently it depends heavily on Windows so I believe it would be a huge set of work packages.

**Comment by Jamminroot** [comment]
Hey @sigmarsson, as App Center IS currently focused on improving reliability and performance, rather than implementing new feature, this feature was not yet prioritized, thus there's no ETA we can provide yet.

**Comment by sigmarsson** [comment]
Thank you @Jamminroot

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
