### ISSUE TITLE
Control of StartServiceLog

### ISSUE THREAD

**Issue by bewster** [microsoft/appcenter-sdk-dotnet#1514]
**Is your feature request related to a problem? Please describe.**
Always sending a `StartServiceLog` to AppCenter.  This seems to be a part of the core implementation, and there is no way for the user to control the opt-in\out-opt of this "analytics".

In some usage cases we only want to deploy the Crashes capability, and none of the analytics.  If a crash log is to be submitted `Crashes.ShouldAwaitUserConfirmation` is used.

Forcing the user to opt-in to the shadow analytics to get crash log support doesn't seem right.

**Describe the solution you'd like**
Ideally no data should be sent to AppCenter unless there is consent.

As a developer, the ability to disable the `StartServiceLog` logging action in code, before calling `AppCenter.Start(..)`

And\or clearer information in documentation that this feature submits data every time the app is started.
https://docs.microsoft.com/en-gb/appcenter/sdk/data-collected does give details on the content of this "Data sent through request body from SDK to Ingestion".

**Describe alternatives you've considered**
I have looked at using `AppCenter.SetEnabledAsync(false)`.  It does stop sending the `StartServiceLog`. but then doesn't send crash logs as they are deleted at start up.
I have considered not calling `AppCenter.Start(...)` until I have decided the user has opted-in.  But it makes the start-up logic more complicated and the users shouldn't have to accept sending any analytics to AppCenter just to enable the crash log support.

**Additional context**
This `StartServiceLog` may not be displayed in AppCenter. as analytics is not enabled, but the data is being submitted and may go somewhere.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
We already have a similar feature request [here](https://github.com/microsoft/appcenter/issues/2004).
Closing as duplicate, but feel free to reopen/comment if you have additional questions.

**Comment by bewster** [comment]
Thanks, I had tried looking for similar questions.  I see, the request is in the main [App Center](https://github.com/microsoft/appcenter) repo.
I will comment there.
