### ISSUE TITLE
WinUI 3 support

### ISSUE THREAD

**Issue by Marv51** [microsoft/appcenter-sdk-dotnet#1523]
### **Description**

Installing the SDK in WinUI 3 (Reunion 0.5.6) project works, but the SDK does not work at runtime. The exception I am getting is that the file `System.Windows.Forms` can't be found. It seems like the nuget package does not correctly install the UWP version of the appcenter SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create empty WinUI 3 project
2. Add Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes
3. Add `AppCenter.Start("[my-project-id]", typeof(Crashes), typeof(Analytics));` to App constructor

If you need more detailed error reports or repro steps, let me know. I guess this needs a dedicated nuget package that supports dotnet 5 + (mostly) UWP.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Please, fill out the `Details` part in the issue template. To do that click `New issue` > `Problem report`. In particular, we need to know the App Center version which you use and verbose logs with repo steps before and after the crash.
Also please clarify what kind of project you use, WinUI in UWP? And how you crash your app? I checked this behavior on my side on an empty app with a test crash and for me all work correclty.

**Comment by Marv51** [comment]
@AnastasiaKubova Thank you for checking this out. WinUI 3 is only support in one configuration: with dotnet 5 and in "desktop" mode. UWP is not supported.

I think the `Details` section does not provide any helpful additional information, but here you go:

### **Description**

Installing the SDK in WinUI 3 (Reunion 0.5.6) project works, but the SDK does not work at runtime. The exception I am getting is that the file System.Windows.Forms can't be found. It seems like the nuget package does not correctly install the UWP version of the appcenter SDK.

### **Repro Steps**
Please list the steps used to reproduce your issue.

* Create empty WinUI 3 project
* Add Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes
* Add AppCenter.Start("[my-project-id]", typeof(Crashes), typeof(Analytics)); to App constructor

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
 As mentioned above: WinUI 3 (Reunion 0.5.6)
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
 dotnet 5 (net5.0-windows10.0.19041.0)
2. Which SDK version are you using?
  latest (4.2.0).
4. Which OS version did you experience the issue on?
   Windows 10 20H2 19042
5. What device version did you see this error on?  Were you using an emulator or a physical device?
   Windows 10 20H2 19042 (is this a different question from 4?)
6. What third party libraries are you using? 
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.2.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.6" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.2.5" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
```
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
```
Exception thrown at 0x00007FF92B624B59 in App.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000035A6F79F70.
Exception thrown at 0x00007FF92B624B59 in App.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF92B624B59 in App.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000035A6F79F70.
Exception thrown at 0x00007FF92B624B59 in App.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FF92B624B59 in App.exe: Microsoft C++ exception: EEFileLoadException at memory location 0x00000035A6F79F70.
Exception thrown at 0x00007FF92B624B59 in App.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.AppCenter.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.AppCenter.dll

Exception thrown at 0x00007FF92B624B59 (KernelBase.dll) in App.exe: WinRT originate error - 0x80131534 : 'The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelper' threw an exception.'.
```

**Comment by AnastasiaKubova** [comment]
Thanks for the additional info!
Could you please clarify do you have a desktop app or a UWP app (I just a bit confused because in the description you mention the UWP app, but if I right understand you test on the desktop app, right?)?

Based on [this docs](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-uwp#create-a-winui-3-app-in-uwp-for-c) I see that WinUI already has a preview version with support UWP apps. I checked this behavior on WinUI in UWP app and for me all work well.

**Comment by AnastasiaKubova** [comment]
Currently, the App Center SDK doesn't support WinUI apps. I will mark this issue as a feature request.

**Comment by Marv51** [comment]
Hi @AnastasiaKubova Has WinUI 3 support been considered for AppCenter? Can you share any update on this feature request?

**Comment by russelarms** [comment]
@Marv51 we have notified our PMs but there are no updates on this feature yet.

**Comment by michael-hawker** [comment]
🦙 Link back to WinUI 3 issue tracking ecosystem support for these scenarios in general: https://github.com/microsoft/microsoft-ui-xaml/issues/5116

**Comment by Marv51** [comment]
Hi @russelarms and @AnastasiaKubova, any update on this?

**Comment by AnastasiaKubova** [comment]
Hi! Sorry for the long response. 
We are already working on it. I will notify you when we will have any updates.

**Comment by Marv51** [comment]
@AnastasiaKubova  I saw that some PRs have been merged to enable WinUI 3 support. Can you update us on what the current state of this support is?
Can we look forward to a release soon?

**Comment by DmitriyKirakosyan** [comment]
Hi @Marv51, we are planning to release SDK next month.

**Comment by AnastasiaKubova** [comment]
Hi there! The feature has been released in the [4.4.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0) version of App Center SDK.

**Comment by antonioberetini** [comment]
Are you guys for real??? The new Windows 11 is all about the new Windows SDK and WinUI3 being the future of Windows platform. How the tell do you guys expect us to continue supporting you and paying for your service if you don't support the latest from your parent company. This is ludacris to me and I am taking this straight to Twitter, and brining Panos Panay's attention. Whoever is prioritizing your roadmap should be fired!

**Comment by antonioberetini** [comment]
https://twitter.com/antonioberetini/status/1469301754705715205

**Comment by DmitriyKirakosyan** [comment]
Hi @antonioberetini , thank you for reaching out to us!
App Center DotNet SDK (starting from `4.4.0`) supports `WinUI in Desktop` and `WinUI in UWP` apps (how to create such apps please [see these docs](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/release-notes/winui3-project-reunion-0.5-preview#install-winui-3---project-reunion-05-preview) and [changelog](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0)).
I'm a bit confused about your concern. Could you please clarify your expectation from the App Center SDK regarding WinUI?

**Comment by wisdeom** [comment]
Hi @antonioberetini We announced the support for WinUI3 3 months go. Please let us know if the below link doesn't give you the information you're looking for. 
https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0

**Comment by Marv51** [comment]
@antonioberetini Personally, I do not like the tone of your comment.

**Comment by antonioberetini** [comment]
@Marv51  i don't really care how you feel about it. This is a paid service owned by Microsoft and for that reason it should support Microsoft technology properly. I wouldn't have the tone of voice of the customer support team had known the product to respond to several questions we asked correctly.

**Comment by antonioberetini** [comment]
@wisdeom thank you.
