### ISSUE TITLE
 Microsoft.AppCenter.Storage.StorageException: Failed to prepare SQL query, result=5 database is locked

### ISSUE THREAD

**Issue by tobias76** [microsoft/appcenter-sdk-dotnet#1530]
### **Description**

Hi, we are seeing the following issue with our clients on version 4.1.0 of the library and we are unable to replicate locally but we get relatively regular occurances, including in our previous reports (See: https://github.com/microsoft/appcenter-sdk-dotnet/issues/1423)

`  Microsoft.AppCenter.Storage.StorageException: Failed to prepare SQL query, result=5
	database is locked
    at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.AppCenter.Storage.Storage.<FlushQueueAsync>d__35.MoveNext()`

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - N/A
2. Which SDK version are you using?
    - 4.1.0
4. Which OS version did you experience the issue on?
    - WINDOWS 10.0.19041
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iMac19,2
6. What third party libraries are you using?
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by tobias76** [comment]
Please find the attached report: 
[report-2517855468079509999-73e67c74-9eb4-4788-98a1-435bc91d522b.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/6576616/report-2517855468079509999-73e67c74-9eb4-4788-98a1-435bc91d522b.zip)

**Comment by russelarms** [comment]
@tobias76 thanks for reaching out, we'll investigate this.

**Comment by AnastasiaKubova** [comment]
Hi @tobias76 ! Could you please clarify does this issue happens only with the 4.1.0 version of App Center, or it happens on the previous version too?

**Comment by tobias76** [comment]
Hi @AnastasiaKubova we initially got the issue in 3.2.1 but we have recieved more reports since upgrading to 4.1.0. Thanks!

**Comment by AnastasiaKubova** [comment]
Could you please confirm that the app doesn't start twice at the same time? (please see [this comment](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1423#issuecomment-664354117) for more context).

**Comment by tobias76** [comment]
Hi @AnastasiaKubova, As Tom mentioned in our previous issue we are unable to replicate it locally but the users do sometimes use remote desktop services if that could cause the issue?

**Comment by AnastasiaKubova** [comment]
Not sure that remote desktop services can cause this issue. We already had the same issue and it was fixed in the [3.4.1](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/3.4.1) version of App Center SDK. Currently I am trying to reproduce this issue, but for me all work well. If you have a chance to share verbose logs or repo steps it will be very helpful in investigating your issue.

**Comment by tobias76** [comment]
Hi @AnastasiaKubova, by verbose logs are they the ones I have previously attached or is it something different? :)

**Comment by tobias76** [comment]
Sorry @AnastasiaKubova I am unable to retrieve the logs as it is happening locally on a clients machine.

**Comment by AnastasiaKubova** [comment]
I found one way how to reproduce this issue. In my case, this issue happens when open two instances of apps which connected to common database of App Center and one of the app do endless requests to the database. 
We had a bug about endless requests to the database and it has already fixed in this [PR](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1529) and will be included in the next release.
Is it a possible case for you?

**Comment by tobias76** [comment]
Whilst unlikely, it isn't impossible as each of our clients do connect to their own DB. Could be worth us updating to the new version and keeping an eye on things.

**Comment by AnastasiaKubova** [comment]
I mean the database that is created and used by App Center only.

**Comment by tobias76** [comment]
Either way, we cannot rule out a client opening the application twice as this error does occur on start-up.

**Comment by AnastasiaKubova** [comment]
The fix has been released in the [4.3.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.3.0) version of App Center SDK so I’m closing this issue. But feel free to reopen this issue with additional info (verbose logs or/and repo steps) if this issue still persists.
