### ISSUE TITLE
Use of Servicepoint Manager breaks TLS1.3 (or any non TLS1.2) on netcore2.0 or NET48 etc

### ISSUE THREAD

**Issue by dpvreony** [microsoft/appcenter-sdk-dotnet#1531]
### **Description**

When using ServicePointManager with a platform that is using SecurityProtocolType.SystemDefault the EnableTls12() call in HttpNetworkAdapter breaks the ability to use TLS1.3 (or anything other than TLS1.2)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Have a project using Netstandard2.0 or NET47 onward
2. Have project use SystemDefault 
3. Have a site that requires TLS1.3
4. Enable AppCenter
5. Try to connect to the TLS1.3 site

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
   WPF
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
  NetcoreApp3.1 and NET48
2. Which SDK version are you using?
    4.2
4. Which OS version did you experience the issue on?
   Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
   N/A
6. What third party libraries are you using? 
  N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
  N/A

https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=net-5.0#System_Net_ServicePointManager_SecurityProtocol

> Starting with the .NET Framework 4.7, the default value of this property is SecurityProtocolType.SystemDefault. This allows .NET Framework networking APIs based on SslStream (such as FTP, HTTP, and SMTP) to inherit the default security protocols from the operating system or from any custom configurations performed by a system administrator. For information about which SSL/TLS protocols are enabled by default on each version of the Windows operating system, see Protocols in TLS/SSL (Schannel SSP).
> 
> For versions of the .NET Framework through the .NET Framework 4.6.2, no default value is listed for this property. The security landscape changes constantly, and default protocols and protection levels are changed over time in order to avoid known weaknesses. Defaults vary depending on individual machine configuration, installed software, and applied patches.
> 
> Your code should never implicitly depend on using a particular protection level, or on the assumption that a given security level is used by default. If your app depends on the use of a particular security level, you must explicitly specify that level and then check to be sure that it is actually in use on the established connection. Further, your code should be designed to be robust in the face of changes to which protocols are supported, as such changes are often made with little advance notice in order to mitigate emerging threats.

**Comment by russelarms** [comment]
Hi @dpvreony, thanks for reaching out!
Is it possible for you to share a repro demo/gist of the issue?

**Comment by dpvreony** [comment]
yep can sort something out

**Comment by dpvreony** [comment]
https://github.com/dpvreony/pocbug-appcenter-tls13/

**Comment by AnastasiaKubova** [comment]
Hi there! The fix has been released in the [4.4.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0) version of App Center SDK.
