### ISSUE TITLE
Please reopen https://github.com/microsoft/appcenter-sdk-dotnet/issues/1533

### ISSUE THREAD

**Issue by Tommigun1980** [microsoft/appcenter-sdk-dotnet#1535]
Hi.

I uploaded the requested information to issue https://github.com/microsoft/appcenter-sdk-dotnet/issues/1533, so could it please be reopened?

Feel free to close this report.

Thank you.

**Comment by AnastasiaKubova** [comment]
Close this issue, the main thread here #1533
