### ISSUE TITLE
Lot of pl crashes in iOS when used AppCenter SDK in Xamarin forms

### ISSUE THREAD

**Issue by pmahend1** [microsoft/appcenter-sdk-dotnet#1541]
### **Description**

I am seeing lot of crashes like
```log
0x00000001055af248 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 11301448 (unsigned int*, plcrash::MS::async::plcrash_dwarf_cfa_reg_rule_t*, unsigned long long*) + 10918044
```
We are using AppCenter SDK in our Xamarin forms project 

### **Repro Steps**

NA

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
   Xamarin.iOS

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
 .NET standard 2.0 shared project

3. Which SDK version are you using?
Microsoft.AppCenter.Crashes 4.2.0

4. Which OS version did you experience the issue on?
    - iOS 12 and higher
    - 
5. What device version did you see this error on?  Were you using an emulator or a physical device?
Any

6. What third party libraries are you using? 
NA

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Could you please clarify
- How you use App Center SDK?
- Share the full [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/ios#adjust-the-log-level)?
- This is just a log or it is crash your app?
- If this just log could you clarify how you crash your app?

**Comment by pmahend1** [comment]
> How you use App Center SDK?

AppCenter crashes SDK in shared project and in OnStart

```cshsarp
AppCenter.Start($"android={____};ios={______________}", typeof(Crashes));
```
> Share the full verbose logs?

I have shared it through support ticket I had raised already.

> This is just a log or it is crash your app?

Testflight crashes symbolicated to get more details.

> If this just log could you clarify how you crash your app?

This is not just log.
this is crash report log.
We dont force the app to crash.

**Comment by AnastasiaKubova** [comment]
Thanks for the details. Could you please share the full crash report and verbose logs here so that I could understand what exactly is going wrong?

**Comment by pmahend1** [comment]
@AnastasiaKubova I can not provide verbose logs because we dont know when those crash happen /
I am sorry, I can email crash files from apple store console logs to you since I cant put them on public website.

I raised issue here since it might be happening for other users , if they search they can see this.

Please provide your email id for me to share.

**Comment by AnastasiaKubova** [comment]
@pmahend1 You can touch with me via this email `v-ankubo@microsoft.com`.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by pmahend1** [comment]
@AnastasiaKubova Sorry have been busy this week.
I had already shared the verbose logs on the ticket I had raised with AppCenter.
Do you want me to email the same or the latest ones?

**Comment by pmahend1** [comment]
@AnastasiaKubova I have emailed the verbose logs and crash reports to the aforementioned email.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for sharing additional info. 
I checked your logs, but I didn't found any strange behavior from the SDK side and I didn't found any logs like this
`0x00000001055af248 plcrash::MS::async::dwarf_cfa_state_iterator<unsigned long long, long long>::next+ 11301448`

I see that you use `TestCrashException` API which crashes your app and in the next start all crash logs are sent correctly.

**Comment by pmahend1** [comment]
@AnastasiaKubova PL crashes are in the apple crash logs . I haven't been able to see those crashes in IDE or AppCenter.
So obviously we cant really see those in verbose logs unless we really know how those crashes happened (which we cant tell because of we don't have crash report for those in AppCenter). [This issue](https://github.com/microsoft/plcrashreporter/issues/28) gave me that clue.

So that's why I raised this issue to know whether such crashes occur does AppCenter not track them?

**Comment by AnastasiaKubova** [comment]
Could you please share the full crash log from the apple report so that I can more accurately tell if AC is causing your application to crash?

**Comment by AnastasiaKubova** [comment]
@pmahend1 just friendly ping. Do you have any updates here?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by pmahend1** [comment]
@AnastasiaKubova those are the logs I have had.i have shared full crash report from Apple. Can you be more specific on what you require?

**Comment by AnastasiaKubova** [comment]
Hi! I found your ticket in App Center. Let's keep this discussion in one thread.
