### ISSUE TITLE
AppCenter.Crashes transmit content of Exception.Data

### ISSUE THREAD

**Issue by norbertwg** [microsoft/appcenter-sdk-dotnet#1546]
**Is your feature request related to a problem? Please describe.**
In some cases I would like to have additional information transmitted together with the exception information. Example: if exception is thrown in a loop handling a collection of objects, information of the object just handled would help to find root cause of exception.

**Describe the solution you'd like**
I would like to store the additional information in Exception.Data. This is very flexible as it is a collection of key/value pairs. The content of Exception.Data could be added as text at end of stack trace. In this way I hope, it is not too much work. Exception.Data could contain all kinds of objects, but transferring only strings would be fine for me.
When not using AppCenter, I add a code like following to output exception information:

                string details="Exception data:";
                foreach (object key in ex.Data.Keys)
                {
                    details += "\r\n" + key.ToString() + "=" + ex.Data[key].ToString();
                }
I hope a similar approach could be implemented in AppCenter.

**Describe alternatives you've considered**
-/-

**Additional context**
-/-

**Comment by DmitriyKirakosyan** [comment]
Hi @norbertwg 

Thank you for reaching out to us!

I believe you can use attachment for that purpose.
You can attach some file or text message to the error report using this API:
```c#
Crashes.GetErrorAttachments = (ErrorReport report) =>
{
    // Your code goes here.
    return new ErrorAttachmentLog[]
    {
        ErrorAttachmentLog.AttachmentWithText("Hello world!", "hello.txt"),
        ErrorAttachmentLog.AttachmentWithBinary(Encoding.UTF8.GetBytes("Fake image"), "fake_image.jpeg", "image/jpeg")
    };
};
```

See more in the [docs](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#add-attachments-to-a-crash-report).

Please let me know if it doesn't help or you have additional questions.

**Comment by norbertwg** [comment]
Hi @DmitriyKirakosyan 

I tried attachment, but there I see some disadvantages. I have to write the additional information into a file on users's machine (which in general I would like to avoid in order to have as less impact as possible on foreign computers) at the time when exception is thrown. Crashes.GetErrorAttachments runs when the app is started again and I have no control, that the file attached at that point of time is the one I created for this exception. I admit, it is very unlikely, that there is a mismatch, but the approach I suggested does not have this risk.
If there is a way to ensure attaching the corect attachment - e.g. if there is a way to get the path where the information is stored for sending (both when exception is thrown and when Crashes.GetErrorAttachments runs), so that I can refer to that folder, I would feel more comfortable with that approach.

By the way: My understanding was, that Crashes.GetErrorAttachments is mainly implemented to allow attaching files, causing the exception (like an image as shown in the example). For this use case I see also the problem of correct assignment. When exception is thrown, the app knows that e.g. fake_image.jpeg causes a problem, but there is no simple way to have this information available when Crashes.GetErrorAttachments runs - or did I miss it?

**Comment by DmitriyKirakosyan** [comment]
The [`GetErrorAttachments` callback](https://github.com/microsoft/appcenter-sdk-dotnet/blob/13483bdd0f39b994a0fa5bdce9248f583f38159d/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Shared/CrashesDelegates.cs#L20) allows you to review the error report information before adding any attachment. This information is available in [ErrorReport](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Shared/ErrorReport.cs) object and it should be enough to identify your exception and attach any text that is specific to that exception. The attachment will be linked to its error report and displayed on the Portal for that exception.
All attachments are stored in database before sending, like any other logs and events sent using the AppCenter SDK.

SDK doesn't provide any API to access the error report at the moment when it happens. Catching exceptions vary from platform to platform and executing any code when the app is crashing is not safe in most cases.

If I understand your case correctly, then attachments is exactly what you need.
Please add more details why `GetErrorAttachments` doesn't work for you if I still get it wrong.

**Comment by norbertwg** [comment]
Thanks for the hint to check ErrorReport, but I still have concerns. Hopefully an example helps to get a common understanding:
Lets assume, there is a loop reading some jpeg-files and in this loop an System.ArgumentOutOfRangeException is thrown. Then the exception message does not contain the jpeg file name. When I catch the exception inside the loop, I know the jpeg file name and could write this information into an information file before I rethrow the exception and the program terminates.
When the program is restarted, GetErrorAttachments callback is triggered. I can see in ErrorReport, that it was a System.ArgumentOutOfRangeException, but I do not see, which file with additional information was created. I need to use a fix file name, which can be attached. This file name will be the same for all exceptions - at least this was my understanding.
But thanks to your hint, I now see a chance: ErrorReport contains an Id. Is it possible to get this Id when Exception is thrown? Then the files created at time of crash can be clearly assigned to the ErrorReport.

**Comment by DmitriyKirakosyan** [comment]
Thank you for the explanation.
I can see a number of options for you there:

1. Catch exception, add file name to the error message and rethrow it with a new error message. Then you can identify the file name from the exception message directly on the AppCenter portal.
2. Create a unique ID and save a file with a name of that ID. Add ID to your error message, then rethrow. In `GetErrorAttachments` you can determine the ID from the exception message and get the associated file with its contents.
3. Analyze the `ErrorReport.StackTrace` and add attachment based on it.

Let me know if it makes sense.

Regarding the `ErrorReport.Id`, unfortunately, you can't get that Id in advance (when the exception is thrown) because the ErrorReport object will be available for you to examine only on the next launch, right before sending the crash report.

**Comment by norbertwg** [comment]
Thanks for the hints. My approach is now to throw a new exception, where message includes the additional information and adding the original exception as inner exception. AppCenter portal shows information from inner exception, the additional information is visible in RAW data. In case I need more information, I will store it in a file, include the file name in exception message, which I then can get in GetErrorAttachments callback. 
This works fine, although I regard using Exception.Data to be a more elegant way.

**Comment by DmitriyKirakosyan** [comment]
Thank you for confirming!

Please share some experience later how this approach works for you.
We can then discuss further steps or create a feature request if the discussed approach wouldn't work for you well enough.

**Comment by norbertwg** [comment]
The approach to throw a new exception works fine, all my current needs are covered. I tried also longer message text. As line breaks are supported, it was good to read in AppCenter portal. The only drawback: the stack trace of the new exception is usually of no use. So the whole text of the exception is longer than needed. But in total, it is easy to use and covers my needs, so no feature request needed.
@DmitriyKirakosyan: once again thanks for your support

**Comment by DmitriyKirakosyan** [comment]
Glad to hear that, thank you for the update!
