### ISSUE TITLE
Custom OS logs via API are not displayed in the Appcenter UI

### ISSUE THREAD

**Issue by EmilAlipiev** [microsoft/appcenter-sdk-dotnet#1553]
**Is your feature request related to a problem? Please describe.**
I am trying to upload a crash or error report using the Api as described [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes)
For example, Tizen OS is currently not supported. So i created a Custom OS as advised. I send a Post request to upload an error, it works fine 200 success response is returned. But I cannot find this error in the UI. Obviously UI is not displaying it. because when i use a get request using Openapi url, errorgroup and details are returned. 

Question is here; is that a problem/bug or it was designed like that? if it is by design, what is the purpose of Custom OS? in what cases or what purpose can we use custom Os? I thought that this is the purpose if there is no existing nuget solution we should generate the data ourself using the Api and it should be displayed.

**Describe the solution you'd like**
It will be nice to get those crashes, trackings etc dispalyed in the UI as it shouldnt be so hard. Get urls looks similar, probably a small tweak is required.

**Describe alternatives you've considered**
Alternative building ourself a custom UI is too much work to be honest as there is already a working tool ca be reused.

**Comment by DmitriyKirakosyan** [comment]
Hi @EmilAlipiev 

Thank you for getting in touch with us!

Indeed, handled errors (type `handledError`) are not supported on Custom Os apps. The log will be successfully sent, but it won't be displayed on the App Center Portal, but normal crash reports (`managedError`) should be displayed under `Diagnostics` tab. If you crashes are not shown for you, it may be a bug. This is more a backend-related question, so please reach out to the support team and they will be able to help you: `appcenter.ms -> ? (question mark button, top-right corner) -> Contact support`.

Regarding the purpose of Custom OS and how it is intended to be used, the main idea is to allow you to distribute your custom app via App Center.

I'm closing this issue, but feel free to reopen if you have any additional questions.
