### ISSUE TITLE
An event message is still sent to AppCenter, even when Analytics are disabled

### ISSUE THREAD

**Issue by ezis94** [microsoft/appcenter-sdk-dotnet#1563]
### **Description**

We recently discovered that after running Analytics.SetEnabledAsync(false); after calling 
Analytics.TrackEvent(eventName, eventData), AppCenter still receives a message. We validated it by exporting our AppCenter events to an Azure storage. The received events do not containt the event name or evend ID but they still are sent to AppCenter with all the attached metadata or Custom properties if any.

### **Repro Steps**

1. set Analytics.SetEnabledAsync(false);
2. run any tracing event with Analytics.TrackEvent(eventName, eventData
3. Verify that no new event appeared in AppCenter with that name
4. Get the raw tracking data and verify that it exists, hovewer without actual event information

### **Details**

1. We are using the latest Xamarin AppCenter nugets 4.3.0

**Comment by DmitriyKirakosyan** [comment]
Hi @ezis94,

We send `StartServices` event on app launch even if Analytics is disabled.
Also, if you enable Crashes module, it can send events if app crashed during previous launch.
So, it is expected that AppCenter SDK can send some data to backend if Analytics is disabled.

We have an API for disabling such behavior and prevent sending anything over the network: `AppCenter.IsNetworkRequestsAllowed = false`, see [docs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#disallow-network-requests).

**Comment by ezis94** [comment]
Alright, thanks!

Will try that

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue but feel free to reopen if you have additional questions.
