### ISSUE TITLE
AppCenter verbose logs are not captured in Console.Out inside the code

### ISSUE THREAD

**Issue by JuliaSheveleva** [microsoft/appcenter-sdk-dotnet#1564]
Hello,
I have added 
AppCenter.LogLevel = LogLevel.Verbose;   before AppCenter.Start

I see all [AppCenterDistribute] logs in the Debug > Windows > Output window.
Then I try to catch Console.Out in the source code and process them.
But I see that program Console.Out does not contain AppCenter verbose logs.
Please tell me why I see logs in Debug > Windows > Output window.
and does not see them in Console.Out.

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    -  Xamarin.Forms on Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - NET standard
2. Which SDK version are you using?
    - 4.3.0
4. Which OS version did you experience the issue on?
    - Android

**Comment by AnastasiaKubova** [comment]
Hello! Thanks for getting in touch with us!
Did you try to enable the flag `Tools` -> `Options` -> `Debugging` -> `General` -> `Redirect all Output Window text to the Immediate Window`?

**Comment by JuliaSheveleva** [comment]
Yes, it did not help.
I see all AppCenter logs in Debug > Windows > Output window
but when I catch Console.Out there are no these logs.

**Comment by DmitriyKirakosyan** [comment]
Hi @JuliaSheveleva 
Could you please share more details about your use case?
How do you catch Console.Out exactly and how do you use the App Center SDK logs?

**Comment by JuliaSheveleva** [comment]
I have the row 
 AppCenter.LogLevel = LogLevel.Verbose;
before
AppCenter.Start()

When I launch my app I see logs in Debug > Windows > Output window in MS Visual Studio

Also my app catches the full Console.Out  to store all log information in local file as well.
We have special CombinedWriter class and we use our class to set Out for standard Console.

var logFileOutputStream = new FileStream(fullPath, FileMode.Append, FileAccess.Write);

var writter = new CombinedWriter(logFileOutputStream , Console.Out);
Console.SetOut(writter);

In our writer we override WriteLine method 
public override void WriteLine(string log)
and inside it we duplicate all logs into console and into the file.

And here  I see that Console.Out contains all logs except verbose logs from AppCenter
So the logs "[AppCenterDistribute] .."etc are absent

**Comment by AnastasiaKubova** [comment]
Hello, @JuliaSheveleva ! Thanks for the details! Let me summarize it. If I right understand you override the `WriteLine` method for collecting logs from the console which are printed via this method, right? If so I'm not sure that it is suitable for App Center Xamarin logs. The Xamarin Android and iOS App Center SDK is just wrappers of the native Android and iOS SDKs and [here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.Android/AppCenterLog.cs#L6) is [used native logger](https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter/src/main/java/com/microsoft/appcenter/utils/AppCenterLog.java#L23).

**Comment by JuliaSheveleva** [comment]
Thanks for response! Got it. The topic can be closed.
