### ISSUE TITLE
Running uitests fails for Android 11 APK

### ISSUE THREAD

**Issue by OlaOsttveit** [microsoft/appcenter-sdk-dotnet#1581]
We are trying to run an uitest for an android APK via the appcenter cli with this command:

/usr/local/bin/appcenter test run uitest --app '<appname>' --devices <devicelistid> --app-path <path to apk> --test-series 'master' --locale 'en_US' --test-parameter --build-dir <path to build> --uitest-tools-dir <path to test-cloud.exe>

It fails with this output:

----------
Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... done.
Uploading files... done.
Starting test run... failed.
Error: apk must be signed, install on device will fail otherwise - apksigner returned: DOES NOT VERIFY
ERROR: Target SDK version 30 requires a minimum of signature scheme v2; the APK is not signed with this or a later signature scheme

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and opening a support ticket (using the help menu in the upper right corner of the screen)

Environment: darwin
App Upload Id: <AppId>
Timestamp: <time>
Operation: RunUITestsCommand
Exit Code: 3
User Email: <email>
User Name: <username>
User Id: <userid>
----------

The given APK is correctly signed, which we have verified by running "apksigner verify -v --min-sdk-version 26 <AppName>.apk", which outputs:

Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): true
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1

The uitest run worked before but started failing when we started building the APK with target framework Android 11.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
This is not an SDK issue. Please open a [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.
