### ISSUE TITLE
New package dependency breaks .NET 5/6 class library support

### ISSUE THREAD

**Issue by leonluc-dev** [microsoft/appcenter-sdk-dotnet#1582]
### **Description**

Currently the AppCenter SDK does not support .NET 5/6 class libraries due to a dependency issue.

The Microsoft.AppCenter NuGet package dependencies are listed as follows:

 ```
   .NETCoreApp 3.0
        Microsoft.Windows.SDK.Contracts (>= 10.0.18362.2005)
        Newtonsoft.Json (>= 13.0.1)
        SQLitePCLRaw.bundle_green (>= 2.0.2)
        System.Configuration.ConfigurationManager (>= 4.6.0)
        System.Management (>= 4.6.0)
    .NETFramework 4.6.1
        Microsoft.Windows.SDK.Contracts (>= 10.0.18362.2005)
        Newtonsoft.Json (>= 13.0.1)
        SQLitePCLRaw.bundle_green (>= 2.0.2)
    MonoAndroid 5.0
        No dependencies.
    net5.0-windows10.0.17763
        Newtonsoft.Json (>= 13.0.1)
        SQLitePCLRaw.bundle_green (>= 2.0.2)
        System.Configuration.ConfigurationManager (>= 5.0.0)
        System.Management (>= 5.0.0)
    net5.0-windows7.0
        Newtonsoft.Json (>= 13.0.1)
        SQLitePCLRaw.bundle_green (>= 2.0.2)
        System.Configuration.ConfigurationManager (>= 5.0.0)
        System.Management (>= 5.0.0)
    UAP 10.0
        Microsoft.NETCore.UniversalWindowsPlatform (>= 6.2.8)
        Newtonsoft.Json (>= 13.0.1)
        SQLitePCLRaw.bundle_green (>= 2.0.2)
    Xamarin.iOS 1.0
        No dependencies.

```

Since a .NET 5 class library does not match any of these target frameworks it uses the next best option to determine package dependencies, which is .NETCoreApp 3.0.

The issue here is the **Microsoft.Windows.SDK.Contracts** dependency listed for the .NETCoreApp 3.0 target. This package is not supported on .NET 5 and will generate about 85 errors on trying to build project using it.
Since the Microsoft.AppCenter NuGet package resolves this unsupported package as a dependency when added to a .NET 5 class library the SDK cannot be used with such a project.

This might become a bigger issue later down the line, due to Xamarin being integrated with .NET 6 later this year, and Xamarin.Forms being superseded by .NET MAUI (which is based on .NET 6 rather than .NET Standard)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a .NET 5 based class library (a .NET 6 class library will also reproduce the issue)
2. Add any of the Microsoft.AppCenter.* packages to the project
3. Try to build the project
4. Multiple errors similar to `Windows.WinMD cannot be referenced. Referencing a Windows Metadata component directly when targeting .NET 5 or higher is not supported. For more information, see https://aka.ms/netsdk1130` should occur.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Primarily Xamarin.Android and Xamarin.iOS (issue also occurs when using .NET 6 Android/iOS)
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET 6 Class library (shared project)
2. Which SDK version are you using?
    - 4.4.0
4. Which OS version did you experience the issue on?
    - Compiler level

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! I will label this issue as a feature request.

**Comment by AnastasiaKubova** [comment]
Hello, @ryanholden8 ! With App Center version `4.3.0` for apps with target version `.net5` or higher was used App Center SDK for `.NETCoreApp 3.0` by default because we didn't have any `.net5` target versions before. In the `4.4.0` version of App Center SDK were added two new targets for `.net5.0-windows10.0.17763` and `.net5.0-windows7.0`. And looks like your app currently tries to use another target version of App Center SDK. Could you please clarify which exactly target version do you use in your app - `.net5` to `.net5-windows` or some other?

**Comment by leonluc-dev** [comment]
This does seem like a bug.
For .NET Core 3.0, .NET 5 and .NET 6 the target `.NETCoreApp 3.0` is used, which is expected behaviour.

The problem lies in the difference between dependencies in 4.3.0 vs 4.4.0.

**4.3.0**

```
.NETCoreApp 3.0
    Newtonsoft.Json (>= 12.0.2)
    SQLitePCLRaw.bundle_green (>= 2.0.2)
    System.Configuration.ConfigurationManager (>= 4.6.0)
    System.Management (>= 4.6.0)
```

**4.4.0**

```
.NETCoreApp 3.0
    Microsoft.Windows.SDK.Contracts (>= 10.0.18362.2005)
    Newtonsoft.Json (>= 13.0.1)
    SQLitePCLRaw.bundle_green (>= 2.0.2)
    System.Configuration.ConfigurationManager (>= 4.6.0)
    System.Management (>= 4.6.0)
```

The new Microsoft.Windows.SDK.Contracts dependency causes an issue because while it's supported for .NET Core 3.0 it causes errors on .NET 5 and 6.

**Comment by AnastasiaKubova** [comment]
Hmm, you are right. Thanks for the details. Looks like this is a bug.

**Comment by docelmo** [comment]
I read all of the comments.  I see there is a solution for what I am assuming is 4.5.0 which will come out eventually.  But is there something that can be done now?  I need to deploy an application and I really need this to work to gather the analytics and crash information.  I am going to have over 2000 users in my enterprise using this application.

**Comment by AnastasiaKubova** [comment]
Hi, @docelmo ! Thanks for getting in touch with us! Currently, you can use the previous version ([4.3.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.3.0)) of App Center SDK. 
We will notify you when the fix will be available.

**Comment by docelmo** [comment]
I did just that but if you know anyone from the MSAL identity folks let them know I had to jump through hurdles to make their library work with yours.  :)

**Comment by AnastasiaKubova** [comment]
Hi there! The [fix](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.5.0) has been released. Please update the SDK version to the latest and let me know if this issue still persists.

**Comment by ryanholden8** [comment]
Thank you!!
