### ISSUE TITLE
constantly shows error of java.net.SocketTimeoutException: timeout in Android

### ISSUE THREAD

**Issue by mgarcialo** [microsoft/appcenter-sdk-dotnet#1587]
### **Description**

In Version 3.4.3 constantly show error java.net.SocketTimeoutException: timeout in Android.
I have updated to version 4.4.0 and it keeps giving the same error .. everything has been tested on several real devices and enum them and the same thing always happens.

It only happens on Android on ios it doesn't happen.

### **Details**

[AppCenter] Try #2 failed and will be retried in 238987 ms
[AppCenter] java.net.SocketTimeoutException: timeout
[AppCenter] 	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:225)
[AppCenter] 	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
[AppCenter] 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
[AppCenter] 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:317)
[AppCenter] 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:311)
[AppCenter] 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:207)
[AppCenter] 	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:395)
[AppCenter] 	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:146)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:900)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:772)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
[AppCenter] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
[AppCenter] 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[AppCenter] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[AppCenter] 	at java.lang.Thread.run(Thread.java:923)
[A 11:51:09.314 W] Caused by: java.net.SocketException: Socket closed
[AppCenter] 	at java.net.SocketInputStream.read(SocketInputStream.java:209)
[AppCenter] 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
[AppCenter] 	at com.android.okhttp.okio.Okio$2.read(Okio.java:145)
[AppCenter] 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
[AppCenter] 	... 20 more

**Comment by AdamDiament** [comment]
FYI I am getting this in 4.5.0, I have added a support ticket as requested
