### ISSUE TITLE
Request: Allow usage of custom HttpClient or certificate pinning.

### ISSUE THREAD

**Issue by jantanis** [microsoft/appcenter-sdk-dotnet#1591]
Please allow the usage of using a custom HttpClient so we're able to implement certificate pinning on this. Or implement certificate pinning itself.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Please, fill out an issue template and describe your issue in more detail. To do that click `New issue` > `Problem report`.

**Comment by AnastasiaKubova** [comment]
Close as duplicate #1592
