### ISSUE TITLE
App Center support Console application

### ISSUE THREAD

**Issue by CenturionYun** [microsoft/appcenter-sdk-dotnet#1595]
### **Description**

I'm going to use App Center to track the crashes of my Console application, but I found that it did not work. Anybody know whether App Center support Console applications?
I think it's necessary to support Console application because one App may have a few independent sub-applications, these applications are not all WPF/UWP/Winform applications.

**Comment by aleksandr-dorofeev** [comment]
Hi @CenturionYun 
Thank you for getting in touch with us!
Currently, App Center SDK doesn't support console apps. We already have such feature request and you can track the progress [here](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1125).

I am closing this issue as a duplicate.
