### ISSUE TITLE
Dependency on SDK Contracts 18363 conflicts with requirements

### ISSUE THREAD

**Issue by wldevries** [microsoft/appcenter-sdk-dotnet#1596]
### **Description**

The AppCenter SDK 4.4 has a dependency on Microsoft.Windows.SDK.Contracts 18363 which seems to imply it only supports Windows 10 v1903 or higher. The documentation does not state any OS requirements. Is this SDK Contracts dependency not a hard requirements?

https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms

Our problem is that our products run on .NET Framework and target a wide range of operating systems including older versions of Windows 10 (those that are offline) and Windows 8.1 / Windows 8. Will upgrading to 4.4 and adding the SDK Contracts dependency cause problems?

### **Repro Steps**

-

### **Details**

-

**Comment by aleksandr-dorofeev** [comment]
Hi @wldevries 
Thanks for getting in touch with us!
This is a [known bug](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1582) that appeared in the 4.3.0 version of App Center SDK. We already prepared [a fix](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1585/files) and it will be released in the next release.
We will notify you when the fix will be released.

**Comment by wldevries** [comment]
Note that I am not talking about dependencies for NET Core. I'm talking about the dependency for NET Framework.

**Comment by aleksandr-dorofeev** [comment]
Oh, sorry, I misunderstood your question. Could you please clarify what App Center SDK version do you use?

**Comment by wldevries** [comment]
We are currently using App Center SDK 4.2 and this is blocking us from updating to 4.4.

**Comment by aleksandr-dorofeev** [comment]
Thanks for your details, I checked it and looks like this is a bug **in the version 4.4.0**. l will label this issue as a bug and notify you when the fix will be released.

**Comment by AnastasiaKubova** [comment]
Hi there! The [fix](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.5.0) has been released. Please update the SDK version to the latest and let me know if this issue still persists.
