### ISSUE TITLE
Add support for net6 maccatalyst project

### ISSUE THREAD

**Issue by marekdovjak** [microsoft/appcenter-sdk-dotnet#1600]
**Describe the solution you'd like**
I want to use appcenter analytics and crashes in net6 maccatalyst project

**Describe alternatives you've considered**
None, we are using appcenter in ios app, which has been modified to support maccatalyst also. So we need appcenter to work with net6 maccatalyst

**Additional context**
It is possible to build and link catalyst project with the current appcenter 4.4.0 version, but after calling `AppCenter.Start(...)`, exception is thrown `System.Exception: Could not create an native instance of the type 'Microsoft.AppCenter.iOS.Bindings.MSACWrapperSdk': the native class hasn't been loaded.`

**Comment by MikhailSuendukov** [comment]
Hello, the [AppCenter .NET SDK v5.0.5](
https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.5) with Mac Сatalyst support has been released. So I close this issue.
