### ISSUE TITLE
Incorrect intellisense documenation for Windows.Shared Analytics.TrackEvent

### ISSUE THREAD

**Issue by wldevries** [microsoft/appcenter-sdk-dotnet#1601]
### **Description**

The method `TrackEvent` in `Windows.Shared` mentions the following limitation for event properties:

>         ///     The properties parameter maximum item count = 5.

The documentation for App Center mentions that the number of property names is [limited to 20](https://docs.microsoft.com/nl-nl/appcenter/analytics/event-metrics).

### **Repro Steps**
-

### **Details**
As recent as commit 0bf8a4c

**Comment by AnastasiaKubova** [comment]
Hi there! The [fix](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.5.0) has been released. Please update the SDK version to the latest and let me know if this issue still persists.
