### ISSUE TITLE
GetDeviceInformation can throw various exceptions if the Windows WMI service is not running

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/appcenter-sdk-dotnet#1603]
### **Description**

Hi,
If the WMI service is not running various exceptions can be thrown from within [GetDeviceInformation](https://github.com/microsoft/appcenter-sdk-dotnet/blob/c214f54da17d609480f6d96efe3af5711f886ca5/SDK/AppCenter/Microsoft.AppCenter.Windows.Shared/Utils/AbstractDeviceInformationHelper.cs#L31) when the methods within it attempt to access device information via WMI. From this we have seen COMException being thrown as well as ManagementException

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Open Services.msc and pause the Windows Management Instrumentation Service
2. Call the following code
```csharp
var errorLog = ErrorLogHelper.CreateErrorLog(new InvalidOperationException());
ErrorLogHelper.SaveErrorLogFiles(new InvalidOperationException(), errorLog);
 ```

This will reliably duplicate an uncaught COMException. It looks like some attempt has been made to stop a similar scenario throwing errors in the past as all of the methods within [DeviceInformationHelper.cs](https://github.com/microsoft/appcenter-sdk-dotnet/blob/c214f54da17d609480f6d96efe3af5711f886ca5/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DeviceInformationHelper.cs#L55) that get device info have catches for UnauthorizedAccessException however this isn't enough if the WMI service isn't running. Like previously said we've also seen ManagementException thrown from this scenario, here is the callstack for that however we've not been able to reliably duplicate this one:
```
System.Management  ManagementException.ThrowWithExtendedInfo (ManagementStatus errorCode)
System.Management.ManagementObjectCollection  ManagementObjectEnumerator.MoveNext ()
Microsoft.AppCenter.Utils  DeviceInformationHelper.GetOsVersion ()
Microsoft.AppCenter.Utils  AbstractDeviceInformationHelper.GetDeviceInformation ()
```

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
WPF
2. Which SDK version are you using?
  4.3.0
4. Which OS version did you experience the issue on?
Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
Physical Device
6. What third party libraries are you using? 
Can duplicate with no third party libraries in a sample project
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
8. N/A

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
I was able to reproduce this issue. I will label it as a bug.

**Comment by tomaustin700** [comment]
Thanks @AnastasiaKubova, I notice your PR is only catching COMException but we have also seen [ManagementException ](https://docs.microsoft.com/en-us/dotnet/api/system.management.managementexception?view=netframework-4.8) thrown also however we've not been able to duplicate that one. Do you think it's worth catching that one also? I'm not 100% what causes ManagementException to be thrown.

**Comment by AnastasiaKubova** [comment]
Thanks for the details, I will check it.

**Comment by AnastasiaKubova** [comment]
Hi there! The [fix](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.5.0) has been released. Please update the SDK version to the latest and let me know if this issue still persists.
