### ISSUE TITLE
AppCenter.GetServices is not linker safe

### ISSUE THREAD

**Issue by Cheesebaron** [microsoft/appcenter-sdk-dotnet#1606]
### **Description**

I am building a net6.0-android project and want to publish it with `PublishTrimmed` set to true.

This throws a warning because GetServices is using reflection.

https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.Android/AppCenter.cs#L191

```
ILLink : Trim analysis error IL2075: Microsoft.AppCenter.AppCenter.GetServices(IEnumerable<Type>): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'. The return value of method 'System.Collections.Generic.IEnumerator<T>.Current.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Enable `PublishTrimmed` in your build props
  - You may need to also add `SuppressTrimAnalysisWarnings` = `False` and `TrimmerSingleWarn` = `False` too to see the warnings
2. Build in release mode

### **Details**

AppCenter NuGet 4.4.0
net6.0-android TFM

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
I will check it and return to you with the results.

**Comment by AnastasiaKubova** [comment]
Hello! I was able to reproduce this issue. I will label it as a bug.

**Comment by thisisthekap** [comment]
@AnastasiaKubova Any ETA for a fix?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue. However, contributions are still welcome.

**Comment by Cheesebaron** [comment]
Thanks for replying 3 years later :)
