### ISSUE TITLE
Occasional deadlock in AppCenter.Start()

### ISSUE THREAD

**Issue by gameshowcrew** [microsoft/appcenter-sdk-dotnet#1612]
### **Description**

We got some reports of our released app hanging at startup. Made a dump and found it was a deadlock in AppCenter.Start(). A screenshot of the stacks/threads is attached

### **Repro Steps**

Winforms app calls AppCenter.Start("...code...", typeof(Analytics), typeof(Crashes));
Cannot reproduce this on dev machines. This is one of the first calls the app makes. 

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
Windows Forms

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
   .NET Framework 4.8

2. Which SDK version are you using?
    4.4.0

4. Which OS version did you experience the issue on?
    Windows 10

5. What device version did you see this error on?  Were you using an emulator or a physical device?
Happened both on a Virtual Box Windows 10 instance as well as on a physical device

6. What third party libraries are you using? 
Many

7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
Didn't find a way to capture these logs in a release situation. Seems no possibilty to get them written to a file.
 
<img width="962" alt="appcenter-deadlock" src="https://user-images.githubusercontent.com/57524306/147217027-da2d526f-3164-45bb-bf35-d63353b4caee.PNG">

**Comment by AnastasiaKubova** [comment]
This issue should be already fixed in[ this PR](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1605 ).
These changes will be available in the next release. I will notify you when the fix will be released.

**Comment by gameshowcrew** [comment]
Thanks, is there any workaround until then? 

Maybe using separate calls like:

AppCenter.Configure("{Your App Secret}");
if (AppCenter.Configured)
{
    AppCenter.Start(typeof(Analytics)); 
    AppCenter.Start(typeof(Crashes)); 
}

**Comment by AnastasiaKubova** [comment]
This bug is only in the [4.4.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0) version of App Center SDK. You can use the [previous](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.3.0) version of App Center SDK instead.

**Comment by TranstecJasonD** [comment]
I was able to workaround the issue by changing the parameter order:
AppCenter.Start("...code...", typeof(Crashes), typeof(Analytics));

**Comment by AnastasiaKubova** [comment]
Hi there! The [fix](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.5.0) has been released. Please update the SDK version to the latest and let me know if this issue still persists.
