### ISSUE TITLE
[macOS] Large bundle size

### ISSUE THREAD

**Issue by tipa** [microsoft/appcenter-sdk-dotnet#1621]
### **Description**
Thanks for adding MacOS support with the recent update 4.5.0 - I am hyped!
Have been using AppCenter for all my Windows, iOS and Android apps and had to fall back to using Sentry for my MacOS app.
So naturally I was immediately adding AppCenter (`AppCenter.Crashes` & `AppCenter.Analytics`) to my Xamarin.MacOS app and built the app.
I noticed, that when building an Archive for publishing to the App Store, the "xarchive" increased significantly in size.

When building for x86_64 only, the bundle size increased from 71.4 MB to 77,6 MB (**6.2 MB increase**).
When building for x86_64 & [ARM64](https://docs.microsoft.com/en-us/xamarin/mac/release-notes/7/7.13#preview-of-apple-silicon-support), the bundle size increased from 130.8 MB to147.8 MB (**17 MB increase**)

I was not able to test increase of app installation size yet because of [this problem](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1620).

Is there any way to prevent this large app size increase?
This actually makes me consider to stick with Sentry, which has a much smaller footprint in size (~1 MB)...

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add `AppCenter.Crashes` & `AppCenter.Analytics` to MacOS Xamarin app
2. Build archive for publishing

**Comment by aleksandr-dorofeev** [comment]
Hi @tipa! Thanks for reporting this issue.
We will check if we can decrease the framework size.

**Comment by AnastasiaKubova** [comment]
Hello! Apologize for the long response!
The App Center SDK for Xamarin platforms uses bindings that are used native App Center SDK platforms. In the App Center Apple SDK, we use `PLCrashReporter` which allows the catching of different native crashes. 
The Sentry uses only `C#` implementation and doesn't use bindings, so the size of this framework is less.

**Comment by tipa** [comment]
Thanks for the response!
From my experience, bindings aren't necessarily large in size, maybe `PLCrashReporter` itself is just (too) large?
6 MB just for crash reporting + analytics is more than I would be willing to use in my app, so it seems like I will be staying with Sentry for now.
Maybe/hopefully you will consider writing a C# implementation for Xamarin.Mac in the future.

**Comment by AnatolyPristensky** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
