### ISSUE TITLE
Configure AppCenter LocalAppData &  Database file Path 

### ISSUE THREAD

**Issue by IndexOutOfLimit** [microsoft/appcenter-sdk-dotnet#1624]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

As we are moving to .MAUI , it would be great if we can customize AppCenter local log file and database file path.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
We already have a similar feature request. Let's track the progress of this feature [here](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1409).
