### ISSUE TITLE
Reset install ID

### ISSUE THREAD

**Issue by wldevries** [microsoft/appcenter-sdk-dotnet#1625]
**Is your feature request related to a problem? Please describe.**
We use App Center in various WPF products. These products are shipped on hardware assembled in house with Windows cloned from images. Due to this process we have series of installations that have the same Install ID, which causes problems.

We would like to have a way of resetting the install ID or to remove the current install ID. It seems it is registered in a file AppCenter.config under AppData, but I'm not sure how to consistently remove it in our application. It's probably not wise either to do it while App Center is initialized.

**Describe the solution you'd like**
I would like to have a method on the `AppCenter` type to reset the Install ID.

I would also like to have documentation on the various files used by the appcenter dotnet sdk. There's the aforementioned AppCenter.config, but I'd also like to know where the sqlite database is stored.

**Describe alternatives you've considered**
Create a manual process for our technicians to remove a certain file during assembly.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
The `installId` value is initialized after the first application start. So if you already ran your application I can suggest you clean all application data to avoid any unexpected issues with analytics data from the App Center SDK.

Database path you can find in the App Center [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/uwp#analytics-data-doesnt-show-up-in-the-portal
) and path to the App Center configuration file you can find [here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DefaultApplicationSettings.cs#L137).

I also can suggest you try to use this hack and try to set installId manually before App Center start.
```
const string kInstallId = "AppCenterInstallId";
var settings = new DefaultApplicationSettings();
settings.SetValue(kInstallId, Guid.NewGuid());
```

**Comment by wldevries** [comment]
Thanks for the help!

Do you foresee any problems when I reset the install id while App Center is running? I don't expect it to pick up the new id, but I would expect it to pick it up when the app is restarted.

I noticed a whole slew of AppCenter.config files in local appdata, each with a different `Url_aphanumericalcode` postfix. Is a new install ID generated each time the version of the application is changed or is it migrated?

**Comment by AnastasiaKubova** [comment]
If you set `installId` before App Center starts it shouldn't affect App Center SDK behavior. But I want to mention that hack above is not a public API and before using I recommend you make sure that it doesn't harm your analytics data. And you also have to make sure that this value will be generated only once after the first application start and not after every application launch.

If after updating your application the App Center SDK can't find the old configuration file then will be generated a new one with a new `installId` value. Please see [here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DefaultApplicationSettings.cs#L152).

**Comment by wldevries** [comment]
It seems you have removed the public interfaces that allowed the workaround. What would you suggest I do when updating to 5.0?

**Comment by DmitriyKirakosyan** [comment]
Hi @wldevries , there were no changes related to `DefaultApplicationSettings`.

Note, that there is no API of resetting/changing `installId`. The option suggested above was an unsupported workaround which may or may not work depending on your project specifics.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Comment by wldevries** [comment]
Since app center is retiring next year..
