### ISSUE TITLE
[Windows] The initialization of App Center underlying services fails, due to a deadlock.

### ISSUE THREAD

**Issue by dahlita** [microsoft/appcenter-sdk-dotnet#1627]
### **Description**

This issue seems to manifest when starting more than one services, e.g `Analytics` then `Crashes`.
The 1st service starts successfully, but the 2nd one fails due to a deadlock.
When the deadlock happens while `AppCenter.Start(params Type[] services)` was invoked on the UI thread, the entire app UI freezes.
Moving the initialization on a background thread, helps keep the UI responsive, but that thread then gets frozen, and blocks all other threads executing events from the 1st service that started successfully.

### **Repro Steps**

Simply invoke
  `AppCenter.Start("<app secret here>", typeof(Analytics), typeof(Crashes))`;

Or start them one after the other with:
```
 AppCenter.Configure("<app secret here>") 
 AppCenter.Start(typeof(Analytics));
 AppCenter.Start(typeof(Crashes));
```

### **Platform details**

1. What is your app platform?
    - Windows desktop
2. Which SDK version are you using?
    - 4.5.0
3. Which OS version did you experience the issue on?
    - Windows 10.0.19043
4. What third party libraries are you using?
    - I can reproduce the issue in a small sample app that just references
     `Microsoft.AppCenter.Analytics` and `Microsoft.AppCenter.Crashes`

### **More details on the deadlock with the call stack**

While instantiating the service `Channel`, the thread acquires a lock via `_mutex.GetLock()`, then queues a BG task to get the logs count
(the result of this task will later be used in another continuation task to update the initial value of `_pendingLogCount` and release the above lock).
Then the thread continues to check for pending logs, via `Channel.CheckPendingLogsInternal(State state)`, attempts to acquire the lock again and waits for the previous one to be released before continuing its execution.
Meanwhile, the 1st service that started successfully is executing its event logs  on another BG thread, but is blocked because it needs the global lock `AppCenterLock` held by the thread instantiating the 2nd service.
At the same time, the Task scheduler is waiting for the ongoing tasks to complete, and related threads to be released, so that it can execute other scheduled ones.
And one of the tasks that is still queued - still in the `Scheduled` status - is the task responsible for populating `_pendingLogCount` and release the lock above, acquired in the `Channel.ctor(...)`.

Below are screenshots showing the process dump analysis of blocked threads / tasks as well as scheduled ones, when the issue occurs:
 
![image](https://user-images.githubusercontent.com/5661026/154565539-a601bb84-17ae-4ac7-839f-4cf912043eff.png)

![image](https://user-images.githubusercontent.com/5661026/154565705-2cb7d808-b1be-4680-906b-98f4ff6112a3.png)

![image](https://user-images.githubusercontent.com/5661026/154565771-d8edcd5e-a04d-468b-8c51-82eb4242c6ff.png)

**Comment by AnatolyPristensky** [comment]
Hello @dahlita!
Thank you for getting in touch with us and thank you for your contribution!
We will test it and update this thread once get results.

**Comment by jmithy** [comment]
Hello @AnatolyPristensk . We are also experiencing this issue on our production app and would like to know an estimated fix date for it please.

**Comment by asierpn** [comment]
Same issue here, please fix it.

**Comment by DmitriyKirakosyan** [comment]
Hi guys, thank you for bumping this thread. We understand the importance of this issue and actively working to make the provided PR merged before the upcoming release which is planned this month.
Thank you for your patience.

**Comment by jmithy** [comment]
Hello @DmitriyKirakosyan . Sorry but do we know an estimated release date for the fix yet?

**Comment by AnatolyPristensky** [comment]
Hello @jmithy,
The estimated release date is within 2-3 weeks. 
We will update this thread once it happens.

**Comment by jmithy** [comment]
Thanks for the update @AnatolyPristensky

**Comment by jmithy** [comment]
@AnatolyPristensky Sorry to chase again but do you have any updates yet?

**Comment by DmitriyKirakosyan** [comment]
Hi @jmithy , we are working on the new release right now. The main PR is already merged here https://github.com/microsoft/appcenter-sdk-dotnet/pull/1638.
We are making sure that the SDK of version 4.5.1 is functioning as expected and will release it to the public nugets in a few days.

Thank you for your patience!

**Comment by jmithy** [comment]
@DmitriyKirakosyan Thanks for your time and efforts on this issue. Do we have a nuget release date yet?

**Comment by DmitriyKirakosyan** [comment]
Hi @jmithy , as I replied in https://github.com/microsoft/appcenter-sdk-dotnet/issues/1620/#issuecomment-1104723303, it should be available later this week.
Thank you for your patience!

**Comment by DmitriyKirakosyan** [comment]
Hi folks, DotNet SDK 4.5.1 has been successfully released!
Closing the issue.
