### ISSUE TITLE
App downloaded from In-app-update won't detect another update

### ISSUE THREAD

**Issue by rborosak** [microsoft/appcenter-sdk-dotnet#1634]
### **Description**

Hi,
I'm using Microsoft.AppCenter.Distribute v4.5.0 in MAUI (Preview 14) app.  
I can install the app from AppCenter and get the first update. Next updates are not detected. 

It's the same problem as in Android SDK described [here](https://github.com/microsoft/appcenter-sdk-android/issues/1594) 
and similar to [this](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1633#issuecomment-1077495186) but my device does not have MIUI optimizations enabled.

**Comment by DmitriyKirakosyan** [comment]
Hi @rborosak , thank you for creating a separate bug. This fix has been already released for Android native SDK. Xamarin will be released soon. I'll keep this thread updated.

**Comment by rborosak** [comment]
Thank you.
When can we expect this to be fixed?

**Comment by aleksandr-dorofeev** [comment]
The release will be ready in the next few days.

**Comment by rborosak** [comment]
@aleksandr-dorofeev Any news about this? This is an impediment for us and our clients are getting a bit nervous.
Thank you

**Comment by DmitriyKirakosyan** [comment]
Hi @rborosak , as I replied in https://github.com/microsoft/appcenter-sdk-dotnet/issues/1620, it should be available later this week.
Thank you for your patience!

**Comment by DmitriyKirakosyan** [comment]
Hi @rborosak , DotNet SDK 4.5.1 has been successfully released!
Closing the issue.

**Comment by rborosak** [comment]
Thank you, but the problem is not fixed

**Comment by rborosak** [comment]
Thank you.
