### ISSUE TITLE
distribution popup for in-app updates does not adapt to Thread.CurrentThread.CurrentUICulture

### ISSUE THREAD

**Issue by gsgou** [microsoft/appcenter-sdk-dotnet#1636]
**Describe the solution you'd like**
Instead of adapting the popup texts according
CultureInfo.InstalledUICulture
the proper culture should derive from API
Thread.CurrentThread.CurrentUICulture
which can be set in the app to the preferred UI language.

**Comment by gsgou** [comment]
Hi @DmitriyKirakosyan, i mean the "Microsoft.AppCenter.Distribute" nuget package.

**Comment by DmitriyKirakosyan** [comment]
@gsgou , what platform do you build your app for?

**Comment by DmitriyKirakosyan** [comment]
Hi @gsgou , just a friendly ping.

**Comment by gsgou** [comment]
The issue was reproducable with latest nuget in Android and iOS

**Comment by DmitriyKirakosyan** [comment]
@gsgou Xamarin Android and iOS SDKs are wrappers on native iOS and Android SDKs. Localization is resolved on the native SDKs side.
You can use custom dialogs as a workaround.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue, but feel free to ask any additional questions.
