### ISSUE TITLE
Add support for net6-ios

### ISSUE THREAD

**Issue by GalaxiaGuy** [microsoft/appcenter-sdk-dotnet#1637]
**Is your feature request related to a problem? Please describe.**
Because `net6-ios` cannot use `xamarin.ios` packages, Maui apps cannot use AppCenter.
https://github.com/xamarin/xamarin-macios/issues/13087

**Describe the solution you'd like**
Add support for `net6-ios`.

**Describe alternatives you've considered**
Not using Maui, or not using AppCenter.

**Additional context**
Other Xamarin based net6 TFMs should probably be supported too, but the breaking change on iOS is the most pressing.

**Comment by DmitriyKirakosyan** [comment]
Hi @GalaxiaGuy , thank you for reaching out to us!

Have you tried to build MAUI Xamarin.ios with AppCenter dependency?
I think you did and it didn't work, right? Can you share the error details?

I tried MAUI Android and WinUI apps and it worked. Haven't tried iOS though. See my post https://github.com/microsoft/appcenter/issues/2268#issuecomment-908327870.

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while so I'm closing this issue. Please let me know if it still persists for you.
