### ISSUE TITLE
[UWP] Is it required to call SQLitePCL.raw.sqlite3_win32_set_directory?

### ISSUE THREAD

**Issue by tipa** [microsoft/appcenter-sdk-dotnet#1641]
Platform: UWP, SDK version: 4.5.0

I regularly have users contacting me because my app is hanging and crashing on startup. Reinstalling the app always solved the problem. In AppCenter, I was not able to find any related exception reports.

Recently, I found [this thread](https://github.com/praeclarum/sqlite-net/issues/958) where the developer of SQLitePCL.raw made me and many others aware of the possible requirement of calling a specific function on the UWP Platform: https://github.com/ericsink/SQLitePCL.raw/wiki/UWP-Init

The App Center SDK is using SQLitePCL.raw but does not call `sqlite3_win32_set_directory()`.
- Could it be possible that AppCenter is crashing my app in `AppCenter.Start()` due to not calling this method?
- Is there a specific reason why the SDK is not calling this method?

I asked a user of my app that experienced that crash to delete the `Microsoft.AppCenter.Storage` file and apparently that was enough for the app to start and not crash again, which makes it appear that AppCenter is causing the crashes.

**Comment by AnatolyPristensky** [comment]
Hello @tipa and thank you for getting in touch with us!
I've marked your request as a bug and filed an item on our internal dashboard. 
We will update this thread once the issue will be fixed.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue. However, contributions are still welcome.
