### ISSUE TITLE
AppVersion fallback to unknown when targeting wpf app to net6.0-windows10.0.18362.0

### ISSUE THREAD

**Issue by Lightczx** [microsoft/appcenter-sdk-dotnet#1644]
### **Description**

```json
"appVersion": "Unknown"
```
the `appVersion` field is not being set, and fallback to "Unkonwn" as I found in

https://github.com/microsoft/appcenter-sdk-dotnet/blob/6b24d283c18ff9b70f033735c7fcf20c3ae98020/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DeviceInformationHelper.cs#L180-L192

the productVersion won't be set as I target my project to net6.0-windows10.0.18362.0

I would have expected it to be consistent with the AssemblyVersion
Is there any workaround to this issue?

### **Repro Steps**

1.Create a wpf app and target it like `net6.0-windows10.0.18362.0`
2.reference the appcenter sdk v 4.5.1

**Comment by DmitriyKirakosyan** [comment]
Hi @Lightczx , thank you for getting in touch with us!
I will mark it is a bug.
As a workaround you can send the version in event properties, however the version related charts on the App Center portal will not work.

**Comment by Lightczx** [comment]
> WINDOWS10_0_17763_0

they use `WINDOWS10_0_17763_0 ` to determine whether it's a WinUI 3 app
However my wpf app has a `net6.0-windows10.0.18362.0` TFM also satisfy the  `WINDOWS10_0_17763_0 ` condition
and then the code just return the value below which is always null for wpf using WinRT

**Comment by DmitriyKirakosyan** [comment]
The fix has been released in v4.5.3. Closing.
