### ISSUE TITLE
Mark Microsoft.AppCenter.Push/Auth/Data as deprecated on nuget.org

### ISSUE THREAD

**Issue by juliushardt** [microsoft/appcenter-sdk-dotnet#1646]
Since [App Center Push, Auth and Data are no longer supported](https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/), please consider marking Microsoft.AppCenter.Push, Microsoft.AppCenter.Auth and Microsoft.AppCenter.Data as [deprecated on nuget.org](https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages), so the .NET tooling reminds developers to remove the package references from their projects.

**Comment by DmitriyKirakosyan** [comment]
Hi @juliushardt ,

Thank you for reaching out to us!
We will mark the mentioned NuGets as deprecated.

**Comment by DmitriyKirakosyan** [comment]
`Microsoft.AppCenter.Push`, `Microsoft.AppCenter.Auth` and `Microsoft.AppCenter.Data` packages are marked as deprecated now.
