### ISSUE TITLE
Document supported Windows platforms

### ISSUE THREAD

**Issue by Marv51** [microsoft/appcenter-sdk-dotnet#1648]
### **Description**
Can you please document what Windows platforms you support? And what kind of exceptions / crashes you support on those platforms?

Are these the supported platforms?
* WinForms & WPF
* WinForms & WPF (packaged as MSIX package)
* UWP
* WinUI 3 (packaged as MSIX)
* WinUI 3 (unpackaged)

For packaged WinUI 3 I am getting reports of a small minority of the occuring crashes, most of those are completely unactionable.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WinUI 3.0 1.0.3 (packaged)
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - N/A
2. Which SDK version are you using?
    - 4.5.1
4. Which OS version did you experience the issue on?
    - Windows 10 1909+
5. What device version did you see this error on?  Were you using an emulator or a physical device?
     - Windows Computer
6. What third party libraries are you using? 
    - WinAppSDK
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
    - N/A

**Comment by optimodzhu** [comment]
AppCenter cannot send data when target .net framework 4.6.1

**Comment by AnatolyPristensky** [comment]
Hello, @Marv51 and thank you for getting in touch with us. 
You can find needful information on the [AppCenter Documentation page](https://docs.microsoft.com/en-us/appcenter/sdk/#windows-uwp). 

@optimodzhu, please fill the separate issue for your request with a more detailed information.

**Comment by optimodzhu** [comment]
> Hello, @Marv51 and thank you for getting in touch with us. You can find needful information on the [AppCenter Documentation page](https://docs.microsoft.com/en-us/appcenter/sdk/#windows-uwp).
> 
> @optimodzhu, please fill the separate issue for your request with a more detailed information.

OK, I will do.

**Comment by Marv51** [comment]
Thank you for the link @AnatolyPristensky. However, you don't mention WinUI 3/Windows App SDK on that page at all. Does that mean these scenarios are unsupported?

**Comment by AnatolyPristensky** [comment]
@Marv51, these scenarios are supported, but this is a known issue: on WinUI apps, the amount of sessions may be lower than on UWP apps due to specifics of its lifecycle. We will also update the documentation.
