### ISSUE TITLE
WPF DeviceInformationHelper doesn't handle unsupported platforms properly

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/appcenter-sdk-dotnet#1652]
### **Description**

WPF `DeviceInformationHelper` is using `System.Management` NuGet package to load info about the device, but this seems to fail on some cases because `System.Management` hooks some built-in .NET Framework native DLL (`wminet_utils.dll`) that might be outdated in some cases.
If the library fails to load, `System.Management` throws a `PlatformNotSupportedException` that's not actually being catched by `DeviceInformationHelper` causing the library to never initialize and to rethrow the exception over and over again.

### **Repro Steps**

The easier way to reproduce this is to test the library on some ancient Windows 10 installation, we tried on version `10240` to be specific.
Invoking `AppCenter.Start("xxx", typeof(Crashes));` seems to be enough to trigger the exception.

### **Details**

We're on WPF, .NET 6, and SDK version 4.5.1.
Windows 10, version 10240 (the issue seem to exist on Windows 7 and 8 as well).

**Comment by DmitriyKirakosyan** [comment]
Hi @FrayxRulez , thank you for reporting this issue, it looks like a bug indeed. Could you clarify this statement:

> If the library fails to load, System.Management throws a PlatformNotSupportedException that's not actually being catched by DeviceInformationHelper causing the library to never initialize and to rethrow the exception over and over again.

Does it mean that AppCenter SDK actually crashes your app, or it just fails to initialize and as a result it is not working on the older windows builds?

**Comment by DmitriyKirakosyan** [comment]
The fix has been released in v4.5.3. Closing.
