### ISSUE TITLE
.Net 6 MAUI support

### ISSUE THREAD

**Issue by Anand-Moghe** [microsoft/appcenter-sdk-dotnet#1660]
**Is your feature request related to a problem? Please describe.**
.Net 6 MAUI is out and many developers wondering how to migrate from Xamarin to .Net 6 MAUI.
But it's not clear if VS App Center will support the .Net 6 MAUI release.
There is no documentation available which describes how to use VS App Center with Mobile App developed using .Net 6 MAUI.

**Describe the solution you'd like**
Please provide documentation regarding which .Net releases are currently supported by VS App Center SDK and updated product roadmap for future/latest .Net releases.

**Comment by MatkovIvan** [comment]
Hi @Anand-Moghe,
Thanks for getting in touch!
We're working on supporting this, but no exact ETA for now (it should be a few months or so).

Closing it as duplicate of #1647
