### ISSUE TITLE
AppCenter Build - When can we expect support for Maui?

### ISSUE THREAD

**Issue by EdwardMcFlurry** [microsoft/appcenter-sdk-dotnet#1689]
![7D3FF05E-F115-4FF8-B452-C7A49327088D](https://user-images.githubusercontent.com/46613832/194997660-995370d6-1a09-4b34-82c3-857b392a342c.jpeg)

**Comment by aleksandr-dorofeev** [comment]
Hey @EdwardMcFlurry 
This doesn't seem to be an SDK issue, I'm closing this issue in this repository.
