### ISSUE TITLE
Distribute pop-up is hard to read in dark mode on Android

### ISSUE THREAD

**Issue by rogerbriggen** [microsoft/appcenter-sdk-dotnet#1691]
### **Description**

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use Distribute module on Android
2. Set your theme to dark mode
3. Add an update to appcenter so the pop-up appears
4. The "Buttons" have a hard to read font color see also attached image
![PurpleTextBlackBackground_2](https://user-images.githubusercontent.com/46163208/195589095-822622a6-6cea-4219-8769-f195ab4784fe.jpg)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - MAUI on Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - 
2. Which SDK version are you using?
    - 5.0.0 Preview 1
6. Which OS version did you experience the issue on?
    - Android 11
7. What device version did you see this error on?  Were you using an emulator or a physical device?
    - OnePlus 8T
8. What third party libraries are you using? 
    - 
9. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by DmitriyKirakosyan** [comment]
Hi @rogerbriggen , this dialog is built on the Android native SDK side and uses default configuration. See [Distribute.java#L1419-L1463](https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L1419-L1463).

You can use your [custom dialog implementation](https://learn.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#2-customize-the-update-dialog).

**Comment by rogerbriggen** [comment]
Ok, thanks
