### ISSUE TITLE
.NET MAUI MacCatalyst app is trying to load ''System.Windows.Forms'

### ISSUE THREAD

**Issue by dhindrik** [microsoft/appcenter-sdk-dotnet#1702]
### **Description**
Exception when running AppCenter.Start, it is trying to load ''System.Windows.Forms'. There are a similar issue for Windows, https://github.com/microsoft/appcenter-sdk-dotnet/issues/1693

### **Repro Steps**

1. Install the NuGet packages for crashes and analytics
2. Add the AppCenter.Start in App.xaml.cs
3. Run the App on MacCatalyst

### **Details**

```
System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

For full logs see the attached files.

[Visual Studio Enterprise 2022 for Mac Pr.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/10081473/Visual.Studio.Enterprise.2022.for.Mac.Pr.txt)
[log (1).txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/10081485/log.1.txt)

**Comment by DmitriyKirakosyan** [comment]
@dhindrik , thank you for creating a separate item! We will inform you once it is fixed.

**Comment by mhrastegari** [comment]
Facing the same here.

**Comment by zahrabayatt** [comment]
Any updates on this?

**Comment by IlyaBausovAkvelon** [comment]
@zahrabayatt we are still working on this.

**Comment by kyurkchyan** [comment]
Same issue :( It's very frustrating

**Comment by tpitman** [comment]
Another one with the same issue. Any fix coming or is this even being worked on?

**Comment by busitech** [comment]
We are facing the same problem here.

**Comment by DmitriyKirakosyan** [comment]
Hello everyone,
Due to shifting priorities, we've had to postpone the work on MAUI MacCatalyst. However, please note that this task remains a high priority on our board. We are committed to addressing the issue at the earliest opportunity. Thanks for your patience and understanding.

**Comment by AndreasReitberger** [comment]
Still facing this issue. Any ETA for a fix? It's been awhile.

**Comment by dfernandezramos** [comment]
Hi there. I am reproducing the issue on a macBook PRO M1 with macOS Sonoma. My application is net7 using Avalonia 11

**Comment by tpitman** [comment]
I am now seeing this error when running it on Android. We need a fix for this or a work around.

**Comment by alimuhammadiiii** [comment]
Any news on this?

**Comment by Mogikan** [comment]
Two years ago they stopped planning development for the next year and seemed to stop even maintaining this product.

**Comment by busitech** [comment]
Wow, that's terrible news.  Did Microsoft announce this officially?

**Comment by NPadrutt** [comment]
@busitech what I would consider at least an indicator for what @Mogikan  is saying is that the roadmap was never updated since 2022: https://github.com/Microsoft/appcenter/wiki/Roadmap

**Comment by thewizrd** [comment]
Not sure if this is being worked on, but I've been using the below change for a few months and its been working fine.
Binaries for maccatalyst taken from the latest xcframework package.

[Binaries](https://github.com/microsoft/appcenter-sdk-apple/releases)
[Changes](https://github.com/thewizrd/appcenter-sdk-dotnet-1/commits/feature/maccatalyst-support/)

**Comment by Mogikan** [comment]
@busitech since silverlight death they stopped announcing bad news. Now they open source products and abandon repos. For example, one drive sdk was abandoned 7 years ago. Sounds crazy, but nobody cares. https://github.com/OneDrive/onedrive-sdk-csharp

**Comment by mhrastegari** [comment]
That's awesome! If it's working, why not doing a PR? @thewizrd

**Comment by DmitriyKirakosyan** [comment]
Hi everyone, I prepared the maccatalyst support [PR](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1771), based on https://github.com/microsoft/appcenter-sdk-dotnet/issues/1702/#issuecomment-1907191123 (thanks a lot to @thewizrd).
We will merge the PR once CI is fixed.

**Comment by mhrastegari** [comment]
@DmitriyKirakosyan And when does CI getting fixed? :")

**Comment by vladPanasiuk** [comment]
@DmitriyKirakosyan Any news about this fix?

**Comment by AndreasReitberger** [comment]
As far as I can remember, AppCenter is shutdown by end of March 2025. So I guess there will be no efforts to fix this issue at all...

**Comment by MikhailSuendukov** [comment]
Hello, the [AppCenter .NET SDK v5.0.4](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.4) has been released, including a fix for this issue. Therefore, I am closing this issue.

**Comment by mhrastegari** [comment]
Did you even test it? 🙂 @MikhailSuendukov

**Comment by tylerwilson** [comment]
Same, just tried 5.0.4 and same issue:

`System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)`

**Comment by domneedham** [comment]
Also facing this issue still with 5.0.4 for Maccatalyst.

**Comment by sovdchains** [comment]
5.0.5 seems to have fixed the issue

**Comment by MikhailSuendukov** [comment]
Hello, the [AppCenter .NET SDK v5.0.5](
https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.5) with fix for this issue has been released.

**Comment by Mogikan** [comment]
Forget about appcenter. As I mentioned earlier  

> Wow, that's terrible news. Did Microsoft announce this officially?

Yes
