### ISSUE TITLE
Microsoft.AppCenter.Crashes - Strong name validation failed. (HRESULT 0x8013141A)

### ISSUE THREAD

**Issue by maximmax42** [microsoft/appcenter-sdk-dotnet#1706]
### **Description**

After I updated AppCenter from 4.5.3 to 5.0.0 I can't launch my WinForms project because of this exception:
`System.IO.FileLoadException: "Could not load file or assembly "Microsoft.AppCenter.Crashes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8a600e2fee7ba272" or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)"`
This exception occurs both in debug and release configurations. Downgrading back to 4.5.3 works just fine.

`C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe -Vr path\to\Microsoft.AppCenter.dll` and `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe -Vr path\to\Microsoft.AppCenter.Crashes.dll` don't help.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Update from 4.5.3 to 5.0.0
2. Build and launch
3. The exception is thrown

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - WinForms on .NET Framework 4.8
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - Not relevant
2. Which SDK version are you using?
    - 5.0.0
5. Which OS version did you experience the issue on?
    - Windows 10
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - PC
7. What third party libraries are you using? 
    - Not sure this is relevant
8. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
    - The project never launches

**Comment by bfmyr4** [comment]
Experiencing the same thing on WPF with .NET Framework 4.7.2.

**Comment by DmitriyKirakosyan** [comment]
Hi @maximmax42 and @bfmyr4 , Thank you for reporting! We filed a bug. I will update on progress.

**Comment by JanZeman** [comment]
Same here, .NET Framework 4.8, Windows 11. Thank you for filing the bug.

**Comment by DmitriyKirakosyan** [comment]
@maximmax42 , @bfmyr4 , @JanZeman , May I ask someone of you to verify that strong name validation doesn't fail on version 5.0.0-preview.1 ?

**Comment by JanZeman** [comment]
Hi @DmitriyKirakosyan, I can confirm it got fixed with 5.0.0-preview.1. The strong name validation problem is not reproducible on the preview build anymore on my solution.

**Comment by maximmax42** [comment]
Yep, 5.0.0-preview.1 works just fine.

**Comment by DmitriyKirakosyan** [comment]
It is fixed now in 5.0.1.
