### ISSUE TITLE
Library e_sqlite3 not found

### ISSUE THREAD

**Issue by massimotomasi** [microsoft/appcenter-sdk-dotnet#1722]
Hello,
I followed the Getting started guide for configuring AppCenter but it doesn't work. You can get the demo code here https://github.com/massimotomasi/AppCenterWpfDemo

Please describe the issue you are facing using the SDK.

### **Repro Steps**

I create a brand new Wpf (.Net Framework) project and added the Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes packages as requested in the getting started guide. You can find the solution here: https://github.com/massimotomasi/AppCenterWpfDemo

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)? WPF (.Net Framework)
2. Which SDK version are you using? Last available on NuGet (5.0.1)
4. Which OS version did you experience the issue on? Windows 11
5. What device version did you see this error on?  Were you using an emulator or a physical device? PC
6. What third party libraries are you using? None
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

'AppCenterWpfDemo.exe' (CLR v4.0.30319: DefaultDomain): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: DefaultDomain): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\AppCenterWpfDemo.exe' completato. Simboli caricati.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Remote Debugger\x86\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
Esegui istruzione: esecuzione di istruzione/routine del codice non utente 'AppCenterWpfDemo.App..ctor'
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
Esegui istruzione: esecuzione di istruzione/routine del codice non utente 'AppCenterWpfDemo.App.InitializeComponent'
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_it_b77a5c561934e089\mscorlib.resources.dll' completato. Modulo compilato senza simboli.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\Microsoft.AppCenter.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\Microsoft.AppCenter.Analytics.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\Microsoft.AppCenter.Crashes.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\Newtonsoft.Json.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
2022-12-30 14:44:53.445 [AppCenter] DEBUG: Use lifecycle for desktop applications.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
2022-12-30 14:44:53.475 [AppCenter] DEBUG: No named identifier found in appSecret; using as-is
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\SQLitePCLRaw.batteries_v2.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\SQLitePCLRaw.core.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\SQLitePCLRaw.provider.dynamic_cdecl.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\System.Memory.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices.RuntimeInformation\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.RuntimeInformation.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
2022-12-30 14:44:53.547 [AppCenter] ERROR: Failed to initialize sqlite3 provider.
System.Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\runtimes\win-x86\native\e_sqlite3.dll
    2) C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\e_sqlite3.dll
win TryLoad: C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\runtimes\win-x86\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): Impossibile trovare il modulo specificato
   in SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): Impossibile trovare il modulo specificato
   in SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

   in SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   in SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   in SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   in SQLitePCL.Batteries_V2.Init()
   in Microsoft.AppCenter.Storage.StorageAdapter..cctor()
2022-12-30 14:44:53.549 [AppCenter] DEBUG: Creating database at: C:\Users\tomasim\AppData\Local\Microsoft\AppCenter\4725cded-e9da-4be7-8336-bdad1d04a424\Logs.db
2022-12-30 14:44:53.551 [AppCenter] DEBUG: AddChannel(core)
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Users\tomasim\source\repos\AppCenterWpfDemo\AppCenterWpfDemo\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll' completato. Modulo compilato senza simboli.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
2022-12-30 14:44:53.569 [AppCenter] INFO: App Center SDK configured successfully.
2022-12-30 14:44:53.573 [AppCenter] DEBUG: AddChannel(analytics)
2022-12-30 14:44:53.575 [AppCenter] ERROR: An error occurred while initializing storage
System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   in SQLitePCL.raw.get_Provider()
   in SQLitePCL.raw.sqlite3_open(utf8z filename, sqlite3& db)
   in SQLitePCL.raw.sqlite3_open(String filename, sqlite3& db)
   in Microsoft.AppCenter.Storage.StorageAdapter.Initialize(String databasePath)
   in Microsoft.AppCenter.Storage.Storage.InitializeDatabase()
2022-12-30 14:44:53.577 [AppCenterAnalytics] DEBUG: SessionTracker.Resume
2022-12-30 14:44:53.578 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   in Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   in Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2022-12-30 14:44:53.580 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2022-12-30 14:44:53.581 [AppCenter] DEBUG: CheckPendingLogsInternal(core) pending log count: 0
2022-12-30 14:44:53.582 [AppCenter] DEBUG: Set max storage size.
2022-12-30 14:44:53.584 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The storage operation failed ---> Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   in Microsoft.AppCenter.Storage.StorageAdapter.SetMaxStorageSize(Int64 sizeInBytes)
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass23_0.<SetMaxStorageSizeAsync>b__0()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass23_0.<SetMaxStorageSizeAsync>b__0()
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2022-12-30 14:44:53.586 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   in Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   in Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2022-12-30 14:44:53.587 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2022-12-30 14:44:53.588 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2022-12-30 14:44:53.588 [AppCenter] DEBUG: CheckPendingLogsInternal(analytics) pending log count: 0
2022-12-30 14:44:53.593 [AppCenter] INFO: 'Analytics' service started.
2022-12-30 14:44:53.595 [AppCenter] DEBUG: AddChannel(crashes)
2022-12-30 14:44:53.598 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   in Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   in Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
2022-12-30 14:44:53.604 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2022-12-30 14:44:53.632 [AppCenter] INFO: 'Crashes' service started.
2022-12-30 14:44:53.660 [AppCenter] DEBUG: CheckPendingLogsInternal(crashes) pending log count: 0
2022-12-30 14:44:53.661 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x86\Microsoft.VisualStudio.DesignTools.WpfTap.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Deployment.resources\v4.0_4.0.0.0_it_b03f5f7f11d50a3a\System.Deployment.resources.dll' completato. Modulo compilato senza simboli.
2022-12-30 14:44:54.199 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2022-12-30 14:44:54.225 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
2022-12-30 14:44:54.299 [AppCenter] ERROR: Could not get max storage size.
2022-12-30 14:44:54.310 [AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: Failed to store a log to the database.
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass31_0.<AddTaskToQueue>b__0()
   in System.Threading.Tasks.Task.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Microsoft.AppCenter.Channel.Channel.<PersistLogAsync>d__41.MoveNext()
2022-12-30 14:44:54.315 [AppCenter] ERROR: Could not get max storage size.
2022-12-30 14:44:54.323 [AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: Failed to store a log to the database.
   in Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass31_0.<AddTaskToQueue>b__0()
   in System.Threading.Tasks.Task.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Microsoft.AppCenter.Channel.Channel.<PersistLogAsync>d__41.MoveNext()
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization.resources\v4.0_4.0.0.0_it_b77a5c561934e089\System.Runtime.Serialization.resources.dll' completato. Modulo compilato senza simboli.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
'AppCenterWpfDemo.exe' (CLR v4.0.30319: AppCenterWpfDemo.exe): caricamento di 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll' completato. Caricamento dei simboli ignorato. Il modulo è ottimizzato e l'opzione del debugger 'Solo codice utente' è abilitata.
Il thread 0xb378 è terminato con il codice 0 (0x0).
Il thread 0xbb1c è terminato con il codice 0 (0x0).
Il thread 0xc2cc è terminato con il codice 0 (0x0).
Il thread 0xd558 è terminato con il codice 0 (0x0).
Il thread 0xa9c0 è terminato con il codice 0 (0x0).
Il thread 0x5748 è terminato con il codice 0 (0x0).
Il programma '[55148] AppCenterWpfDemo.exe' è terminato con il codice 4294967295 (0xffffffff).

**Comment by MikhailSuendukov** [comment]
Hi @massimotomasi and thank you for contacting us, we are now investigating this issue.

**Comment by MikhailSuendukov** [comment]
@massimotomasi We managed to reproduce this bug, so I created a bug ticket on our dashboard, and we will monitor its status here.

**Comment by smasherprog** [comment]
Blocked by the same problem
