### ISSUE TITLE
Windows App SDK app freezes when calling Crashes/Analytics.SetEnabledAsync 

### ISSUE THREAD

**Issue by paulober** [microsoft/appcenter-sdk-dotnet#1723]
### **Description**

I have a Windows App SDK app with net6.0 on Windows 11. When i cal `SetEnabledAsync(true)` for Crashes or Analytics the hole app freezes (for about 20seconds) and i get infinit System.IO.Exception in Visual Studio 2022 debuger. But `SetEnabledAsync(false)` it freezes the hole app (for about 20seconds) and i get errors like this:
`Exception raised: "System.IO.IOException" in System.Private.CoreLib.dll`
Some times when caling with (false) it does not crash but then it crashes when trying to activate it again.

(Edit: I think the problem now only occurs when caling it on Crashes but on Analytics get normal logs like `[AppCenter] INFO: Analytics service has already been disabled.`)

(Second edit: I also get the invinit System.IO exceptions when calling "AppCenter.Configure" when my app is build in RELEASE mode but sometimes it strangely works)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a Windows App SDK 1.2+ app (with Template Studio if you want)
2. If you want you can now call SetEnabledAsync(false) for all modules to stop them from running <- some times this also freezes the hole app when called on the Crashes module 
3. Call AppCenter.Configure at the beginning
4. Call AppCenter.Start with both modules
5. Try to run `await Crashes.SetEnabledAsync(true)`. <- This now freezes the hole app

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Packaged WinUI 3 app (Windows App SDK 1.2)
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    X
2. Which SDK version are you using?
    - 5.0.1
6. Which OS version did you experience the issue on?
    - Windows 11 Pro 22H2
7. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Deskop
8. What third party libraries are you using? 
    - Only libraries from Microsoft except "WinUIEX"
9. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
```
"MyApp.exe" (Win32): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.12\System.Reflection.Emit.dll" geladen. 
"MyApp.exe" (CoreCLR: clrhost): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.12\System.Reflection.Emit.dll" geladen. 
"MyApp.exe" (CoreCLR: clrhost): "Snippets" geladen. 
Ausnahme ausgelöst bei 0x00007FFDEC9206BC (KernelBase.dll) in MyApp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x00000053D8F7D590).
"MyApp.exe" (Win32): "C:\Windows\System32\WinMetadata\Windows.ApplicationModel.winmd" geladen. Das Modul wurde ohne Symbole erstellt.
Ausnahme ausgelöst bei 0x00007FFDEC9206BC (KernelBase.dll) in MyApp.exe: 0x40080202: WinRT transform error (Parameter: 0x000000008000000B, 0x0000000080070490, 0x0000000000000019, 0x00000053D8F7D580).
"MyApp.exe" (Win32): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.12\System.ComponentModel.TypeConverter.dll" geladen. 
"MyApp.exe" (CoreCLR: clrhost): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.12\System.ComponentModel.TypeConverter.dll" geladen. 
"MyApp.exe" (Win32): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.12\System.Threading.Thread.dll" geladen. 
"MyApp.exe" (CoreCLR: clrhost): "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.12\System.Threading.Thread.dll" geladen. 
2023-01-03 23:57:51.492 [AppCenter] INFO: Analytics service has already been disabled.
"MyApp.exe" (Win32): "C:\Windows\System32\ntmarta.dll" geladen. 
"MyApp.exe" (Win32): "C:\Windows\System32\feclient.dll" geladen. 
Ausnahme ausgelöst: "System.IO.IOException" in System.Private.CoreLib.dll
Ausnahme ausgelöst: "System.IO.IOException" in System.Private.CoreLib.dll
Ausnahme ausgelöst: "System.IO.IOException" in System.Private.CoreLib.dll
```

**Comment by paulober** [comment]
I don't seem to have this problem when running the app "Unpackaged"

**Comment by paulober** [comment]
It seems like it's due to Filesystem access restrictions inside a packaged app. And the AppCenter SDK trys to create files because it doesn't recognize in the new Windows App SDK that it is running in a packged environment. And because it's retrying it serveral times my app needs like 20sec to boot up.

**Comment by MikhailSuendukov** [comment]
Hi @paulober and thank you for reaching us. I can't reproduce your bug on a Blank WinUI 3 app. It will be very helpful if you send a small demo application that reproduces this error.

**Comment by paulober** [comment]
> Hi @paulober and thank you for reaching us. I can't reproduce your bug on a Blank WinUI 3 app. It will be very helpful if you send a small demo application that reproduces this error.

I'll try to create one. But as i having this problem with a production app which must go live soon i was hopeing if there are some general not in the docs mentioned things you can do to maye fix these System.IO execptions from AppCenter sdk freezing your hole application.

**Comment by paulober** [comment]
@MikhailSuendukov Ok i'm now not having this problem anymore. I don't know what changed it but it's working at the moment. Maybe because i used the nuget also in other projects. Don't know.

**Comment by paulober** [comment]
While i tried to create a sample i just tested my project again and it now works. I don't know why i haven't changed anything on the project it self. Maybe because i used the nugets also in an other project, don't know... 6 hours wasted time...
