### ISSUE TITLE
Big startup performance penalty since .NET6 due to unnecessarily compiled RegEx

### ISSUE THREAD

**Issue by tipa** [microsoft/appcenter-sdk-dotnet#1730]
### **Description**

Please describe the issue you are facing using the SDK.
The compiled Regex [here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/5d6936f1e58b39233750ea7689dce9ba6e54a6c2/SDK/AppCenter/Microsoft.AppCenter.Shared/AppCenter.Shared.cs#L26) is significantly slowing down startup performance since .NET6/.NET7. This has been discussed in detail [here](https://github.com/dotnet/runtime/issues/71007). Before .NET6/7 (in "old" Xamarin) the `RegexOptions.Compiled` flag was ignored so there was no negative performance impact.

The RegEx should not be compiled as it only seems to be executed a single time.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - .NET7 for Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - e.g. .NET7
2. Which SDK version are you using?
    - e.g. 5.0.1

**Comment by MikhailSuendukov** [comment]
Hello @tipa  and thank you for contacting us, I have started the investigation and will be back soon with the results.

**Comment by MikhailSuendukov** [comment]
@tipa your remark makes sense to me. I created a task on our dashboard for implementing such parameter.

**Comment by snakefoot** [comment]
Resolved by AppCenter ver 5.0.2 ?

**Comment by MikhailSuendukov** [comment]
Okay, then I'll close this issue. If you have any other questions about this topic, you can freely reopen it.
