### ISSUE TITLE
[AppCenter] java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by Bloodyairtimer** [microsoft/appcenter-sdk-dotnet#1732]
### **Description**

Experiencing a lot of SocketExceptions when sending the events to AppCenter. Seems to be quit random when it will work or not. Currently on Android and iOS we see this behavior. UWP seems to have it way less. In the logging of Android I see the SocketExceptions with the retry after x miliseconds. Next try also fails than.

I tried to call the endpoint directly from a httpClient to see if I get the same results. See sample below:

            using (var httpCLient = new HttpClient())
            {
                var responseMessage = await httpCLient.GetAsync("https://in.appcenter.ms");
            }

Also getting a socketException with the "Connection reset" message. (Sometimes)

Getting reports from multiple users that it's not working from different locations around the globe. (Netherlands and Philipines.)

### **Repro Steps**

Log some event to AppCenter with Analytics.TrackEvent(eventName, eventDataList); or using the call directly to the url from the HttpClient.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    **Xamarin.Forms on all 3 platforms (Android, iOS and UWP).**

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    **NET standard 2.0.**
2. Which SDK version are you using?
   **AppCenter 5.0.1**
4. Which OS version did you experience the issue on?
    **Android 11, iOS 15.7 and iOS 16.2**
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    physical devices (Samsung galaxy tab 8", ipad mini)

Logs:
[AppCenter] Try #1 failed and will be retried in 5067 ms
[AppCenter] java.net.SocketException: Connection reset
[AppCenter] 	at java.net.SocketInputStream.read(SocketInputStream.java:215)
[AppCenter] 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
[AppCenter] 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
[AppCenter] 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1450)
[AppCenter] 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1399)
[AppCenter] 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1343)
[AppCenter] 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
[AppCenter] 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
[AppCenter] 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
[AppCenter] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
[AppCenter] 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[AppCenter] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[AppCenter] 	at java.lang.Thread.run(Thread.java:923)

[AppCenter] triggerIngestion(group_analytics) pendingLogCount=3
[AppCenter] Trying to get 3 logs from the Persistence database for group_analytics
[AppCenter] Returning 3 log(s) with an ID, f0055a10-42bc-4b7f-89f7-e8ed3f8b929e
[AppCenter] The SID/ID pairs for returning log(s) is/are:
[AppCenter] 	f0809baf-7e2c-414f-952f-ed65a822f236 / 88
[AppCenter] 	f0809baf-7e2c-414f-952f-ed65a822f236 / 89
[AppCenter] 	f0809baf-7e2c-414f-952f-ed65a822f236 / 90
[AppCenter] ingestLogs(group_analytics,f0055a10-42bc-4b7f-89f7-e8ed3f8b929e) pendingLogCount=0
[AppCenter] checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=6000
[AppCenter] The timer for group_analytics channel finished.
[AppCenter] Calling https://in.appcenter.ms/logs?api-version=1.0.0...
[AppCenter] Headers: {Content-Encoding=gzip, Install-ID=54da00cd-0317-4a52-bd58-6da74e26a6c9, App-Secret=****************************9355971d, Content-Type=application/json}
[AppCenter] {
[AppCenter]   "logs": [
[AppCenter]     {
[AppCenter]       "type": "event",
[AppCenter]       "timestamp": "2023-02-16T11:42:28.011Z",
[AppCenter]       "sid": "f0809baf-7e2c-414f-952f-ed65a822f236",
[AppCenter]       "device": {
[AppCenter]         "wrapperSdkVersion": "5.0.1",
[AppCenter]         "wrapperSdkName": "appcenter.xamarin",
[AppCenter]         "wrapperRuntimeVersion": "13.1.99.61",
[AppCenter]         "sdkName": "appcenter.android",
[AppCenter]         "sdkVersion": "5.0.0",
[AppCenter]         "model": "SM-T290",
[AppCenter]         "oemName": "samsung",
[AppCenter]         "osName": "Android",
[AppCenter]         "osVersion": "11",
[AppCenter]         "osBuild": "RP1A.200720.012",
[AppCenter]         "osApiLevel": 30,
[AppCenter]         "locale": "en_US",
[AppCenter]         "timeZoneOffset": 60,
[AppCenter]         "screenSize": "736x1280",
[AppCenter]         "appVersion": "7.0.200156.1",
[AppCenter]         "appBuild": "100",
[AppCenter]         "appNamespace": "xxx.xxx.xxx"
[AppCenter]       },
[AppCenter]       "name": "MainPage_StartSyncButton",
[AppCenter]       "id": "729ba235-58f8-4319-ae37-8f08c7415c00",
[AppCenter]       "typedProperties": [
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "User",
[AppCenter]           "value": "xxx---xx---xx--"
[AppCenter]         },
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "Environment",
[AppCenter]           "value": "xxx-xx-x---xxx-"
[AppCenter]         }
[AppCenter]       ]
[AppCenter]     },
[AppCenter]     {
[AppCenter]       "type": "event",
[AppCenter]       "timestamp": "2023-02-16T11:42:29.520Z",
[AppCenter]       "sid": "f0809baf-7e2c-414f-952f-ed65a822f236",
[AppCenter]       "device": {
[AppCenter]         "wrapperSdkVersion": "5.0.1",
[AppCenter]         "wrapperSdkName": "appcenter.xamarin",
[AppCenter]         "wrapperRuntimeVersion": "13.1.99.61",
[AppCenter]         "sdkName": "appcenter.android",
[AppCenter]         "sdkVersion": "5.0.0",
[AppCenter]         "model": "SM-T290",
[AppCenter]         "oemName": "samsung",
[AppCenter]         "osName": "Android",
[AppCenter]         "osVersion": "11",
[AppCenter]         "osBuild": "RP1A.200720.012",
[AppCenter]         "osApiLevel": 30,
[AppCenter]         "locale": "en_US",
[AppCenter]         "timeZoneOffset": 60,
[AppCenter]         "screenSize": "736x1280",
[AppCenter]         "appVersion": "7.0.200156.1",
[AppCenter]         "appBuild": "100",
[AppCenter]         "appNamespace": "xxxx---xxxxxxxxx---xxx"
[AppCenter]       },
[AppCenter]       "name": "HomeViewModel",
[AppCenter]       "id": "85418a8b-9682-40cc-9377-8c88eb6f0b75",
[AppCenter]       "typedProperties": [
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "Parameters",
[AppCenter]           "value": "Empty"
[AppCenter]         },
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "User",
[AppCenter]           "value": "xxxxxxxxxxxxxxxx"
[AppCenter]         },
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "Environment",
[AppCenter]           "value": "xxxxxxxxxxxxxxxxxxx"
[AppCenter]         }
[AppCenter]       ]
[AppCenter]     },
[AppCenter]     {
[AppCenter]       "type": "event",
[AppCenter]       "timestamp": "2023-02-16T11:42:29.885Z",
[AppCenter]       "sid": "f0809baf-7e2c-414f-952f-ed65a822f236",
[AppCenter]       "device": {
[AppCenter]         "wrapperSdkVersion": "5.0.1",
[AppCenter]         "wrapperSdkName": "appcenter.xamarin",
[AppCenter]         "wrapperRuntimeVersion": "13.1.99.61",
[AppCenter]         "sdkName": "appcenter.android",
[AppCenter]         "sdkVersion": "5.0.0",
[AppCenter]         "model": "SM-T290",
[AppCenter]         "oemName": "samsung",
[AppCenter]         "osName": "Android",
[AppCenter]         "osVersion": "11",
[AppCenter]         "osBuild": "RP1A.200720.012",
[AppCenter]         "osApiLevel": 30,
[AppCenter]         "locale": "en_US",
[AppCenter]         "timeZoneOffset": 60,
[AppCenter]         "screenSize": "736x1280",
[AppCenter]         "appVersion": "7.0.200156.1",
[AppCenter]         "appBuild": "100",
[AppCenter]         "appNamespace": "xxxxxxxxxxxxxxxxxxxx"
[AppCenter]       },
[AppCenter]       "name": "Home Page",
[AppCenter]       "id": "20a5488e-f220-45d9-8d36-5090378b1208",
[AppCenter]       "typedProperties": [
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "User",
[AppCenter]           "value": "xxxxxxxxxxxxxx"
[AppCenter]         },
[AppCenter]         {
[AppCenter]           "type": "string",
[AppCenter]           "name": "Environment",
[AppCenter]           "value": "xxxxxxxxxxxxxxx"
[AppCenter]         }
[AppCenter]       ]
[AppCenter]     }
[AppCenter]   ]
[AppCenter] }

**Comment by shadyabarada** [comment]
Hi @Bloodyairtimer , thank you for your patience we are currently actively looking into and analyzing this issue and will get back to you as soon as we have a fix.

**Comment by Bloodyairtimer** [comment]
> Hello @Bloodyairtimer, the issue should be mitigated. Could you please confirm it?

Hi @AnatolyPristensky I have checked the issue. Still occurring on our end. Getting a little bit of a different exception this time:

[AppCenter] Try #1 failed and will be retried in 9686 ms
[AppCenter] java.net.SocketTimeoutException: failed to connect to in.appcenter.ms/40.70.161.7 (port 443) from /192.168.10.61 (port 47772) after 10000ms

Also checked with others, but no events incoming.

**Comment by Bloodyairtimer** [comment]
Retested it today and the issues seems to be resolved now. Thanks @shadyabarada & @AnatolyPristensky
