### ISSUE TITLE
Unable to build for iPhoneSimulator on a Xamarin project since v5.0.1

### ISSUE THREAD

**Issue by DjeeBay** [microsoft/appcenter-sdk-dotnet#1733]
### **Description**

After updating package  Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes from 4.5.3 to 5.0.1 on a Xamarin.Forms 5.0.0.2578 I cannot build the iOS project for the iPhoneSimulator.

I have the following issues :
- /Project.iOS/error MT5209: Error: warning: ignoring file /obj/iPhoneSimulator/Debug/mtouch-cache/AppCenter.a, file is universal (x86_64,arm64,arm64e) but does not contain the i386 architecture: /obj/iPhoneSimulator/Debug/mtouch-cache/AppCenter.a (Project.iOS) Native linking

- /Project.iOS/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: MSACAnalytics. The symbol '_OBJC_CLASS_$_MSACAnalytics' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (Project.iOS)

### **Details**

1. App platform : Xamarin.iOS
2. IDE : Visual Studio Mac
3. Target : iPhoneSimulator

**Comment by DjeeBay** [comment]
Workaround in my case :
In the iOS project properties, go to iOS > Build > Supported architectures : switched from **i386 + x86_64** to **x86_64**

Now it builds and run. But I'm not sure what are the consequences for real devices.

**Comment by MikhailSuendukov** [comment]
Hello @DjeeBay and sorry for the long response. The fact is that we no longer support the i386 architecture. But this error will not affect the work on a real device. This limitation is only related to simulators. Here is a [thread](https://developer.apple.com/forums/thread/90648) on the apple forum about it.
