### ISSUE TITLE
`SystemInformation.Instance.LaunchTime` doesn't get the launch time correctly

### ISSUE THREAD

**Issue by yikuo123** [microsoft/appcenter-sdk-dotnet#1739]
### **Description**

I encountered an issue with `SystemInformation.Instance.LaunchTime` on Xbox platform. In some cases, it did not work as expected and failed to get the `launchTime`. I also observed this phenomenon occasionally on PC platform.

I suspect that this might be related to the way the app is terminated, because `SystemInformation.Instance.TrackAppUse` first checks the `args.PreviousExecutionState`, which might cause the issue.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - UWP
2. Which SDK version are you using?
    - 5.0.1
4. Which OS version did you experience the issue on?
    - WINDOWS 10.0.22621
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Xbox and PC

**Comment by MikhailSuendukov** [comment]
Hello, thank you for reaching out to us, I need some time to investigate your issue. I'll be back soon with information.
