### ISSUE TITLE
MAUI Blazor Hybrid - linker error on iOS Simulator

### ISSUE THREAD

**Issue by iw1qlh** [microsoft/appcenter-sdk-dotnet#1748]
### **Description**

Adding AppCenter SDK to a MAUI Blazor Hybrid project, debugging using iOS Simulator on paired MAC I have this error message:
**clang++ exited with code 1**
in the output log:

- 1>ld: in /Users/.../Library/Caches/Xamarin/mtbs/builds/MauiHybridApp/.../obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/AppCenterCrashes.a(MSACErrorReport.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/.../Library/Caches/Xamarin/mtbs/builds/MauiHybridApp/.../obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/AppCenterCrashes.a'
- 1>clang: error: linker command failed with exit code 1 (use -v to see invocation)
- 1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\targets\Xamarin.Shared.Sdk.targets(1274,3): error : clang++ exited with code 1:
- 1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\targets\Xamarin.Shared.Sdk.targets(1274,3): error : ld: in /Users/.../Library/Caches/Xamarin/mtbs/builds/MauiHybridApp/.../obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/AppCenterCrashes.a(MSACErrorReport.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/.../Library/Caches/Xamarin/mtbs/builds/MauiHybridApp/.../obj/Debug/net7.0-ios/iossimulator-arm64/linker-cache/AppCenterCrashes.a'
- 1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7089\targets\Xamarin.Shared.Sdk.targets(1274,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation)
- 1>Done building project "MauiHybridApp.csproj" -- FAILED.

The issue still persists even after Clean, Rebuild, Build, deleting bin and obj folders, restarting VS, logout/login on paired MAC

### **Repro Steps**

1. Create a new .NET MAUI Blazor App
2. Pair a MAC
3. Debug - iPhone 8 Plus iOS 16.4 => the code is compiled, the application is executed
4. Add packages Microsoft.AppCenter (5.0.2) and Microsoft.AppCenter.Crashes (5.0.2) to the MAUI Blazor Hybrid project
5. Add `using Microsoft.AppCenter; using Microsoft.AppCenter.Crashes;`  - `AppCenter.Start("secret-code", typeof(Crashes))` to MauiProgram.cs
6. Debug again => Build error

### **Details**

1. Microsoft.AppCenter 5.0.2
2. Framework net7.0-ios
3. Mac mini - Chip Apple M1 - MacOS Ventura 13.3.1 - XCode 14.3.1
4. VS 17.7.0 Preview 1.0 and Preview 3.0

**Comment by AnatolyPristensky** [comment]
Hello @iw1qlh,
We have no official support of MAUI Blazor yet. 
I would ask you try to disable hot reload and hot restart if you are using such, and check if it helps.

**Comment by Yves-Be** [comment]
I'm also seeing this with .NET 8 MAUI apps, not just MAUI Blazor. Both the AppCenter.Analytics package and AppCenter.Crashes are affected.

I believe it might be related due to the fact that apps for the simulator are being built for the iossimulator-arm64, where it used to be the x64 build. (This x64 build also ran on the ARM simulator with Rosetta, and in the Rosetta Simulator itself)

Could it be that the native iOS AppCenter library is missing some iossimulator-arm64 bits?
The Sqlite.Raw package and SkiaSharp already had some fixes for similar issues.

I already tried forcing the RuntimeIdentifier to iossimulator-x64, but that doesn't seem to do anything.

**Comment by MikhailSuendukov** [comment]
Hello @Yves-Be, as far as I know .NET 8 MAUI has not been officially released yet. Could you please provide steps to reproduce this bug or a small demo project on which your bug is reproduced?

**Comment by Yves-Be** [comment]
@MikhailSuendukov Sure, here's a repo: [net8-maui-ios-arm64-appcenter](https://github.com/Yves-Be/net8-maui-ios-arm64-appcenter).

### Repro Steps
1. Create a new .NET 8 MAUI App
2. Install AppCenter.Crashes or AppCenter.Analytics
3. Pair with a MAC with an Apple Silicon chip
4. Select any iOS Simulator
5. Try to build

**Comment by Yves-Be** [comment]
It is indeed Visual Studio 17.7 that now has the new default behavior to build for the ARM64 Simulator, so it is not .NET 8 specific, and .NET 7 projects will also be affected.
The best workaround is to add the following element to your .csproj:
`<ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>`
This restores the previous behavior.

I do still believe that some changes might be required in the Appcenter libraries to add support for the ARM64 Simulator.

**Comment by MikhailSuendukov** [comment]
Thanks for your investigation and information. At the moment, we have already implemented support for arm64. So the problem is really either in Visual Studio or pairing with your Mac.
