### ISSUE TITLE
[ macOS ] [ 5.0.2 ] "Asset validation failed" error when submitting to App Store

### ISSUE THREAD

**Issue by FoggyFinder** [microsoft/appcenter-sdk-dotnet#1753]
### **Description**

```xml
<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.2" />
<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.2" />
```

Since upgrade `Analytics` & `Crashes` packages to `5.0.2` version App Store automatically rejects app with following message:

```json
{
  "NSLocalizedDescription": "Asset validation failed",
  "NSLocalizedFailureReason": "The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools. (ID: id)",
  "original_server_error": {
    "code": "STATE_ERROR.VALIDATION_ERROR.90135",
    "detail": "The executable could not be re-signed for submission to the App Store. The app may have been built or signed with non-compliant or pre-release tools.",
    "id": "id",
    "status": 409,
    "title": "Asset validation failed"
  }
}
```

Only Mac platform is affected, iOS/Android/Win seems fine

### **Workaround**

Revert to `5.0.1`

**Comment by DmitriyKirakosyan** [comment]
Hi @FoggyFinder , thank you for reporting this issue!

I wonder which of the changes could case this rejection. Possibly https://github.com/microsoft/appcenter-sdk-dotnet/pull/1729.

Which versions of Xcode and VisualStudio are you on?

**Comment by FoggyFinder** [comment]
> Which versions of Xcode and VisualStudio are you on?

@DmitriyKirakosyan pipeline uses `macos-latest`, so according to [this](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#macos-12)

XCode - 14.2 and 
VS for Mac - 2022 (default) 17.6.4.472

**Comment by DmitriyKirakosyan** [comment]
@FoggyFinder ,  have prepared a PR with a potential fix. We will inform you as soon as we have an SDK build ready for you to test.

**Comment by DmitriyKirakosyan** [comment]
@FoggyFinder, I've attached the NuGet packages below. Eager to know if they work for you!

[AppCenterAnalytics.nupkg.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/13217566/AppCenterAnalytics.nupkg.zip)
[AppCenterCrashes.nupkg.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/13217569/AppCenterCrashes.nupkg.zip)
[AppCenterDistribute.nupkg.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/13217570/AppCenterDistribute.nupkg.zip)

**Comment by DmitriyKirakosyan** [comment]
I'm going to close this issue due to inactivity. @FoggyFinder please let me know if you are still interested in it.
