### ISSUE TITLE
Use DefaultApplicationSettings from UWP in packaged WinUI 3 project?

### ISSUE THREAD

**Issue by Marv51** [microsoft/appcenter-sdk-dotnet#1758]
**Is your feature request related to a problem?**
I am working on a packaged WinUI 3 application. 
Settings in a packaged project are stored in a pretty weird way and in an uncommon location: 

Inside the packaged application data:
LocalCache\Local\[company name]\[appname]_Url_sg3j4gg2am51ysim2dgiox50dw2qtdti\AppCenter.config

It seems to store one settings file per installed update? I have 6 different `[appname]_Url_[hash]` folders for my app.
Interestingly each containing a different AppCenterInstallId.

Additionally, AppCenter is the only library that requires the System.ConfigurationManager (~1MB, incl. ReadyToRun code) library.

**Describe the solution you'd like**
I would like to use the Microsoft.AppCenter.UWP/Utils/DefaultApplicationSettings.cs in my WinUI3 application. It is a small (30 line), native alternative to a complicated current system.

**Describe alternatives you've considered**
I could set my own settings implementation easily, if this wasn't `[Obsolete]:
https://github.com/microsoft/appcenter-sdk-dotnet/blob/e79284db5b2fff7c69211085deb0978c18f5ebea/SDK/AppCenter/Microsoft.AppCenter.Shared.Windows/AppCenter.cs#L160-L162
(It seems this feature was introduced in 2017 already with the obsolete attribute: https://github.com/microsoft/appcenter-sdk-dotnet/commit/dafd96b40de08d4bae76f38317245818ae688ace I do not understand what the idea here was.)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue. However, contributions are still welcome.
