### ISSUE TITLE
Apple Privacy Manifest : Appcenter Crash/Analytics Data collection

### ISSUE THREAD

**Issue by akhilvswoodplc** [microsoft/appcenter-sdk-dotnet#1775]
This is rather a clarification request on Apple's Privacy manifest. If we are using Appcenter Crash/Analytics sdks in the application, Do we need to mention any information on the Privacy manifest

**Comment by DmitriyKirakosyan** [comment]
Hi @akhilvswoodplc, thanks for reaching out!

You can find all the App Center requirements for the Privacy Manifest in the following files:

[App Center PrivacyInfo.xcprivacy](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenter/PrivacyInfo.xcprivacy)
[App Center Crashes PrivacyInfo.xcprivacy](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenterCrashes/PrivacyInfo.xcprivacy)

The App Center Dotnet Apple SDK is a wrapper for the App Center Apple SDK, which means these requirements also apply to the Dotnet SDK.

**Comment by akhilvswoodplc** [comment]
@DmitriyKirakosyan 
Thanks for the update.
So when an App uses appcenter sdk, is it required to define those same entries in out app provacy manifest file also or the file is available in the sdk itself?

**Comment by viswanath-pamarthi** [comment]
@DmitriyKirakosyan 
When is the next SDK release date ?

**Comment by MikhailSuendukov** [comment]
Hello, the [AppCenter .NET SDK v5.0.4](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.4) has been released, including a fix for this issue. Therefore, I am closing this issue.
