### ISSUE TITLE
Send custom identifiers

### ISSUE THREAD

**Issue by help-14** [Microsoft/AppCenter-SDK-DotNet#284]
It should be able to sent custom info like email or user id manually so we can see exactly how many users are using, not just how many devices are using.

**Comment by elamalani** [comment]
@help-14 We plan to support custom properties in Mobile Center going forward but there is no ETA yet. You should be able to use them for sending custom info like email.

**Comment by elamalani** [comment]
@help-14 Could you also help me understand what information do you want to send? Is it specific to Analytics or Crashes services? How would you want this information to be displayed or aggregated in the portal? Thanks!

**Comment by MisterJimson** [comment]
I would want full history on each user. So I could compare a workflow they did a month ago to how they did it today. Trace their steps. Xamarin Insights does this very well.

**Comment by blparr** [comment]
Hello!

Custom properties are now in Mobile Center. This can be defined using our SDK and used to create Audiences under Push notifications. This will allow you to send targeted notifications to your users based on a set of properties that you define (e.g. premium users, ...). You can see more information at: https://docs.microsoft.com/en-us/mobile-center/push/audiences.

Regarding the idea of identifying and see the history for a user, this is something we are currently thinking about and considering, not ETA for it yet.

**Comment by MisterJimson** [comment]
Any update on this? Specifically session history or user history like Xamarin Insights?

**Comment by blparr** [comment]
Not yet @MisterJimson, we are working hard to stop being a preview product, and then will look into this feature. Thanks for your patience!

Best,
Blanca

**Comment by MisterJimson** [comment]
Thanks for the update.

**Comment by guperrot** [comment]
`AppCenter.SetCustomProperties` does not have a REST API equivalent today.

**Comment by guperrot** [comment]
That API is to create an audience without using the portal, this does not set custom properties for a device on behalf of the SDK.

**Comment by titonton** [comment]
I wasn't exactly talking about the devices, but for the audience themselves. But you're right, if I'm not going to be using the console then it will create the audience with whatever properties dynamically. It was a stupid question on my part to begin with. Thanks for your help guys!

**Comment by guperrot** [comment]
@titonton Hi, that was a good question, no worries about that ;) and thanks for using App Center. Don't hesitate to ask other questions, maybe on a new issue or you can chat with us using the blue button on https://appcenter.ms.

**Comment by breyed** [comment]
When you set properties with `SetCustomProperties`, the data is exported to App Insights in a custom event of type `CustomPropertyLog` with a `Properties` property like this:

``` json
[{"type":"String","name":"Key1","value":"Value1"},{"type":"String","name":"Key2","value":"Value2"}]
```

What I thought would happen is that the custom properties would be visible on each subsequent event in App Insights, until the custom properties were changed again. That would make it easy to filter the events by context, where the context is defined as the custom properties in place at the time.

As it is, is there some other way in App Insights to correlate custom properties with their subsequent events to enable filtering of events by custom properties?

**Comment by breyed** [comment]
Also, when viewing events on appcenter.ms, the custom properties don't show up. I expected them to be merged with the specific properties of events. The [docs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#use-custom-properties) I found don't lend any insight into what custom properties are for other than "various purposes" which include push notifications.

**Comment by breyed** [comment]
I had left a couple comments about correlating custom properties to events, but then this issue was closed. So I moved them into a new issue (#829) for better tracking.

**Comment by joehanna** [comment]
Added in 0.13.0... and now they're gone in 4.5.0 

It is getting painful to invest in Microsoft platforms. Bring in a feature we need, we rely on it, and then it is taken away.

https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/CHANGELOG.md#app-center-1

**Comment by DmitriyKirakosyan** [comment]
Hi @joehanna , could you please describe how you use Custom Properties API?
If it is used for user identification, there is a dedicated [setUserId API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#identify-users).

**Comment by joehanna** [comment]
Thanks @DmitriyKirakosyan. First that is on an Android API page, what about iOS? Also, setUserId is one field and I need many to segment the users.

**Comment by DmitriyKirakosyan** [comment]
@joehanna , `setUserId` API is available on all platforms.

> Also, setUserId is one field and I need many to segment the users.

Only one field `userId` is supported at this moment. We have a feature request for adding predefined properties: https://github.com/microsoft/appcenter/issues/2335.

**Comment by APIWT** [comment]
@DmitriyKirakosyan We have been using this API for years to track things specific to our application that are not specific to an analytics event. What are we supposed to use to track arbitrary things related to the user that are not used for identification?

**Comment by DmitriyKirakosyan** [comment]
@APIWT As alternative, an event with such properties related to user can be sent on app start. Would it work for you?

**Comment by APIWT** [comment]
> @APIWT As alternative, an event with such properties related to user can be sent on app start. Would it work for you?

@DmitriyKirakosyan Unfortunately this would not work, since there is another product team within our organization that utilizes the App Insights export to query the various custom properties we set, and whichever solution we utilize needs to be backwards compatible with the existing data they have exported.

I do not understand why this feature was removed from the SDKs. It still seems to be services on the backend, and ultimately it is a very handy feature.

Is there any possible way we can make a call from our app to the backend endpoint manually? I was poking around yesterday and it seems to process would be similar to uploading crash logs manually.

**Comment by joehanna** [comment]
@APIWT I agree and wonder the same thing. I suspect they don't want the free App Center insights to be too attractive and want us all to subscribe to Azure for the functionality.

**Comment by akamenev** [comment]
Unfortunately, custom properties are not supported today and the only alternative is to use TrackEvent. We will look into this in the future, but for now we do not have any plans to add this feature back.

**Comment by help-14** [comment]
Wow after 6 years moving from Microsoft platform, I still receive notification for this issue 🤣
