### ISSUE TITLE
Export analytics, crashes and other telemetry?

### ISSUE THREAD

**Issue by degant** [Microsoft/AppCenter-SDK-DotNet#319]
Is there a way to export analytics, crashes and other telemetry? 

Also, what is the retention policy for analytics on Mobile Center? The dropdown only has options for 'Last 7/30/60/90 days'. Does that mean there is a limit of 90 days?

Can we export the telemetry to our systems so that we can query data after 90 days?

**Comment by blparr** [comment]
Hello @degant ! Currently, there is no way to do that. However, we are actively working on a feature to Export the Analytics and Crashes data. This will allow you to store the data for longer than 90 days (current retention) and query the data.

Hope this clarifies your question. Thanks!

**Comment by blparr** [comment]
Hello! I'd like to let you know that you can now export your raw data into Blob Storage and Application Insights, check out our documentation at: https://docs.microsoft.com/en-us/mobile-center/analytics/export and let us know what you think!
