### ISSUE TITLE
Missing Method Exception in Start method for UWP (Xamarin Forms)

### ISSUE THREAD

**Issue by snehithv** [microsoft/appcenter-sdk-dotnet#390]
I added the mobile centre SDK to my xamarin forms app and then added the below in App.xaml.cs:
    MobileCenter.Start("ios=eab5ae24-2c21-4bc4-af8b-bdc01b41d27d;" +
                               "uwp=08df195d-1f0d-42db-bf5c-70de451d9e3a" +
                               "android=fab0066e-af9a-494f-b677-b231cfec53b9",
                typeof(Analytics), typeof(Crashes));

It works well in iOS and Andriod but results in the below error in UWP:

System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken Windows.ApplicationModel.Core.CoreApplication.add_LeavingBackground(System.EventHandler`1<Windows.ApplicationModel.LeavingBackgroundEventArgs>)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Azure.Mobile.Utils.ApplicationLifecycleHelper..ctor()
   at Microsoft.Azure.Mobile.Utils.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.Azure.Mobile.MobileCenter.InstanceConfigure(String appSecretOrSecrets)
   at Microsoft.Azure.Mobile.MobileCenter.StartInstanceAndConfigure(String appSecret, Type[] services)
   at Microsoft.Azure.Mobile.MobileCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.Azure.Mobile.MobileCenter.Start(String appSecret, Type[] services)
   at TILL.POS.App.OnStart() in C:\Source\Till-POS\2.Clients\TILL.POS\App.xaml.cs:line 199
   at Xamarin.Forms.Platform.UWP.WindowsBasePage.LoadApplication(Application application)

**Comment by achocron** [comment]
What build of Windows are you targeting? It should run without issues on older builds of Windows 10, but I've seen cases where targeting builds before 14393 can cause issues.

**Comment by guperrot** [comment]
No news here, closing.

**Comment by saraford** [comment]
@guperrot I'm hitting the same issue here for UWP. Same callstack. I'm on Windows 10 build 16299.

**Comment by saraford** [comment]
Yesterday the Getting Started instructions for my App registration said to use `MobileCenter.Start()` but this morning, I'm seeing different instructions to use `AppCenter.Start()` along with different using statements. 😕 

Fortunately I took a screenshot of the instructions yesterday. 😄  

**Today**
![image](https://user-images.githubusercontent.com/11529908/32849250-7a03db7e-c9e3-11e7-941f-8156e8d705a0.png)

**Yesterday** 
![image](https://user-images.githubusercontent.com/11529908/32849317-a4aecdac-c9e3-11e7-8182-90ff2a48176e.png)

Did something deploy last night? Is `AppCenter.Start()` the correct method to use?

**Comment by saraford** [comment]
Ha! I'll take this blog post as a yes 😆 https://blogs.msdn.microsoft.com/vsappcenter/introducing-visual-studio-app-center/

I'll update my project and see if it still repros. Thanks! 🙏

**Comment by achocron** [comment]
Yes, please use the new packages! But we haven't made a specific fix, so I won't be surprised if the issue persists for you. You said you're using Windows 16299 - but which build are you actually targeting?

**Comment by saraford** [comment]
Ah, I see. I'm using the default target values, which is Build 10240 (found under Properties - Application page, just FYI in case anyone else hits this). I'll try using the new packages and report back.

Instead of being "a day late and a dollar short" I was just a day too early! :)

**Comment by achocron** [comment]
Got it - can you also please target 14393 or later? It will still run on the minimum version and won't throw an exception on those devices, but the target needs to be 14393 or higher.

**Comment by luminelx64** [comment]
AppCenter.Start("{my` secret}", typeof(Analytics), typeof(Crashes), typeof(Push)) 
yields the below error on UWP targeting build 16299, and Minimum 10240

"Could not load file or assembly 'SQLite-net, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

**Comment by achocron** [comment]
That's actually a separate problem- can you try manually adding the sqlite-net-pcl package version 1.3.1 and let me know if that fixes it?

**Comment by luminelx64** [comment]
I already have sqlite-net-pcl 1.4.118 installed. Do I need to downgrade? I don't know that the consequence will be.

**Comment by achocron** [comment]
Could you try downgrading to see what happens?

**Comment by luminelx64** [comment]
@achocron I have resolved the issue.
Downgrading sqlite-net-pcl put the entire project in disarray
There was an error indicating a conflict in e_sqlite3.dll (didn't remember to copy the details).

I removed the Microsoft.NETCore.UniversalWindowsPlatform nuget completely.
Then manually deleted a folder C:\Users\{username}\.nuget\packages\sqlitepclraw.lib.e_sqlite3.v140\1.1.5

Leaving only the ...\sqlitepclraw.lib.e_sqlite3.v140\1.1.2 and 1.18 folders intact
I can't remember why I had to add the Microsoft.NETCore.UniversalWindowsPlatform nuget previously, but it seems unnecessary now.

**Comment by guperrot** [comment]
We also added support for sqlite-net-pcl version 1.5 in version [1.1.0](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.1.0).

**Comment by surensaluka** [comment]
Hi,
I have tested this and found when you have the minimum target version below build 14393 it does not work. My current configuration is Min version build 14393 and Target version build 17763.

**Comment by AnastasiaKubova** [comment]
Hi, @surensaluka! Could you please clarify what version of the SDK you use and what kind of error you have?

**Comment by surensaluka** [comment]
> Hi, @surensaluka! Could you please clarify what version of the SDK you use and what kind of error you have?

OS: Windows 10 Build 17134.765
SDK: Min version build 10240 and Target version build 10586.
Error: Please refer the first comment. (@snehithv's comment)

**Comment by russelarms** [comment]
@surensaluka 
Please, check out this comment:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/390/#issuecomment-344703039
