### ISSUE TITLE
Payload contains two ore more files with the same destination path 'WatsonRegistrationUtility.dll'

### ISSUE THREAD

**Issue by bmarchionni** [microsoft/appcenter-sdk-dotnet#423]
On my UWP Xamarin mobile app, after updating from Microsoft.Azure.Mobile.Crashes v0.14.0 to v0.14.2 I started getting this error on compile. Reverting resolves the issue.

I have references to both Microsoft.Azure.Mobile.Crashes and Microsoft.Azure.Mobile.Analytics, my app targets x86, x64 and arm. I've seen it with any of the target build options including Any CPU.

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1740,5): error APPX1101: Payload contains two or more files with the same destination path 'WatsonRegistrationUtility.dll'. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1740,5): error APPX1101: C:\Users\User\\.nuget\packages\microsoft.azure.mobile.crashes\0.14.2\build\uap10.0\..\..\runtimes\win10-x86\native\WatsonRegistrationUtility.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(1740,5): error APPX1101: C:\Users\User\\.nuget\packages\Microsoft.Azure.Mobile.Crashes\0.14.2\runtimes\win10-x86\lib\uap10.0\WatsonRegistrationUtility.dll

**Comment by achocron** [comment]
Hey, do you still encounter this issue with the latest release `0.15.0`?

**Comment by bmarchionni** [comment]
I cleared my NuGet cache and it now works as expected at version 0.15.0 thanks for the tip!

**Comment by Jamminroot** [comment]
Thanks for bringin this to our attention. Ill have a look at this and try to reproduce.

**Comment by Jamminroot** [comment]
Hey, @michaelstonis, I've tried to reproduce the problem with several SDK versions (2.1.1, 2.2.1-preview, 2.3.0-preview) but all versions worked just fine. Is there any specific details I might be missing? Tested with VS 2019 16.3.0 preview 2.0

**Comment by michaelstonis** [comment]
This issue occurs specifically was with version 2.1.1. I bumped the version to 2.3.0-preview and it compiles without issue.

This is for a client project, so I can't exactly post the solution here, but I would be more than glad to supply any other details that you need via private communications.

**Comment by guperrot** [comment]
Hi, for UWP you cannot have Crashes just yet using the preview SDK:

```
This preview version removes Crashes support for UWP. The App Center backend is not yet ready to process UWP crashes using the system introduced in this version. If your app relies on UWP crashes, do not update to this preview version.
``` from https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.2.1-preview

And in the docs: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#package-manager-console

Please stay in the latest stable version (no prerelease) if you need crashes support for UWP until we support the new pipeline.

**Comment by mikegoatly** [comment]
@michaelstonis I've raised this as a bug with the VS team - from the sounds of things it's their problem and will be fixed - you can track it [here](https://developercommunity.visualstudio.com/content/problem/719729/uwp-apps-importing-microsoftappcentercrashes-do-no.html).

**Comment by guperrot** [comment]
Hi, thanks for following up with VS team, we can close this one then.
