### ISSUE TITLE
Sometimes App hangs without internet connection UWP SDK

### ISSUE THREAD

**Issue by snrnats** [Microsoft/AppCenter-SDK-DotNet#517]
I am using MobileCenter 0.17.1 in the App. I've got a lot of hangs in Developer Dashboard. I suspect MobileCenter.Start method in App.ctor().
[devCenter.zip](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/1485842/devCenter.zip)

I was able to reproduce the hang in local environment both MobileCenter 0.17.1 and AppCenter 1.0.1. It happens rarely. Steps:
- Disable internet on the target device.
- Run a in-process background task without launching the app.
- It hangs on PauseExecutionUntilNetworkBecomesAvailable()
-- I also tried disable/enable internet connection while running background task. It seems to cause issue much often.
[appcenterlog.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/1485852/appcenter.txt)
[LocalDump](https://1drv.ms/u/s!AmwrM5g-csqJk9dcQHdAtLxcywOiMA)
![untitled](https://user-images.githubusercontent.com/1597284/32994081-67ff882c-cd73-11e7-8d10-c2422bb0c905.png)

**Comment by achocron** [comment]
Thanks! Added to our backlog.

**Comment by pfaucon** [comment]
Looking to start using App Center once managed exceptions are supported, is there any update on this ?

**Comment by elamalani** [comment]
@pfaucon Managed exceptions will be supported in App Center for Xamarin platform very shortly (most likely in a week or two). If you want to get early preview access to that feature, please share your email address that you use for App Center.

**Comment by elamalani** [comment]
@pfaucon We have prioritized this work in our backlog and will fix it soon.

**Comment by EmilAlipiev** [comment]
is there any progress on this issue?

**Comment by elamalani** [comment]
@EmilAlipiev There is no update on this bug yet. We will let you know once this is fixed and ready for a release.

**Comment by MatkovIvan** [comment]
Hi @snrnats 

The fix for this is merged to `develop`, but not released yet.
It would be great if you could verify that this issue is solved now.

Best,
Ivan

**Comment by snrnats** [comment]
Hi @MatkovIvan 

I wasn't able to reproduce the bug even using the reported version 1.0.1. Seems like something has changed on my side since then.

**Comment by guperrot** [comment]
@snrnats [1.6.0](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.6.0) has been released with both your PRs.
