### ISSUE TITLE
Crash in ApplyEnabledState() UWP SDK

### ISSUE THREAD

**Issue by snrnats** [Microsoft/AppCenter-SDK-DotNet#518]
I am using MobileCenter SDK 0.17.1.
I guess CreatePushNotificationChannelForApplicationAsync() causes crashes
Exceptions code are different:

- TaskExceptionHolder_UnhandledException (The notification platform does not have the proper privileges to complete the request. (Excep_FromHResult 0x803E0208))
- TaskExceptionHolder_UnhandledException (The object invoked has disconnected from its clients. (Excep_FromHResult 0x80010108))
- TaskExceptionHolder_UnhandledException (A notification channel request for the provided application identifier is in progress. (Excep_FromHResult 0x803E0103))
- TaskExceptionHolder_UnhandledException (Excep_FromHResult 0x880403E9)
- And others

`0   SharedLibrary                        0x00007fff7db31c61 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs at 61:13
1   SharedLibrary                        0x00007fff7db85ce0 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 182:25
2   SharedLibrary                        0x00007fff7db85c68 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 151:42
3   SharedLibrary                        0x00007fff7db85c27 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd($Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs at 123:17
4   CryptoCoins.UWP                      0x00007fff642a24fa Microsoft.Azure.Mobile.Push.Push.<>c__DisplayClass5_0.<<ApplyEnabledState>b__0>d.MoveNext() in  at 0:0`

**Comment by achocron** [comment]
Thanks for reporting this; I've added it to our backlog.

**Comment by guperrot** [comment]
Fixed and released in version [1.1.0](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.1.0).
