### ISSUE TITLE
Didn't find class "md5077d3f1b65f0ebbab0ee71c2383ed9a2.AndroidCrashListener

### ISSUE THREAD

**Issue by KhuongNtrd** [Microsoft/AppCenter-SDK-DotNet#557]
Get **TargetInvocationException** in release mode on Xamarin.Android with Multi-dex enabled.

`12-17 16:14:05.343 I/MonoDroid( 5125): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Crashes.Crashes' threw an exception. ---> Java.Lang.ClassNotFoundException: Didn't find class "md5077d3f1b65f0ebbab0ee71c2383ed9a2.AndroidCrashListener" on path: DexPathList[[zip file "/data/app/fiveminute.toeicphoto.droid-1/base.apk"],nativeLibraryDirectories=[/data/app/fiveminute.toeicphoto.droid-1/lib/arm64, /data/app/fiveminute.toeicphoto.droid-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
12-17 16:14:05.343 I/MonoDroid( 5125):   at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00114] in <319dac7ba7564adc955025895d5353b6>:0 
12-17 16:14:05.343 I/MonoDroid( 5125):   at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <319dac7ba7564adc955025895d5353b6>:0 
12-17 16:14:05.343 I/MonoDroid( 5125):   at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x00064] in <319dac7ba7564adc955025895d5353b6>:0 
12-17 16:14:05.343 I/MonoDroid( 5125):   at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x0002c] in <319dac7ba7564adc955025895d5353b6>:0 
12-17 16:14:05.344 I/MonoDroid( 5125):   at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00032] in <319dac7ba7564adc955025895d5353b6>:0 
12-17 16:14:05.344 I/MonoDroid( 5125):   at Java.Lang.Object..ctor () [0x00034] in <ac06db5fbce34cf48377b108a8d23789>:0 
12-17 16:14:05.344 I/MonoDroid( 5125):   at Microsoft.AppCenter.Crashes.AndroidCrashListener..ctor (Microsoft.AppCenter.Crashes.PlatformCrashes owner) [0x00000] in <8ab89aac5c594cccad87baafb7dfe305>:0 
12-17 16:14:05.344 I/MonoDroid( 5125):   at Microsoft.AppCenter.Crashes.PlatformCrashes..ctor () [0x00006] in <8ab89aac5c594cccad87baafb7dfe305>:0 
12-17 16:14:05.344 I/MonoDroid( 5125):   at Microsoft.AppCenter.Crashes.Crashes..cctor () [0x0000a] in <8ab89aac5c594cccad87baafb7dfe305>:0 `

**Comment by varon** [comment]
Also experiencing this issue:

```
Unhandled Exception:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

12-17 17:14:43.155 I/MonoDroid(30427): UNHANDLED EXCEPTION:
12-17 17:14:43.164 I/MonoDroid(30427): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Crashes.Crashes' threw an exception. ---> Java.Lang.ClassNotFoundException: Didn't find class "md5077d3f1b65f0ebbab0ee71c2383ed9a2.AndroidCrashListener" on path: DexPathList[[zip file "/data/app/com.eezyfile.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.eezyfile.android-1/lib/arm, /vendor/lib, /system/lib]]
12-17 17:14:43.165 I/MonoDroid(30427):   at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x00114] in <54816278eed9488eb28d3597fecd78f8>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <54816278eed9488eb28d3597fecd78f8>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Java.Interop.JniPeerMembers+JniInstanceMethods..ctor (System.Type declaringType) [0x00064] in <54816278eed9488eb28d3597fecd78f8>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Java.Interop.JniPeerMembers+JniInstanceMethods.GetConstructorsForType (System.Type declaringType) [0x0002c] in <54816278eed9488eb28d3597fecd78f8>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00032] in <54816278eed9488eb28d3597fecd78f8>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Java.Lang.Object..ctor () [0x00034] in <b45497bae7b44aa5b84d9841d4f92a20>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Microsoft.AppCenter.Crashes.AndroidCrashListener..ctor (Microsoft.AppCenter.Crashes.PlatformCrashes owner) [0x00000] in <d3350e6250834260a1674c2436994900>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Microsoft.AppCenter.Crashes.PlatformCrashes..ctor () [0x00006] in <d3350e6250834260a1674c2436994900>:0 
12-17 17:14:43.165 I/MonoDroid(30427):   at Microsoft.AppCenter.Crashes.Crashes..cctor () [0x0000a] in <d3350e6250834260a1674c2436994900>:0 
12-17 17:14:43.166 I/MonoDroid(30427):    --- End of inner exception stack trace ---
12-17 17:14:43.166 I/MonoDroid(30427):   at System.Reflection.MonoProperty.StaticGetterAdapterFrame[R] (System.Reflection.MonoProperty+StaticGetter`1[R] getter, System.Object obj) [0x00000] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x0005f] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-17 17:14:43.166 I/MonoDroid(30427):    --- End of inner exception stack trace ---
12-17 17:14:43.166 I/MonoDroid(30427):   at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00073] in <657aa8fea4454dc898a9e5f379c58734>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at Microsoft.AppCenter.AppCenter.GetServices (System.Collections.Generic.IEnumerable`1[T] services) [0x00029] in <42dc73f55eb143199a75bb5cc912fc22>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at Microsoft.AppCenter.AppCenter.PlatformStart (System.String appSecret, System.Type[] services) [0x00026] in <42dc73f55eb143199a75bb5cc912fc22>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at Microsoft.AppCenter.AppCenter.Start (System.String appSecret, System.Type[] services) [0x00000] in <42dc73f55eb143199a75bb5cc912fc22>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at EezyFile.Android.Activities+MainActivity.OnCreate (Android.OS.Bundle b) [0x00254] in <5a3689a7d5753712a7450383a789365a>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
12-17 17:14:43.166 I/MonoDroid(30427):   at (wrapper dynamic-method) System.Object:e1c632c1-c5e4-4f9b-9203-120f508a4778 (intptr,intptr,intptr)
```

**Comment by guperrot** [comment]
It could be caused by "Link All" build option or Proguard or both, are you using any of those?

**Comment by guperrot** [comment]
Hi @varon @KhuongNtrd, can you please reply to the previous questions? If no news I will close the ticket.

**Comment by alexanderhanssen** [comment]
I'm getting the exact same exception. Linking is set to Sdk Assemblies only, i haven't enabled ProGuard or Multi-Dex. 
I installed the Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes packages for both core and android project, and put the AppCenter code in the core projects Application.xaml.cs. When i checked if all the packages were installed, i noticed that that the Microsoft.AppCenter packages wasn't installed into the core project, so i did so. This didn't help, so i tried to put the AppCenter start code into the MainActivity.cs in the android project, but this gave me the same exception as when trying to initialize from the core project.

**Comment by KhuongNtrd** [comment]
I'm trying port current Xamarin Android project to new project template with Visual Studio 15.5, reinstall nuget and now it work without Multi-Dex.

**Comment by alexanderhanssen** [comment]
Only adding the Analytics service and dropping the Crash service made my app start normally. Might be something with AndroidCrashListener.cs?

**Comment by KhuongNtrd** [comment]
@alexanderhanssen have you tried remove  bin and obj folder

**Comment by alexanderhanssen** [comment]
@KhuongNtrd Hmm that seemed to do the trick, thanks!

**Comment by guperrot** [comment]
So this is just another clean build issue?

**Comment by guperrot** [comment]
If this is a stale build issue, we will document the full clean in troubleshooting (clean solution will usually not clean some bin/obj folders and have to be removed manually to actually clean). Can you confirm full clean was the only thing you changed since creation of the issue? @alexanderhanssen

**Comment by alexanderhanssen** [comment]
Sorry for the late reply @guperrot, a manual clean of obj and bin folders was the only thing that i did. I got it working when i didn't reference Crash in the startup code also.

**Comment by guperrot** [comment]
Ok thanks for the feedback.
