### ISSUE TITLE
AppCenter doesn't send data to server when on Release config (Xamarin.Forms on Android)

### ISSUE THREAD

**Issue by luccasclezar** [Microsoft/AppCenter-SDK-DotNet#567]
I have a Xamarin.Forms app and when I'm using with Debug configuration, it works as it should, but when I try to test it using Release, it doesn't send anything.

To understand the problem I set the LogLevel to Verbose and here's what I noticed:

- It shows the message "App Center SDK configured successfully"
- It shows the Active Network Info right with "state: CONNECTED"
- Then after "onActivityResumed" it shows another Active Network Info that says that the type of my connection is "VPN[]" and the state is "DISCONNECTED" with reason "(unspecified)".
- After that message it says "Network is down. Pausing 0 network calls".
- Then, when it tries to send the persisted data to server, it says "Call triggered with no network connectivity, waiting network to become available...".
- And when AppCenter tries to send new data to server, it shows the message "Already sending 3 batches of analytics data to the server.".

[log.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/1603712/log.txt)

After examining the logs, I tried to run a Packet Capture app and see if any connection is actually being made, and when I did the exact same thing than before but capturing the packages, the data was sent to the servers.

I reproduced this some times to be sure and every time was the same thing, if I run my app alone, no data gets sent, but when I run it capturing the packets, it works as expected.

**Comment by luccasclezar** [comment]
Apparently it was Android's problem, I rebooted the device and now it's working as expected.

Sorry for opening this issue before trying that.

**Comment by guperrot** [comment]
Hi, the SDK was thinking the network was unavailable and that's why no packet was sent.
We are also in the process of updating the implementation of network up/down detection to be more reliable on Android 5+ by using the network callback APIs.
