### ISSUE TITLE
Ability to defer registering for notifications on iOS

### ISSUE THREAD

**Issue by cbartonnh** [Microsoft/AppCenter-SDK-DotNet#589]
It is very common for an application to provide an onboarding carousel or other guidance to the user to improve the chances of them opting into push notifications.

By requiring that all the services be started at once, there is no way to start crash reporting and analytics at an appropriate time while still being able to prompt the user prior to the OS-provided prompt to be displayed.

I would propose an info.plist flag to defer the call to RegisterForRemoteNotifications() similar to AppCenterAppDelegateForwarderEnabled and provide a method to be called later such as Push.Register().

I hope that makes sense. Would this be something that would be acceptable if a pull request were to be generated?

**Comment by guperrot** [comment]
Hi, such a change should be discussed with @elamalani.

In the mean time, nothing forces you to `AppCenter.Start` all modules at once. You can make single calls to service such as `AppCenter.Start(typeof(Push))` later in the lifecycle of your application for first time launch.

**Comment by achocron** [comment]
The Apple SDK is located [here](https://github.com/Microsoft/AppCenter-SDK-Apple), by the way

**Comment by cbartonnh** [comment]
That is not what the SDK doc states in the Xamarin.ios section. If the doc is incorrect then I should be all set.

**Comment by guperrot** [comment]
The docs are not incorrect, the docs are only a getting started for the most simple case and do not cover splitting start calls into multiple calls. But it's actually possible to start a module later as a separate call (without the app secret though the second time).

**Comment by cbartonnh** [comment]
Sorry, I was going by this (and the similar paragraph in native iOS) found here https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin:

Note that, unless you explicitly specify each module as parameters in the start method, you can't use that App Center service. In addition, the start() API can be used only once in the lifecycle of your app – all other calls will log a warning to the console and only the modules included in the first call will be available.

I will give it a try to see what happens.

Thanks again.

Carl

**Comment by cbartonnh** [comment]
I tried what you said and it definitely seems to work. I think that makes my issue null and void. I will update it with the resolution.

**Comment by guperrot** [comment]
Ok the wording should be improved, but there are 2 different start API signatures, 1 with app secret (the one covered in docs which work only once) and 1 without app secret (which works once per different module). They have the same name but are actually 2 different APIs given the signature is different (no app secret vs app secret).

**Comment by guperrot** [comment]
There is also a Configure method that takes only the app secret and no module.
Start(appSecret, modules) is really a shortcut for Configure() then Start(module)

**Comment by cbartonnh** [comment]
Great. Thanks again for the help. I really appreciate it.

**Comment by guperrot** [comment]
Sure, thanks for using App Center.
