### ISSUE TITLE
Not seeing any events in the events tab of a crash report

### ISSUE THREAD

**Issue by nathanielcook** [Microsoft/AppCenter-SDK-DotNet#598]
I thought events were supposed to be like breadcrumbs for a crash report. I see events in Analytics-Events (and also I see them in Log Flow), but I don't see any events showing up in Crashes-Group-Report-Events. I just see

> Collecting data…
If you don’t see any logs here after a few minutes, please ensure your app has the App Center Analytics SDK installed.

Is there something else I need to do? I can't find any additional steps in the documentation. Seems like it ought to work.

**Comment by guperrot** [comment]
In practice it takes half an hour after event is seen in dashboard to work on crash.

**Comment by nathanielcook** [comment]
Ok, I thought perhaps it wasn't a supported portal feature yet, like [used to be the case with attachments](https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/119). I will reach out to support. Closing this issue.
