### ISSUE TITLE
Analytics - Xamarin.Android Class not found

### ISSUE THREAD

**Issue by cyrilcathala** [Microsoft/AppCenter-SDK-DotNet#603]
Hi,

I have an issue with the Analytics package (v1.4.0) for Xamarin.Android. 
When I launch the app, I get this exception:

Unhandled Exception:
Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/appcenter/analytics/channel/SessionTracker;

I have no linking and no AOT enabled, and no issue with iOS, it works fines.
If I exclude Analytics and only include Crashes, it works fine.

Is it a known issue?

----------------------
Full stack trace:

02-20 09:39:41.571 E/AndroidRuntime(31758): FATAL EXCEPTION: AppCenter.Looper
02-20 09:39:41.571 E/AndroidRuntime(31758): Process: fr.company.app, PID: 31758
02-20 09:39:41.571 E/AndroidRuntime(31758): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/appcenter/analytics/channel/SessionTracker;
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at com.microsoft.appcenter.analytics.Analytics.applyEnabledState(Analytics.java:444)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at com.microsoft.appcenter.AbstractAppCenterService.onStarted(AbstractAppCenterService.java:193)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at com.microsoft.appcenter.AppCenter.finishStartServices(AppCenter.java:565)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at com.microsoft.appcenter.AppCenter.access$400(AppCenter.java:51)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at com.microsoft.appcenter.AppCenter$5.run(AppCenter.java:549)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at android.os.Handler.handleCallback(Handler.java:751)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at android.os.Looper.loop(Looper.java:154)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-20 09:39:41.571 E/AndroidRuntime(31758): Caused by: java.lang.ClassNotFoundException: com.microsoft.appcenter.analytics.channel.SessionTracker
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	... 9 more
02-20 09:39:41.571 E/AndroidRuntime(31758): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/appcenter/channel/AbstractChannelListener;
02-20 09:39:41.571 E/AndroidRuntime(31758): 	... 9 more
02-20 09:39:41.571 E/AndroidRuntime(31758): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.microsoft.appcenter.channel.AbstractChannelListener" on path: DexPathList[[zip file "/data/app/fr.company.app-1/base.apk"],nativeLibraryDirectories=[/data/app/fr.company.app-1/lib/arm, /system/fake-libs, /data/app/fr.company.app-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
02-20 09:39:41.571 E/AndroidRuntime(31758): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by MatkovIvan** [comment]
Hi,

Thanks for getting in touch.
Please answer questions below to help us clarify the problem.
1. Do you use ProGuard?
1. Is it happens only on `1.4.0`? Which version do you use before?
1. Have you tried to clean the solution and remove all `bin`/`obj` folder?

At the moment, I'm inclined that this is just some build cache problem, so (3) should help in this case. Please let me know if this helps or does not help you.

Best,
Ivan

**Comment by cyrilcathala** [comment]
Thanks for the quick answer :)

To answer you :
- I don't use ProGuard.
- I've introduced Analytics recently, never used before. I tried with 1.3.0, same issue.
- Yes, I manually deleted all bin/obj folders before testing.

**Comment by MatkovIvan** [comment]
Personally, I couldn't reproduce this issue on `Xamarin.Forms` and `Xamarin.Android` sample projects.
But I see mention of `com.microsoft.appcenter.channel.AbstractChannelListener` class in your stack trace. This class was introduced some time ago and should come from AppCenter core library (all modules like Analytics and Crashes depends on it).
My other assumption: the old version of core library is used in your application.

So, could you please:
1. Check out that versions of all AppCenter libraries are equal.
1. Specify what project type do you use? (`Xamarin.Forms` with shared/PCL/.NET Standard library or just `Xamarin.Android`).
1. Try to reproduce it in [our demo app](https://github.com/Microsoft/AppCenter-SDK-DotNet/tree/master/Apps/Contoso.Forms.Demo) or just blank app. It helps us to figure out this is project setup problem or something else.

It would be great if we can get the reproduction steps.

Thanks,
Ivan

**Comment by cyrilcathala** [comment]
1. Yes everything is 1.4.0 (AppCenter + Analytics + Crashes in my case)
2. Xamarin.Forms + .NET Standard
3. I could not reproduce the issue with the demo app. I've replaced the PCL with .NET Standard and matched build options with my project, no luck so far ... :(

**Comment by guperrot** [comment]
To help you on that we will need your sources as the problem seems very specific to your project and got no similar report.

**Comment by guperrot** [comment]
Hi, we have not heard from you since last answer. We will need project sources that trigger the problem to be able to reopen this ticket and work on this as we can't reproduce the issue.
