### ISSUE TITLE
It should be possible to group apps under ./Applications

### ISSUE THREAD

**Issue by pfaucon** [Microsoft/AppCenter-SDK-DotNet#617]
We are producing an app that is effectively whitelabeled, so for each client we have at least 2 entries (iOS and Android).  It would be nice to enable a feature grouping the entries by app or with arbitrary folders.

**Comment by elamalani** [comment]
@pfaucon Could you help me understand your use case in detail? Are you creating two different apps in App Center - one for Xamarin iOS and another for Xamarin Android and would like to have both the apps grouped together?

**Comment by pfaucon** [comment]
So our specific use case is that we have app X but branded for clients 1, 2, 3... 10'ish.  The code is mostly the same so testing isn't a big concern, but we like to have the error tracking and usage separated out.  This creates 20 "apps" when really it could be 1 folder with the 20 entries inside.  Our current approach is just to prefix each of them with the same name ("X client1 iOS", "X client1 Android"), so that are at least grouped. This isn't a major problem, but it constrains our naming (and could be a problem if we add another client later and don't pay attention to the naming), and it floods the UI with about 2 pages of just the one app.

For our specific use case another solution might be to be able to group by GitHub repository (since all of our "apps" are different build configurations from the same repository).

**Comment by elamalani** [comment]
@pfaucon We have heard about this feature ask from our customers and it's in our backlog to support it. Unfortunately, there is no ETA on this feature as it's not prioritized yet.

Since we are already tracking this feature at a product level rather than SDK, I suggest to close this issue for now. We will reopen it again once we actively start working on it in App Center. Thanks!
