### ISSUE TITLE
getting help

### ISSUE THREAD

**Issue by amccorma** [Microsoft/AppCenter-SDK-DotNet#618]
How do I open a support ticket?

I clicked the blue chat thing in appcenter and waited 2 hours to be ignored.  My messages are "seen", but no one answers.  Can I email someone and get help?   I do not have 2 hours, going on to 3 hours to wait for someone to answer the blue button to talk to someone.

**Comment by elamalani** [comment]
@amccorma Our support team takes a look at intercom tickets on a first-come, first-serve basis. We should be responding to your question soon. Thanks!

**Comment by joemellin** [comment]
@amccorma could you let me know your App Center username or email me at joemel @ microsoft dot com?

**Comment by amccorma** [comment]
I understand first come first served but having the chat window open for 3 hours waiting is long. I see my message change from unread to read but zero replies. 

My username is psea.mobile@gmail.com or you can email me at amccormack@psea.org. i send you an email from @psea.org

**Comment by joemellin** [comment]
Hey @amccorma We responded to your message an hour ago to your gmail.com address.  Can you check your spam filter?

**Comment by guperrot** [comment]
Hi, it seems like your ticket was handled on other support channels, we shall close this one here. Thanks for using App Center.
