### ISSUE TITLE
Xamarin.iOS crashes aren't sent

### ISSUE THREAD

**Issue by Muthukumar1393** [Microsoft/AppCenter-SDK-DotNet#621]
I'm able to see errors logs  in my app center portal which are the exceptions i catched manually using the statement  " Crashes.TrackError ()" . But for app crashes there is no log feed is available in the app center portal . is there anything am missing ?.

**Comment by elamalani** [comment]
@Muthukumar1393 Please follow our troubleshooting guidelines to make sure that the Crashes SDK is setup correctly in your application.
https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin#crashes-dont-show-up-in-the-portal

**Comment by Muthukumar1393** [comment]
yeah tried with all the steps given in API documents, but it didn't turn up with results.  facing the issue as like https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/583 normally. my app get launched without any delay, but still am facing the same.

**Comment by jwallra** [comment]
I can dig a bit deeper into your issue if you would send the verbose logs from your application.  Just set `AppCenter.LogLevel = LogLevel.Verbose;` before you call `AppCenter.Start("{Your App Secret}", typeof(Crashes));` (which should be somewhat similar to what you are using already!).

**Comment by jwallra** [comment]
It's been a few days; feel free to reopen if you're still having issues.
