### ISSUE TITLE
Property event length 125 characters

### ISSUE THREAD

**Issue by MikaTas** [Microsoft/AppCenter-SDK-DotNet#657]
1.6 release notes..
Analytics
[Improvement] Analytics now allows a maximum of 20 properties by event, each property key and value length can be up to 125 characters long.

Each property value length was max 255 character before. Why go less and is that improvement?

**Comment by MatkovIvan** [comment]
Hi @MikaTas 

Thanks for getting in touch.
It was `64`, not `255`. Thus, we've **increased** the maximum length.
The maximum length of the event **name** hasn't been changed.

See https://github.com/Microsoft/AppCenter-SDK-DotNet/pull/635/commits/cd75c6b791decf711bf3cce7c13e42031b055ee1

Best,
Ivan

**Comment by MikaTas** [comment]
ah, understand. thanks for clarifying it.

**Comment by MatkovIvan** [comment]
You are welcome
