### ISSUE TITLE
Cant use Analytics from NetStandard2.0

### ISSUE THREAD

**Issue by rido-min** [Microsoft/AppCenter-SDK-DotNet#676]
I'm using AppCenter.Analystics in my UWP app. The app references a NetStandardLibrary and I'd like to add some telemetry events from that library.

When I add the NuGet Package I see a warning in the NuGet node, and then the types are not resolved.

Is there anything special to consume Analytics from NetStandard?

**Comment by rido-min** [comment]
Cant repro with latest version 1.6.1

**Comment by guperrot** [comment]
Hi, glad the issue was fixed for you with the latest package.
