### ISSUE TITLE
Ability to set or reset the session id manually.

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [microsoft/appcenter-sdk-dotnet#682]
I want to be able to set/reset the session id manually as this makes sense for our application in terms of trimming our crash report bread crumbs i.e. attaching them for a specific user-flow as our app is an always running kiosk type app.

**Comment by guperrot** [comment]
Hi, even if the process is not killed, the sdk resets session id if the app was in background for more than 20 seconds (the check is done after you resume the app). Is your app always in foreground with screen never turning off?

**Comment by AnastasiaKubova** [comment]
Hi there! The feature [has been released](https://github.com/microsoft/appcenter-sdk-dotnet/releases).
