### ISSUE TITLE
Ability to set the UserId or session meta data.

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [microsoft/appcenter-sdk-dotnet#683]
I want to be able to manually set the user id to something more app/user domain specific so that I can future proof for when error and crash report log searching becomes available (e.g. how Hockey app meta was searchable)

**Comment by blparr** [comment]
Hello, thanks for your feedback!
We are currently looking into the requirements to support User ID. Unfortunately, we don't have an ETA for it yet.

**Comment by blparr** [comment]
Hello @Dexyon ! Great timing for your question - In this month's release, you will be able to set user ID for native SDKs!

We are also working on adding it for cross platforms SDKs as we speak, but we are not 100% confident that it will make it for this month's release (worst case it will be live in the next month's release).

**Comment by Dexyon** [comment]
@blparr Thanks for the response. I assume it is now in the 1.13 release on NuGet? Personally I find it a bit difficult to find the changes in the NuGet package directly. Now that I have found this repo I can look up what changes were made, however from the NuGet package there are no changes mentioned or a link to this repo. 

Maybe something that could be improved by simply linking to this repo or mentioning the changes there as well..?

**Comment by blparr** [comment]
Thanks for the feedback and the suggestion.

Also, as a reference, we always put our updates here: https://docs.microsoft.com/en-us/appcenter/general/changelog

For this specific feature, we also added a banner in the Diagnostics overview with a link to our docs: https://docs.microsoft.com/en-us/appcenter/diagnostics/features

Thank you!
