### ISSUE TITLE
[iOS] Exception at start : Attempting to JIT compile method

### ISSUE THREAD

**Issue by quentinR0bert** [Microsoft/AppCenter-SDK-DotNet#688]
### **Description**

Exception at the initialization of Microsoft.AppCenter on iOS Project.

"Attempting to JIT compile method 'Bill.Services.CrashesMonitorService:Initialize ()' while running in aot-only mode."

The Bill.Services.CrashesMonitorService:Initialize() only contains :

`AppCenter 
                .Start($"ios={iOsMobileCenterKey};android={AndroidMobileCenterKey}",
                 typeof(Analytics), typeof(Crashes));`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Upgrade of Microsoft.AppCenter.Crashes 1.2.0 to 1.6.1
2. Call AppCenter.Start in the OnStart Method of App (Forms project)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms on all 2 platforms (Android and iOS).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - NET standard 2.0.
2. Which SDK version are you using?
    - 1.6.1
4. Which OS version did you experience the issue on?
    - iOS 11
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Iphone 7

**Comment by TroubleMakerBen** [comment]
Hi @quentinR0bert,

Thx for getting in touch. I'm not able to reproduce the issue that you are seeing but on investigation. The error you are seeing might be related to a compiler setting in your project. Can you try to following things:
1. Initialize the App Center SDK directly in `onStart()` without the wrapper? If this works, it might be an issue in your compiler settings used for the package of `Bill.Services.CrashesMonitorService`.
2. Can you make sure to clean Xamarin's cache? Maybe one of the old nugets is still in cache somewhere?

If this does not solve the issue, please provide your build output. If you'd like to continue this conversation in private, please get in touch through intercom (blue button on App Center portal) and mention this GH issue and that you've had a conversation with me (Benjamin Scholtysik) and we can chat over there.

**Comment by quentinR0bert** [comment]
Hi @TroubleMakerBen ,

So i tried again after delete the output folders and restore NuGet packages. 
It's all fine.

So....sorry for this issue ^^"

**Comment by TroubleMakerBen** [comment]
Don't be sorry @quentinR0bert, I'm happy to help. Thx for using App Center!
