### ISSUE TITLE
AppCenter can push to new Android install using the old install identifier

### ISSUE THREAD

**Issue by almirvuk** [Microsoft/AppCenter-SDK-DotNet#699]
### **Description**

I am using `VS App Center` as a service for sending push notifications from backend to mobile devices, in one of my apps, after few days of testing process I found out that there is maybe a major issue with current usage of `AppCenter.GetInstallIdAsync()` method and VS App Center mechanism of sending push notifications to devices. 

### **Repro Steps**

Steps used to reproduce this issue.

1. **"User A"** installs our XF app on his mobile device, called **Device XYZ**.
2.  Using `AppCenter.GetInstallIdAsync()` app/device will get `Install-Id`.
3. We can save `Install-Id` for later usage.
4. **"User A"** will do sign-in to authenticate with backend service.
5. `Install-Id` from device will be mapped to that user and saved on our backend database.
6. Now we can use that `Install-Id` to send specific/targeted push notifications to our **"User A"** from our backend using `VS App Center REST API` and everything will be OK and working.
7. **"User A"** will do sign-out at some point, during sign-out process, we will handle the logic for sign out, we can disable push notifications from our backend by removing that `Install-Id`, and after that he will not get any specific/targeted push notifications because he is signed-out from our app on his device.
8. Still everything is Ok, but in few future steps situation can be problematic.
9. "**User A"** have our app installed on his **Device XYZ**, he is using is as anonymous user (which is a valid state).
10. His friend **"User B"** borrows  **Device XYZ** from **"User A"** and do sign-in, steps are reproduced. Now **"User B"** is mapped to that device on our backend, we have `Install-Id` from that device and future notifications will be sent to **"User B"**, at that moment he is using that **Device XYZ**.
11. After some time he decide to return **Device XYZ** to **"User A"** which is the real owner of it, without sign-out process, he will just do uninstall of the app from **Device XYZ** and return it to **"User A"** (original owner).
12. **"User A"** will install app on his **Device XYZ** again, he will get **new** `Install-Id `from VS App Center, which will be different from previous one.
13. **"User A"** will do sign-in to authenticate with backend.
14. ` Install-Id` from device will be mapped to that user and saved on our backend.
15. Backend will start sending push notifications using `VS App Center REST API`, and it will use `Install-Id`s which are mapped to our users.

16. Now, we have that weird behaviour, backend will start sending push notifications, **"User A"** owner of **Device XYZ**, will get push notifications which are specific to **"User A"** (✔️ ) and notification which are specific to **"User B"** (⚠️), which is a huge problem!

This was longer list of steps but I think this is a **major** issue.

**Conclusion:**

Reason for this weird and problematic behaviour is because we have `Install-Id` from previous app installation which was not cleared on our backend, because **"User B"** did not do sign-out... and big problem here is that one device can have multiple `Install-Id`, which are somehow all valid for `VS App Center` at the same time, even though we are getting new one using `AppCenter.GetInstallIdAsync()` after uninstall. 

We can also send push notifications using old ones which are stored in database of backend service or somewhere else.

Maybe this scenario is weird but in some cases it is very possible, for example : "Hi, can you borrow me your device, just to check something ... (they are both users of our product)...".

I want to hear what do you think about this, am I missing something here or?

If you ask me the major issue is that we are able to send/recieve push notification using Install-Id which is "old", one device had multiple app installations and every time we get new Install-Id, but somehow old ones are also valid.

With standard **sign-in/sign-out** we can handle mapping our user to `Install-Id` without any problem, but if sign-out is somehow missing in that process we have a problem. Common one will be uninstalling the device.

I have some solutions in my mind, but they are not quite clean solutions for this problem.

Please can you review this and give your opinion on this issue.

Thanks! 

Best regards! 🙂 

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms on all 3 platforms (Android, iOS and UWP).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 1.4.
2. Which SDK version are you using?
    - 1.7.0
4. Which OS version did you experience the issue on?
    - iOS 11 and Android 8.1.0, UWP 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Doesn't matter, all devices
6. What third party libraries are you using? 
    - Doesn't matter, it is a general bug
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
   - Doesn't matter, it is a general bug

**Comment by guperrot** [comment]
# Android

The native push token (called registration identifier by Google) that is coupled with the installId is often valid even after uninstall/reinstall.

If the push service accepts the push command to the old push token (and it almost always does according to our tests), then we have no way to know it's from a previous install as we cannot handle uninstall information from devices. The only way push token is invalidated is when you pushed between uninstall and reinstall (or if token old enough).

In the next version of our Android SDK we have to make Firebase Push SDK mandatory instead of using an old push registration mechanism (because of Android P that removed the old registration mechanism we were using and because of [this announcement](https://firebase.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html)).

When Firebase Push SDK is used as a dependency by our upcoming SDK for getting push token, then uninstalling the app invalidates the push token correctly so this scenario will be solved by updating the SDK and doing the migration steps that will be documented soon.

# Apple and UWP

Uninstall is already invalidating the push tokens so this scenario cannot happen on those platforms. You might still see 1/1 sent the first time but the push will not be delivered, if you try again you will see 0/1 and an expired channel error on the App Center portal.

**Comment by almirvuk** [comment]
Ok, thank you for your quick response. :)

Hope that next version of Android SDK will be available soon.

**Comment by TroubleMakerBen** [comment]
We're on a monthly release schedule and plan to have the next version out next week!

**Comment by almirvuk** [comment]
Nice to hear that! 🙂

**Comment by guperrot** [comment]
This should be fixed by updating Nugets to 1.8.0 then following https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/xamarin-android.
