### ISSUE TITLE
Windows Desktop Issue / Support

### ISSUE THREAD

**Issue by StefanKoell** [Microsoft/AppCenter-SDK-DotNet#707]
Hi!
 
I desperately need some help.
 
Someone at MS suggested to use the following package where WPF/WinForms would work:
https://www.nuget.org/packages/Microsoft.AppCenter/1.0.2-r0004-e44d856

I use this one in my WinForms app and use Analytics only. This all works great and I was able to implement all I needed.
 
Now I'm in the final phase and need to deploy my app to my users. There I found out that the library is writing some files to the app directory (like AppCenter.config or some temp files). Unfortunately my app installs to Program Files x86 where the user does not have write permissions.
 
I tried to pull in the source from the git hub or even tried to decompile the nuget binaries in hope to tweak the path those files were written to. Unfortunately this all failed.
 
The only thing preventing my release is this small tweak. Maybe you can tell me what branch / commit id the 1.0.2-r0004 nuget package corresponds to, so that I can pull this version from github and tweak the path myself. 

I'm really desperate here. Any help would be very much appreciated!
 
Thanks, 
Stefan

**Comment by achocron** [comment]
Discussion moved offline
