### ISSUE TITLE
How to handle notification when Android running in background mode

### ISSUE THREAD

**Issue by kritsadadechawantana** [microsoft/appcenter-sdk-dotnet#708]
How to trig PushNotificationReceived when Android running in background mode like content-available in iOS

**Comment by guperrot** [comment]
Hi this is currently not supported.

**Comment by kritsadadechawantana** [comment]
Thanks for your answer :)

**Comment by raver99** [comment]
Technically, you could create your own Receiver to intercept the background push and then delegate to the AppCenter [PushReceiver](https://github.com/microsoft/appcenter-sdk-android/blob/develop/sdk/appcenter-push/src/main/java/com/microsoft/appcenter/push/PushReceiver.java), right?

**Comment by AnastasiaKubova** [comment]
Hi, @raver99. Yes, it’s possible since that’s what we do in android native SDK. But we don't support this case for now for Xamarin SDK.

**Comment by guperrot** [comment]
To clarify the receiver in the native SDK detects that Firebase is used and will thus let Firebase generate notifications on background and thus has nothing more to do. So we don't support relaying the background notifications today on native SDK via a listener. The Xamarin code simply wraps the Java receiver and thus relies on its behavior.

But in the meantime yes, a receiver can be used in the app code to work around the missing feature.

**Comment by AnastasiaKubova** [comment]
Hi there!
The App Center Push module has been removed from App Center SDK in the [4.0.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.0.0) version so we are closing this feature request.

As an alternative to App Center Push, we recommend you migrate to [Azure Notification Hubs](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-overview) by following the [Push Migration Guide](https://docs.microsoft.com/en-us/appcenter/migration/push/).
