### ISSUE TITLE
Distribute - Not working on Samsung browser

### ISSUE THREAD

**Issue by spixy** [microsoft/appcenter-sdk-dotnet#719]
### **Description**

App distribution is not working through *Samsung browser* on Android.

### **Repro Steps**

1. set *Samsung browser* as default browser on Android
2. open email that informs that new version of application is available
3. click on *Install* button inside email

### **Details**

Xamarin.Android 8.3.3.2, Xamarin.Android.Support 27.0, Xamarin.Forms 3.1 (.NET Standard 2.0), 
AppCenter 1.8.0

**Comment by guperrot** [comment]
Closing this one as Distribute no longer enforces Google Chrome browser. Please reopen if any issue with the latest version.
