### ISSUE TITLE
Distribute - Stop opening browser on app start

### ISSUE THREAD

**Issue by spixy** [Microsoft/AppCenter-SDK-DotNet#720]
### **Description**

Please stop opening browser on every app start when using AppCenter.Distribute on Android.
After day of use of my app I have in browser many tabs that I have to close.

### **Details**

Xamarin.Android 8.3.3.2, Xamarin.Android.Support 27.0, Xamarin.Forms 3.1 (.NET Standard 2.0), 
AppCenter 1.8.0

**Comment by guperrot** [comment]
Hi, this is because of #719 where we support only Google Chrome. If we cannot get a success or failure from Google Chrome then we have to retry next time. Thus this issue is the same as #719, let's track the discussion there.
