### ISSUE TITLE
"Silent" Push for Android

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [microsoft/appcenter-sdk-dotnet#741]
### **Description**

Currently App Center iOS push supports silent notifications but Android does not (Android shows a notification if the app is in the background and only has "silent" push if the app is in the foreground). 

However silent push notifications should now be possible with Firebase: https://stackoverflow.com/questions/36555653/push-silent-notification-through-gcm-to-android-ios

**Comment by TroubleMakerBen** [comment]
Hi @Steven-Mark-Ford,

we are tracking this as a feature request on our backlog but I cannot provide any info on when or if we are adding support for silent push on Android at this moment.

**Comment by nbsoftware** [comment]
If I may add, this one is very much needed here also!
Would there be any workaround in the meantime? (I'm afraid not....)

**Comment by guperrot** [comment]
Today there is no work around using the App Center Portal or API as the message field is mandatory in App Center.

**Comment by nbsoftware** [comment]
Now that Firebase dependencies are required again... wouldn't there be a workaround using FCM?
Would `FirebaseInstanceId.Instance.Token` be accessible in any way?

**Comment by elamalani** [comment]
@nbsoftware @Steven-Mark-Ford Thanks for using App Center. We don't plan to support this feature right now but will keep this issue open for visibility and let you know once we decide to work on it in the SDK.

**Comment by pfedotovsky** [comment]
@elamalani any updates on silent pushes for Android?

**Comment by devopsone** [comment]
Also in need pure data notifications or we have to drop AppCenter and switch to something else. So is there any update on this?

**Comment by rheuser** [comment]
What happens to the hockeyApp functions in my WPF app on November 16? Are they just no longer supported or do they stop working? If they will stop working, when do we get App Center support so WPF so that we can transition?

**Comment by rheuser** [comment]
Can I put the App Center SDK into my WPF app and start using custom events now? Or do I have to wait for WPF support in App Center?

**Comment by chris-cubhub** [comment]
We'd also like to have this available. The lack of parity between droid and iOS renders this feature unusable. Has there been any movement on this one by chance? Would be much appreciated.

**Comment by jwargo** [comment]
We have a work item for this, I'm working on getting it onto the backlog.

**Comment by ChrisJAult** [comment]
Is this ever going to be implemented? We are looking at using silent push through AppCenter but cannot progress..

**Comment by jwargo** [comment]
@ChrisJAult Yes.

**Comment by Robelind** [comment]
So, when?

**Comment by DamienDoumer** [comment]
Has this feature been finally planned for ?

**Comment by annakocheshkova** [comment]
Hey, you can track the status of this request [here](https://github.com/microsoft/appcenter/issues/87).

**Comment by annakocheshkova** [comment]
I'm going to close this one as duplicate
