### ISSUE TITLE
In App Updates doesn't work with two different App Center projects but same codebase and bundle identifiers?

### ISSUE THREAD

**Issue by kevinrodriguez-io** [Microsoft/AppCenter-SDK-DotNet#743]
### **Description**

- I have one Xamarin.Forms app for testing
- I have one Xamarin.Forms app for production
- Each one has different Keys
- My app uses the same bundle identifier for both cases.
- I implemented In App Updates successfully on testing
- I'm using the same code base but different app identifiers
- On development(The app we don't intent for production, mostly internal testing) everything works perfectly.
- On production, the app works fine but nothing about in app updates work. The app seems to be working fine tough (I created another version and nothing happened, the app won't even request me to open the safari window on the first time)
- What is happening here? The same code that works with an app doesn't work with the other.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create Xamarin.Forms project
2. Create two projects on AppCenter, one for Internal testing and one for production
3. Implement In App Distribution with Internal testing project's key
4. Deploy to your device using the internal testing app
5. Change the key to production
6. Uninstall your app (Testing)
7. Deploy your proudction app to your device

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - PCL Profile
2. Which SDK version are you using?
    - 1.9.0 (App Center)
4. Which OS version did you experience the issue on?
    - iOS 11.3
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPad 4
6. What third party libraries are you using? 
    <Reference Include="AutoMapper, Version=6.1.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005, processorArchitecture=MSIL">
      <HintPath>..\..\packages\AutoMapper.6.1.1\lib\netstandard1.1\AutoMapper.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AppCenter, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.AppCenter.1.9.0\lib\portable-net45+win8+wpa81+wp8\Microsoft.AppCenter.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AppCenter.Analytics, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.AppCenter.Analytics.1.8.0\lib\portable-net45+win8+wpa81+wp8\Microsoft.AppCenter.Analytics.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AppCenter.Crashes, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.AppCenter.Crashes.1.8.0\lib\portable-net45+win8+wpa81+wp8\Microsoft.AppCenter.Crashes.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AppCenter.Distribute, Version=0.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.AppCenter.Distribute.1.9.0\lib\portable-net45+win8+wpa81+wp8\Microsoft.AppCenter.Distribute.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.OData.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.OData.Core.6.0.0\lib\portable-net40+sl5+wp8+win8\Microsoft.OData.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.OData.Edm, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.OData.Edm.6.0.0\lib\portable-net40+sl5+wp8+win8\Microsoft.OData.Edm.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\CommonServiceLocator.1.3\lib\portable-net4+sl5+netcore45+wpa81+wp8\Microsoft.Practices.ServiceLocation.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Unity.4.0.1\lib\portable-net45+wp80+win8+wpa81+MonoAndroid10+MonoTouch10\Microsoft.Practices.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Spatial, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.Spatial.6.0.0\lib\portable-net40+sl5+wp8+win8\Microsoft.Spatial.dll</HintPath>
    </Reference>
    <Reference Include="ModernHttpClient, Version=2.4.2.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\modernhttpclient.2.4.2\lib\Portable-Net45+WinRT45+WP8+WPA81\ModernHttpClient.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Newtonsoft.Json.8.0.2\lib\portable-net40+sl5+wp80+win8+wpa81\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Plugin.Connectivity, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xam.Plugin.Connectivity.3.0.3\lib\netstandard1.0\Plugin.Connectivity.dll</HintPath>
    </Reference>
    <Reference Include="Plugin.Connectivity.Abstractions, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xam.Plugin.Connectivity.3.0.3\lib\netstandard1.0\Plugin.Connectivity.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Plugin.Media, Version=3.1.2.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xam.Plugin.Media.3.1.2\lib\netstandard1.0\Plugin.Media.dll</HintPath>
    </Reference>
    <Reference Include="Plugin.Media.Abstractions, Version=3.1.2.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xam.Plugin.Media.3.1.2\lib\netstandard1.0\Plugin.Media.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Plugin.Settings, Version=3.1.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xam.Plugins.Settings.3.1.1\lib\netstandard1.0\Plugin.Settings.dll</HintPath>
    </Reference>
    <Reference Include="Plugin.Settings.Abstractions, Version=3.1.1.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xam.Plugins.Settings.3.1.1\lib\netstandard1.0\Plugin.Settings.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Realm, Version=2.1.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Realm.Database.2.1.0\lib\portable-net45+sl5+wp8+wpa81+win8+monoandroid+Xamarin.iOS10+monotouch+Xamarin.Mac\Realm.dll</HintPath>
    </Reference>
    <Reference Include="Realm.DataBinding, Version=1.2.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Realm.DataBinding.1.2.0\lib\netstandard1.0\Realm.DataBinding.dll</HintPath>
    </Reference>
    <Reference Include="Realm.Sync, Version=2.1.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Realm.2.1.0\lib\portable-net45+sl5+wp8+wpa81+win8+monoandroid+Xamarin.iOS10+monotouch+Xamarin.Mac\Realm.Sync.dll</HintPath>
    </Reference>
    <Reference Include="Rg.Plugins.Popup, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Rg.Plugins.Popup.1.0.4\lib\portable-win+net45+wp8+win8+wpa81\Rg.Plugins.Popup.dll</HintPath>
    </Reference>
    <Reference Include="Rg.Plugins.Popup.Platform, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Rg.Plugins.Popup.1.0.4\lib\portable-win+net45+wp8+win8+wpa81\Rg.Plugins.Popup.Platform.dll</HintPath>
    </Reference>
    <Reference Include="SignaturePad.Forms, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xamarin.Controls.SignaturePad.Forms.2.3.0\lib\portable-net45+win8+wp8\SignaturePad.Forms.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\..\packages\System.ComponentModel.Primitives.4.3.0\lib\netstandard1.0\System.ComponentModel.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.TypeConverter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\..\packages\System.ComponentModel.TypeConverter.4.3.0\lib\netstandard1.0\System.ComponentModel.TypeConverter.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http.Extensions, Version=2.2.29.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.Net.Http.2.2.29\lib\portable-net45+win8\System.Net.Http.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http.Formatting, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.AspNet.WebApi.Client.5.2.6\lib\portable-wp8+netcore45+net45+wp81+wpa81\System.Net.Http.Formatting.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http.Primitives, Version=4.2.29.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Microsoft.Net.Http.2.2.29\lib\portable-net45+win8\System.Net.Http.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="TW.SP.Encryption">
      <HintPath>Dll\TW.SP.Encryption.dll</HintPath>
    </Reference>
    <Reference Include="Xamarin.Forms.CarouselView, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xamarin.Forms.CarouselView.2.3.0-pre2\lib\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.CarouselView.dll</HintPath>
    </Reference>
    <Reference Include="Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xamarin.Forms.2.4.0.282\lib\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.Core.dll</HintPath>
    </Reference>
    <Reference Include="Xamarin.Forms.Platform, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xamarin.Forms.2.4.0.282\lib\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.Platform.dll</HintPath>
    </Reference>
    <Reference Include="Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Xamarin.Forms.2.4.0.282\lib\portable-win+net45+wp80+win81+wpa81\Xamarin.Forms.Xaml.dll</HintPath>
    </Reference>
    <Reference Include="Xamarin.iOS">
      <HintPath>..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Xamarin.iOS.dll</HintPath>
    </Reference>
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by TroubleMakerBen** [comment]
Hi @kevinrodriguez-io,

thx for getting in touch and providing all the information above. From what you are writing, It's not entirely clear to me what you are trying to achieve.

>Create Xamarin.Forms project
Create two projects on AppCenter, one for Internal testing and one for production
Implement In App Distribution with Internal testing project's key
Deploy to your device using the internal testing app

By "internal testing app", are you referring to the [Android app for App Center](https://blogs.msdn.microsoft.com/vsappcenter/how-and-why-we-built-our-new-visual-studio-app-center-tester-apps-preview-now-available/)?

>Change the key to production
Uninstall your app (Testing)
Deploy your proudction app to your device

I understand that you are testing the "Testing" builds and in-app-updates work just fine. You then uninstall the "Testing" build and install the "Production" one. And you are saying that you don't get in-app-updates for the next "Production" build?

Can you enable verbose logging as described in the last step of the issue template, please, distribute a production build, install it, and share the Console output at launch of the app here? If you deploy the production app through App Center, you should see the authentication flow just like for the "Testing" build.

Other pointers that I can think of:
* is the user part of the group or team that is supposed to get the updated build?
* in case you are expecting the "Production" app to receive an update to the "Testing" app because they share the same bundle identifier. (I know, likely not the case, I'm just checking)

**Comment by kevinrodriguez-io** [comment]
> I understand that you are testing the "Testing" builds and in-app-updates work just fine. You then uninstall the "Testing" build and install the "Production" one. And you are saying that you don't get in-app-updates for the next "Production" build?

Yes, that's exactly my issue

I have the following app setup on app center, i'm not using the Android app you mentioned before.

![Projects](https://image.ibb.co/cabWtU/APPS.png)

My code looks like this

![Code](https://image.ibb.co/esGmSp/TSS.png)

I'm not working anymore for today, but i promise i will enable logging tomorrow to see what happens.

- I have one user on one group and the release is intended for that user (Me).

- I'm not expecting the production app to get test updates.

This is what i'm expecting:

- I deploy .ipa on TESTAPP with upgraded number and get In App Distribution popup.

- If I change the code to point to the key for production app, I expect that when I deploy .ipa on PRODAPP with upgraded number, get In App Distribution popup or at least the initial prompt with the Web View.

**Comment by TroubleMakerBen** [comment]
Hi @kevinrodriguez-io,

I looked into this some more today and specifically tried to reproduce you issue with no luck (feel free to check out the sample project that I attached to this response).

There must be something missing when you compile the live/prodution version of the app.
Do you change the app secret in the `AppCenter.start(....)` code as well as in custom URL scheme entry in the `info.plist`?

Without the logs from the Console at app launch for your PRODAPP, it's really hard to tell what's going on.

And just, to make sure, because we've had people asking about it:
>This is what i'm expecting:
>
>I deploy .ipa on TESTAPP with upgraded number and get In App Distribution popup.
>
>If I change the code to point to the key for production app, I expect that when I deploy .ipa on PRODAPP with upgraded number, get In App Distribution popup or at least the initial prompt with the Web View.
>I deploy .ipa on TESTAPP with upgraded number and get In App Distribution popup.

There is no upgrade path straight from TESTAPP to PRODAPP because that's not how in-app-updates work.

Let me know how things go and thanks for using App Center!
[TestInAppUpdates.zip](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2338265/TestInAppUpdates.zip)

**Comment by kevinrodriguez-io** [comment]
Hey guys, someone on the app center support bubble is amazing.

The actual problem was that i forgot to modify the `info.plist` file on the MyApp.iOS  project.

```
<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
        <string>appcenter-KEY-FOR-TESTAPP</string>
				<string>appcenter-KEY-FOR-PRODAPP</string>
			</array>
		</dict>
	</array>
```

Adding both keys to the CFBundleURLSchemes made it work.
