### ISSUE TITLE
[UWP] No compatible with sqlite 1.5.231

### ISSUE THREAD

**Issue by MarMarIV** [Microsoft/AppCenter-SDK-DotNet#753]
### **Description**

After upgrade sqlite and xamarin.forms to latest version, method AppCenter.Start throw exception:

Method not found: 'Void SQLite.SQLiteAsyncConnection..ctor(System.String, Boolean)

### **Repro Steps**

1. NuGet Xamarin Forms 3.2
2. NuGet Sqlite-net-pcl 1.5.231
3. NuGet AppCenter 1.9
4. override OnStart method in App.xaml.cs:

AppCenter.Start(
                   "uwp=...;" +
                   "android=...;" +
                   "ios=...;",
                   typeof(Analytics), typeof(Crashes));

### **Details**

With sqlite-net-pcl 1.5.166-beta it is working

**Comment by dhei** [comment]
Hey @MarMarIV,

Thanks for reporting this issue. Looks like sqlite-net-pcl v1.5.231 has some breaking change in the `SQLiteAsyncConnection` [constructor](SQLiteAsyncConnection) that breaks App Center SDK. (See https://github.com/praeclarum/sqlite-net/issues/751 for users reporting this to sqlite-net-pcl repo).

We are working on a fix and we will share more info when we have the fix. Thanks for the understanding.

**Comment by MatkovIvan** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.

**Comment by MatkovIvan** [comment]
Hi @gmarbury,

The `sqlite-net-pcl` is only used for UWP and does not affect Xamarin Live Player (Android) in any way.

**Comment by guperrot** [comment]
The android and iOS dlls are mostly implemented using bindings to the Java and Objective C SDKs which is considered native code by Xamarin Live Player.
