### ISSUE TITLE
NuGet for AppCenter API

### ISSUE THREAD

**Issue by balivo** [Microsoft/AppCenter-SDK-DotNet#760]
There's no NuGet package for AppCenter API?

NuGet packages allready have is for "client" (receives push, send info for Analytics, take care about Distribution, etc)... AppCenter don't have a NuGet for "server-side" operations (like, send push notifications, etc)... Ok, we have a REST API, but don't have a NuGet for easy setup (plug and play) with it... I thinking about create this package for "server side" AppCenter operations....

**Comment by cleidson** [comment]
I think it's extremely important! would help me a lot in the projects I've been working on.

**Comment by ElektrojungeMS** [comment]
I'm not sure if I understand you correctly
> I thinking about create this package for "server side" AppCenter operations....

Are you looking for a package that allows you to gather telemetry in AppCenter for a web application?
My guess is that you just want to use the App Center REST API for tasks like uploading builds, etc. and we do have a package for you [AppCenter CLI](https://github.com/Microsoft/appcenter-cli). It's an npm package, nut a nuget, though.

**Comment by balivo** [comment]
@ElektrojungeMS I know about AppCenter CLI... Some applications have some "server side" needs (like, send push notifications)... Today I have to implement a AppCenter REST API client, not a "problem" but if we have a NuGet just for "plug and play" the REST API client...

I just ask about it, because if MS have one, I'd just contribute and not create... Ok?

**Comment by MatkovIvan** [comment]
@balivo There is [OpenAPI (Swagger) definition](https://api.appcenter.ms/preview/swagger.json) which can be used for easily generating client library (not only for C#). Is that what you're looking for?

**Comment by clpolet** [comment]
I have the feeling that this is not client SDK related but I might misunderstood. Also @balivo you might take your chance with the support directly from the AppCenter portal, the blue button at the bottom right corner.

**Comment by clpolet** [comment]
@balivo we haven't heard from you for a while I'll go ahead and close this issue. I think @MatkovIvan solution is good. Thanks for using AppCenter!

**Comment by balivo** [comment]
Ok @clpolet I'm making a AppCenter OpenAPI client here: https://github.com/balivo/ms-appcenter-sdk Tks!

**Comment by balivo** [comment]
New, repo... MS brand guidelines: https://github.com/balivo/appcenter-openapi-sdk

**Comment by MatkovIvan** [comment]
Hi @balivo,

It looks like you are trying to implement implement it manually. In the comment above I mean you can **generate** it.

1. Install [AutoRest](https://github.com/Azure/autorest)
2. `autorest --input-file=https://api.appcenter.ms/preview/swagger.json --csharp` (`namespace` and some other things are configurable too)

**Comment by MatkovIvan** [comment]
@balivo https://github.com/balivo/appcenter-openapi-sdk/pull/1 Enjoy 🙂

**Comment by balivo** [comment]
Ow @MatkovIvan Really awesome!

I didn't know AutoRest...

Tks for reference...

As I always say: We have learned a lifetime to die dumb!

Now I'm need get new subjects for my LiveCodes on YouTube! (youtube.com/jbalivo)
