### ISSUE TITLE
Expose device info

### ISSUE THREAD

**Issue by KristofferBerge** [microsoft/appcenter-sdk-dotnet#769]
### **Description**

The SDK contains a Device object containing a lot of info about the device, but I don't see any way to get an instance of it.

Would you consider exposing this?

**Comment by elamalani** [comment]
@KristofferBerge Thanks for using App Center. I agree this API would be useful for developers but we don't have any plan to support it right now. We will keep the issue open for visibility and let you know once we plan to add this API in the SDK.

**Comment by sasivishnu** [comment]
Hi, Any update on this? It will be very nice to get this access to this information. Can we expect some ETA? Thanks.

**Comment by hamswan** [comment]
@sasivishnu we don't have an ETA yet but you can track it through this GitHub request.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
