### ISSUE TITLE
iOS push notification - Appcenter "category"  keyword ignored   

### ISSUE THREAD

**Issue by gunapandianraj** [Microsoft/AppCenter-SDK-DotNet#770]
Unable to send iOS reserved key value pair { "Category" : "value" } for showing custom actions for push notification's. i would like to know is this a limitation in appcenter push or is there any alternate keyword we have to use. 

For now category key value pair is ignored while converting to platform specific payload.

Unable to send "Category" key and its value in push notification payload.

**Comment by dhei** [comment]
Closing this duplicate as we are tracking https://github.com/MicrosoftDocs/appcenter-docs/issues/332 for your question.
