### ISSUE TITLE
Export data to Logstash

### ISSUE THREAD

**Issue by fredeil** [microsoft/appcenter-sdk-dotnet#779]
### Feature request

_(Not sure where this issue should have been created)_

Ops team is having a hard time accepting that we cannot customise the log format.

It would be great to be able to export the BLOB data to [Logtash](https://www.elastic.co/products/logstash) for transforming and aggregating the log data. Today we are exporting data to Azure Blob Storage (via AppCenter Export), downloading it, then transforming it and then sending it to Logstash and then back to Application Insights.

Perhaps there could be an option to transform the log data with a config locally on the devices (with the upcoming pause feature).

**Comment by DmitriyKirakosyan** [comment]
Hi @fredeil ,

I would like to refresh the status of this feature request. Could you please confirm that this request is still valid for you?
Do you think an API for providing a custom logger would resolve the issue for you?

**Comment by fredeil** [comment]
Absolutely. Some way to extract the data without having to use Azure as the middle-man

**Comment by DmitriyKirakosyan** [comment]
Hi there, could you elaborate a bit on this? So you want to capture all AppCenter SDK events which are sending to the App Center backend using Analytics.TrackEvent and Crashes.TrackError and modify the structure/formatting of these events/logs, right? If it is correct, can you provide an example of such transformation which you perform? We have a validation on the backend side, so the log format should conform to a specific format rules so the backend can handle it. 
In this case, you may achieve your goal using the api `SetLogUrl` which you can use to redirect all events to the provided url. In this case you would able to transform the logs on your end and send them to App Insight.

Is that correct? Please let me know if my understanding is incorrect.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue but feel free to reopen if the problem still persists for you.
