### ISSUE TITLE
OnPushNotificationReceived firing twice in iOS

### ISSUE THREAD

**Issue by stesvis** [Microsoft/AppCenter-SDK-DotNet#782]
Only in iOS, the OnPushNotificationReceived event is fitted twice. If i just place an alert in the event, i see it twice, but only once in Android.

What could it be? Some platform specific configuration?

**Comment by ElektrojungeMS** [comment]
Hey @stesvis,

thanks for getting in touch.

Are you aware of this behavior

```
If silent notifications are enabled and you push a notification with content-available: 1, then the event may be triggered twice for the same notification: when the notification is received in background and when it is tapped.
```

that we describe in our [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios#intercept-push-notifications)?

In case you have updated to version **1.11.0**, did you follow the instructions

> If you have implemented this delegate please remove any call to the Push.DidReceiveRemoteNotification method as it's now handled by the new User Notification Center Delegate Forwarder.

that are part of our [release notes](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.11.0)?

If both do not apply, please
* let me know the version of the App Center SDK that you are using?
* set the log level [to verbose](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level), build, install and test while the device is attached to your Mac and share the console output here.

Without a verbose log output from the device (via Console.app), it's next to impossible to understand what's going on on your device.

Best,
Benjamin

**Comment by ElektrojungeMS** [comment]
Hey @stesvis,

we haven't heard from you in a while. I'm closing this issue but please don't hesitate to reopen/comment on it and let us know if you are still seeing this issue.

Thanks for using App Center and have a nice weekend!

Benjamin
