### ISSUE TITLE
Distribute login popup is not disabled

### ISSUE THREAD

**Issue by mamcx** [Microsoft/AppCenter-SDK-DotNet#796]
When the user open the apps with distribute, is requested a login with a popup.

We want to disable that.

I put:

```f#
    override this.FinishedLaunching (app, options) =
        Distribute.SetEnabledAsync(false) |> ignore
```
but it not work.

### **Details**

- Xamarin.Forms on  (Android, iOS).
- .NET standard 2.0.
- SDK 1.9.0
-  iOS 11

**Comment by jaelim-ms** [comment]
How did you start App Center in your app? If your app starts App Center before disabling Distribute, it will show a popup and try to initialize Distribute. Seems your `SetEnabledAsync` call is too late.

**Comment by mamcx** [comment]
I do the `SetEnabledAsync` as the first line after` this.FinishedLaunching` on iOS.

**Comment by ElektrojungeMS** [comment]
Hey @mamcx,

The order should be
* disable App Center Distribute
* start App Center
* this.FinishedLaunching

Best,
Benjamin

**Comment by mamcx** [comment]
I change to:

```F#
    override this.WillFinishLaunching(app, options) =
        Distribute.SetEnabledAsync(false) |> ignore

        AppCenter.Start("ef9...", typedefof<Analytics>, typedefof<Crashes>, typedefof<Distribute>)
        true

    override this.FinishedLaunching (app, options) =
        Forms.Init()
```

With the same result

**Comment by jwallra** [comment]
Hi @mamcx - are you using a private distribution group?  If you are, and your users are downloading for, say, testing purposes, then the login popup is unavoidable.  If you're using a public group, then you should be able to avoid it with your method.

I am also curious what language you're using... I don't recognize it from your code sample, and we don't have any test apps written in languages other than C#.  Did you just write pseudocode?  If so, could you provide the exact code you're using to override the login?

**Comment by guperrot** [comment]
Whether it's a public group or private group, enabling in-app updates requires opening the browser the first time.

If you want to avoid browser opening then in-app updates will not work (this is detailed in the [documentation](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#how-do-in-app-updates-work)).

If there are some situations where you want to delay when that happens, it might be better solution to not use `Distribute.SetEnabledAsync` but instead remove `typeof(Distribute)` from the `AppCenter.Start` call.

You can then call `AppCenter.Start(typeof(Distribute))` later on (without the appSecret the second time you call Start) or not call it if you want to keep it inactive.

**Comment by mamcx** [comment]
The language is F#.

I'm using private groups for managing the devices. Is for a closed beta. I will try the delay.

**Comment by achocron** [comment]
@mamcx Hey have you had any success?

**Comment by mamcx** [comment]
Yes, removing typedefof<Distribute>
