### ISSUE TITLE
WinForms Support Needed

### ISSUE THREAD

**Issue by StefanKoell** [microsoft/appcenter-sdk-dotnet#798]
WinForms github issue has been closed.
WPF github issue is open but no confirmation yet.

We desperately need support for WinForms and WPF apps - at least for the analytics part. How hard can this be. The WinForms code base I got from MS was a private build and nobody cared to publish the source (Open Source?!). Now the code seems to be lost (according to MS). Really?! You can support macOS but not WinForms / WPF?!

Please, please, please!!!

**Comment by achocron** [comment]
Hi Stefan, 
I unfortunately don't have an ETA for official support but it is on our roadmap. We don't have the code we provided you as it was a one-off drop that was specifically for you, but the codebase on the GitHub repository does contain the WPF/WinForms SDKs. If you need to make any changes, you are of course welcome to make a fork to make any changes until we support the platform officially.

The code is found split up among a few folders for each module, but it looks like this:
<img width="1186" alt="screen shot 2019-01-07 at 2 00 25 pm" src="https://user-images.githubusercontent.com/5619585/50854096-fae63d00-1338-11e9-814f-b857431cd26b.png">

- *.AppCenter.Shared contains code for all platforms
- *.Windows.Shared contains code that is shared among all Windows platforms we support (UWP, WPF, and WinForms) and this is where you'll find most of the logic
- *.AppCenter.WindowsDesktop contains the logic that is specific to WPF and WinForms

Let us know if you have any questions.

**Comment by jwallra** [comment]
Please use this thread for WinForms support conversation going forward, and refer to #620 for WPF comments.

**Comment by MatkovIvan** [comment]
Hi there!

AppCenter .NET SDK with WPF/WinForms support ([`2.2.1-preview`](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/2.2.1-preview)) is released. We would appreciate it if you give us some feedback, so please check it out!

**Comment by guperrot** [comment]
Please check this comment https://github.com/microsoft/appcenter-sdk-dotnet/issues/620#issuecomment-513828951 before trying it.

**Comment by guperrot** [comment]
Closing this one since we have WinForms available in the preview SDK. Please create specific issues if any bug or feature request.
