### ISSUE TITLE
[Android] Distribute in-app updates not working when app minSdkVersion is 26

### ISSUE THREAD

**Issue by Sjiep** [Microsoft/AppCenter-SDK-DotNet#801]
### **Description**

I followed the [steps](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android) to activate the Distribute module together with in-app updates.

When I download and install the app on the device, a browser window opens with the notification "In-app updates enabled! Returning to the app in 3, 2, 1....". All good so far. However when I close and re-open the app, the same thing happens again. 
Also when a new version is distributed, the app doesn't receive any notification (which would make sense if the app is not properly registered to receive in-app updates).

I've seen ticket #719 and #720 and I am using Google Chrome in the steps mentioned above. Any idea what is causing this behaviour?

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Android
2. Which SDK version are you using?
    - AppCenterSDK 1.9.0, 1.10.0, 1.11.0
    - AndroidSDK 27
4. Which OS version did you experience the issue on?
    - Android 8.1.0, 9
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Pixel 2 XL physical device, Huawei P20 physical device

**Comment by clpolet** [comment]
Hi there, what could help is having the console logs emitted by the SDK to understand why you are experiencing such behavior. Can you please adjust the SDK's log level to verbose as described in [this documentation](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level)? You will see SDK's logs in your IDE's device console, it should be logcat for Android. Thanks

**Comment by clpolet** [comment]
Just wondering but are you aware of anything that could prevent the SDK from writing to the app's local storage or getting values from it?

**Comment by Sjiep** [comment]
I also I see I posted my Issue in the wrong project, it should have been: AppCenter-SDK-Android

**Comment by Sjiep** [comment]
Well, I seemed to have found the cause of the problem. In my gradle file, the minSdkVersion was set to the following `minSdkVersion 26`. Setting this value to `24` fixed the problem.

Should this maybe be mentioned somewhere in the documenation?

**Comment by clpolet** [comment]
Hi @Sjiep, thanks for logs that really helps. From the `JSONException` seen it feels like a SDK/server communication issue. We are actively investigating it. Though it's quite a surprised to see that the `minSdkVersion` have fixed the issue it feels unrelated. Anyways, we'll keep you posted.

**Comment by clpolet** [comment]
A quick update, the issue is happening server side and we are still working on the fix.

**Comment by Sjiep** [comment]
Ok, good to hear. 
Just so you know, I'm fine with setting the `mindSdkVersion` to 24.

**Comment by clpolet** [comment]
Also FYI the fix for `minSdkVersion 26` is live :).

**Comment by dotfig** [comment]
I am having similar issues with appcenter inapp updates. For some reason, my application is not updating on Android version 5.1 but is updating on Android version 7.0

**Comment by jaelim-ms** [comment]
@dotfig Do you also have the same error message on your device?
```
E/AppCenterDistribute: Failed to check latest release:
    org.json.JSONException: No value for android_min_api_level
        at org.json.JSONObject.get(JSONObject.java:392)
```
Could you please post your device logs?

**Comment by dotfig** [comment]
please see refer to this issue https://github.com/Microsoft/AppCenter-SDK-Android/issues/948

this issue can be closed
