### ISSUE TITLE
Distribute not work with android cosu

### ISSUE THREAD

**Issue by diogosapessoa** [Microsoft/AppCenter-SDK-DotNet#804]
### **Description**

Distribute module not work with android cosu

### **Details**

My app is device owner using QR code for installation [Provision dedicated devices](https://developer.android.com/work/dpc/dedicated-devices/#provision_dedicated_devices) 
We need to manage automatic updates and try AppCenter Distribute SDK
But when app is installed with QR code, the InstallerPackageName=**com.android.managedprovisioning**
And not listed in options [Populate local stores](https://github.com/Microsoft/AppCenter-SDK-Android/blob/b19a26b57004cdca05a5413ff5f7bd0f4b73b088/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java#L36)

Xamarin.Android
wrapperSdkVersion: 1.12.0
sdkVersion: 1.11.0

Device: Samsung SM-G570M
Android: 8.0

I/AppCenter(21290): Distribute service started from application.
D/AppCenter(21290): Storing a log to the Persistence database for log type startService with flags=1
D/AppCenter(21290): Stored a log to the Persistence database for log type startService with databaseId=1
D/AppCenter(21290): enqueue(group_core) pendingLogCount=1
D/AppCenter(21290): checkPendingLogs(group_core) pendingLogCount=1
D/AppCenterAnalytics(21290): onActivityResumed
**D/AppCenterDistribute(21290): InstallerPackageName=com.android.managedprovisioning
I/AppCenterDistribute(21290): Not checking in app updates as installed from a store.**
D/AppCenter(21290): Storing a log to the Persistence database for log type startSession with flags=1
D/AppCenter(21290): Stored a log to the Persistence database for log type startSession with databaseId=2
D/AppCenter(21290): enqueue(group_analytics) pendingLogCount=1
D/AppCenter(21290): checkPendingLogs(group_analytics) pendingLogCount=1
D/AppCenterAnalytics(21290): onActivityPaused
D/AppCenter(21290): triggerIngestion(group_core) pendingLogCount=1
D/AppCenter(21290): Trying to get 1 logs from the Persistence database for group_core
D/AppCenter(21290): Returning 1 log(s) with an ID, 39cf743d-3a9d-4833-916e-83f473024f9e
D/AppCenter(21290): The SID/ID pairs for returning log(s) is/are:
D/AppCenter(21290): 	null / 1
D/AppCenter(21290): ingestLogs(group_core,39cf743d-3a9d-4833-916e-83f473024f9e) pendingLogCount=0
D/AppCenter(21290): checkPendingLogs(group_core) pendingLogCount=0
V/AppCenter(21290): Calling https://in.appcenter.ms/logs?api-version=1.0.0...
V/AppCenter(21290): Headers: {Install-ID=decbc58b-30ef-4811-b3ee-dea329753d18, App-Secret=****************************715904ff, Content-Type=application/json}
V/AppCenter(21290): {
V/AppCenter(21290):   "logs": [
V/AppCenter(21290):     {
V/AppCenter(21290):       "type": "startService",
V/AppCenter(21290):       "timestamp": "2019-01-16T17:55:07.151Z",
V/AppCenter(21290):       "device": {
V/AppCenter(21290):         "wrapperSdkVersion": "1.12.0",
V/AppCenter(21290):         "wrapperSdkName": "appcenter.xamarin",
V/AppCenter(21290):         "wrapperRuntimeVersion": "9.1.5.0",
V/AppCenter(21290):         "sdkName": "appcenter.android",
V/AppCenter(21290):         "sdkVersion": "1.11.0",
V/AppCenter(21290):         "model": "SM-G570M",
V/AppCenter(21290):         "oemName": "samsung",
V/AppCenter(21290):         "osName": "Android",
V/AppCenter(21290):         "osVersion": "8.0.0",
V/AppCenter(21290):         "osBuild": "R16NW",
V/AppCenter(21290):         "osApiLevel": 26,
V/AppCenter(21290):         "locale": "pt_BR",
V/AppCenter(21290):         "timeZoneOffset": -120,
V/AppCenter(21290):         "screenSize": "720x1280",
V/AppCenter(21290):         "appVersion": "1.0.0",
V/AppCenter(21290):         "carrierCountry": "br",
V/AppCenter(21290):         "appBuild": "1",
V/AppCenter(21290):         "appNamespace": "com.vsoft.appadmin"
V/AppCenter(21290):       },
V/AppCenter(21290):       "services": [
V/AppCenter(21290):         "Analytics",
V/AppCenter(21290):         "Crashes",
V/AppCenter(21290):         "Distribute"
V/AppCenter(21290):       ]
V/AppCenter(21290):     }
V/AppCenter(21290):   ]
V/AppCenter(21290): }
D/AppCenter(21290): triggerIngestion(group_analytics) pendingLogCount=1
D/AppCenter(21290): Trying to get 1 logs from the Persistence database for group_analytics
D/AppCenter(21290): Returning 1 log(s) with an ID, 7b2226bb-32ce-45a1-bc6d-904eedc165e3
D/AppCenter(21290): The SID/ID pairs for returning log(s) is/are:
D/AppCenter(21290): 	95703f96-c5ca-48ab-9679-d4f9d6feb8c7 / 2
D/AppCenter(21290): ingestLogs(group_analytics,7b2226bb-32ce-45a1-bc6d-904eedc165e3) pendingLogCount=0
D/AppCenter(21290): checkPendingLogs(group_analytics) pendingLogCount=0

**Comment by clpolet** [comment]
Hi @UnDiogO, this looks like a bug in the native Android SDK. Thanks for reporting it.

**Comment by guperrot** [comment]
This has been fixed in version [1.13.2](https://github.com/Microsoft/AppCenter-SDK-DotNet/releases/tag/1.13.2).
