### ISSUE TITLE
MTOUCH : error MT5212: Native linking failed

### ISSUE THREAD

**Issue by SteeBono** [Microsoft/AppCenter-SDK-DotNet#816]
I can not compile iOS project with Microsoft.AppCenter.

**Enviroment:**
Xamarin.iOS 12.2
Visual Studio for Mac 7.7.3
xCode with the last version (updated on 26/01/19)
AppCenter 1.13.0
AppCenter.Crash 1.13.0
AppCenter.Analytics 1.13.0

I have also tried with xCode not updated and Xamarin.iOS not updated
I have also tried to clean projects, delete obj and bin, remove all packages and restore but none of that works.
I have also tried to add extra params to project and I have also tried to compile with (debug iphone and ad-hoc iphone).

I urgently need a service to check the crash logs, and this library does not help me.

Could you solve the problem of duplicate symbols?

**This is the log**:

clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8DspInit'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-dec.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(dec.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8PredChroma8'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-dec.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(dec.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8PredLuma16'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-dec.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(dec.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8PredLuma4'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-dec.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(dec.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LDspInit'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LInverseTransform'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LColorIndexInverseTransformAlpha'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LTransformColorInverse_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LAddGreenToBlueAndRed_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LConvertBGRAToBGR_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LConvertBGRAToRGB_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LConvertBGRAToRGBA_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LConvertBGRAToRGB565_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LConvertBGRAToRGBA4444_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LConvertFromBGRA'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LBundleColorMap'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_kPrefixEncodeExtraBitsValue'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_kLog2Table'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_kSLog2Table'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_kPrefixEncodeCode'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LTransformColor_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_VP8LSubtractGreenFromBlueAndRed_C'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-lossless.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(lossless_enc.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_WebPYUV444Converters'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-upsampling.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(upsampling.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_WebPInitUpsamplers'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-upsampling.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(upsampling.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_WebPGetLinePairConverter'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-upsampling.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(upsampling.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_WebPInitSamplers'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-yuv.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(yuv.o) (Location related to previous error)
MTOUCH : error MT5212: Native linking failed, duplicate symbol: '_WebPSamplerProcessPlane'.
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/WebP.a(libwebpdspdecode_la-yuv.o) (Location related to previous error)
MTOUCH : error MT5213: Duplicate symbol in: /Users/userh/projs/nameofapp/SteeBono.NameApp/SteeBono.NameApp.iOS/obj/iPhone/Ad-Hoc/mtouch-cache/liblibwebp.a(yuv.o) (Location related to previous error)
error MT5209 : Native linking error : 27 duplicate symbols for architecture arm64
MTOUCH : error MT5202: Native linking failed. Please review the build log.

**Comment by SteeBono** [comment]
UP..

I have found that all that symbols come from libwebp.
I have this library inside Xamarin.Forms.iOS project, the library is named WebP.Touch.

Do you use this library?
It seems strange to me that this error appeared when I have added AppCenter libraries.

Thanks

**Comment by MatkovIvan** [comment]
Hi @SteeBono,

As you mentioned, all duplicate symbols in this build are from `WebP` library.
The AppCenter do not use that library.

PS doc with detailed information of this error: [MT5212: Native linking failed, duplicate symbol: *](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5212-native-linking-failed-duplicate-symbol-)

Thanks,
Ivan

**Comment by SteeBono** [comment]
You're right, I found out what caused the conflict.
Strange that appeared after adding the AppCenter package.

Sorry for this fake iusse.

Thanks,
Stefano
