### ISSUE TITLE
Expose Title and Message when System/Background notification is pressed (Xamarin.Forms on Android)

### ISSUE THREAD

**Issue by NaveenGovindraj** [microsoft/appcenter-sdk-dotnet#817]
Hello Team,

Note: This is more of a feature-request rather than an issue.

I am trying to implement AppCenter Push on a Xamarin.Forms App.

When implementing the feature on Xamarin.Forms Android App, I came across this piece of info in the docs:

"The background notification click callback does NOT expose title and message. Title and message are only available in foreground pushes."
"When the push is clicked from background on Android and UWP, the event does not have title and message in the event arguments, only iOS expose those fields for all events."

Is it possible to implement this feature to display the title and message when the background push is clicked?
I am not sure if there is any workaround for this at the moment to overcome this issue, if there is please do share the info.

**Comment by jwargo** [comment]
@NaveenGovindraj thanks for this, we've heard the same from other customers as well. I'll add this to our list of requested features. Just so you know,

**Comment by AnastasiaKubova** [comment]
Hi there!
The App Center Push module has been removed from App Center SDK in the [4.0.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.0.0) version so we are closing this feature request.

As an alternative to App Center Push, we recommend you migrate to [Azure Notification Hubs](https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-overview) by following the [Push Migration Guide](https://docs.microsoft.com/en-us/appcenter/migration/push/).
