### ISSUE TITLE
No IntelliSense

### ISSUE THREAD

**Issue by breyed** [microsoft/AppCenter-SDK-DotNet#818]
No documentation shows up in Visual Studio for most of the symbols in the SDK. A quick example is `AppCenter.SetLogUrl`: there's no indication of what this method does.

**Comment by guperrot** [comment]
Hi, we do have the source doc comments for the APIs mentioned in the public docs but it looks once packaged into nuget it does not work indeed. We will have a look at how to fix for binary distribution.

Though `AppCenter.SetLogUrl` is public (language constraint), it's not intended for public usage and thus has no documentation. We can add a comment there. It is to redirect traffic to another endpoint and we use that for testing.

**Comment by guperrot** [comment]
Looks like crashes, distribute and push still have the issue, the fix worked only for core and analytics.

**Comment by guperrot** [comment]
This bug has been fixed in version [2.0.0](https://github.com/microsoft/AppCenter-SDK-DotNet/releases/tag/2.0.0).
