### ISSUE TITLE
AppCenter used for namespace and type

### ISSUE THREAD

**Issue by breyed** [Microsoft/AppCenter-SDK-DotNet#819]
The Framework Design Guidelines (which the AppCenter SDK should follow, since it's an extension of the framework and should integrate seamlessly with) includes this [naming](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces) rule:

> **DO NOT** use the same name for a namespace and a type in that namespace.

The namespace `AppCenter` and type `AppCenter` don't follow this rule. Additionally, the the SDK uses a common type name `Device`, which is in use by Xamarin.Forms, means that code using AppCenter often ends up using fully qualified type names rather than a `using` directive. The result is ugly and possibly confusing code like this:

``` c#
Microsoft.AppCenter.AppCenter.SetUserId(user);
```

The specific issue is the namespace/type name conflict. The larger issue is that this conflict is indicative of the SDK being rushed out without bothering to run Code Analysis on it. Since ease of programmer use is a key goal behind the SDK, the same review and scrutiny that makes the .NET Framework and .NET Core so productive should also apply to the SDKs like AppCenter.

**Comment by guperrot** [comment]
We thank you for your feedback.
The API changes from your suggestion cannot be applied to the versions 1.x without a major change.
We have no plan for a version 2.0 at this time but we can consider this change when a major version of the SDK will be planned.

**Comment by guperrot** [comment]
This change would be too disruptive even for a 2.0.

While we value guidelines, we value cross platform solutions more and the Xamarin SDK was modeled after doing the Java SDKs and Apple SDKs to provide a unified experience.

Not all platforms have the same guidelines and for simplicity we wanted to have static methods called on a class named after the module like Analytics so you call Analytics.TrackEvent and when you look for the nuget it is simply the Analytics package.

We understand the frustration it can cause for some developers but as a team we decided not to rename those as we would also need to rename Java, Apple, Cordova, Unity and React-Native SDKs as a result.

**Comment by breyed** [comment]
Consistency between platforms is important, but that's different than verbatim identical APIs. It's analogous to the bad-old-days of mobile apps that used web browser controls to present an identical UI on iOS and Android, and ended up fitting neither platform well. Native-focused platforms like Xamarin Forms allowed developers to keep the apps consistent, yet follow the platform idioms to provide a native experience.

The same concept holds for cross-platforms APIs. The general design of the API should be equivalent, but where languages differ, the SDKs should acclimate in a consistent way. For example, Java for Android uses camel case method names and has no properties, so it might say `getFoo`, whereas the equivalent for .NET would be a `Foo` property. For a .NET developer, to have to code against an API designed for Java is awkward and unproductive.

The namespace/class name conflict is an example of an idiom for another language not matching .NET, due to .NET having different name resolution rules. That's why the guideline exists. Just like method names, namespace names should be tuned to provide a native development experience, while remaining conceptually consistent with other platforms.

A good example of a framework that does this well is Google [Protocol Buffers](https://developers.google.com/protocol-buffers/). It has SDKs for various languages, each of which honors the idioms of its language, yet still providing consistency across all languages.
