### ISSUE TITLE
Add Tuple based overloads to Analytics/Crashes

### ISSUE THREAD

**Issue by dansiegel** [microsoft/appcenter-sdk-dotnet#821]
### **Description**

There are a number of times where a developer may only want to add a single property to track such as a UserId. Given the current API's you have to instantiate a Dictionary and load it like:

```cs
Analytics.TrackEvent("Some Event", new Dictionary<string, string> { { "userid", userId } });
```

### Proposed API

- Analytics.TrackEvent(string message, params (string, string)[] properties)
- Crashes.TrackError(Exception ex, params (string, string)[] properties)

These overloaded API's don't actually change or impact functionality in any way, but they do make it just a little easier and provide some nice syntactic sugar when calling them.

```cs
Analytics.TrackEvent("Some Event", ("userId", userId));
```

**Comment by guperrot** [comment]
Hi, thanks for your feedback, I will forward it.
As a side note, for userId we recommend using AppCenter.SetUserId instead.

**Comment by dansiegel** [comment]
@guperrot I was just using that as a common case that would make sense for someone to want to track... and yes the SetUserId would seem like a much better API to use for that specific property. :)

**Comment by guperrot** [comment]
We might consider this feature in the future but there is no plan right now.

**Comment by guperrot** [comment]
Sure, for Analytics you need to modify portable code (empty implementation): https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/develop/SDK/AppCenterAnalytics/Microsoft.AppCenter.Analytics/Analytics.cs

Then implement it for Android, iOS then Windows.

https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/develop/SDK/AppCenterAnalytics/Microsoft.AppCenter.Analytics.iOS/Analytics.cs
https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/develop/SDK/AppCenterAnalytics/Microsoft.AppCenter.Analytics.Android/Analytics.cs
https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/develop/SDK/AppCenterAnalytics/Microsoft.AppCenter.Analytics.Windows.Shared/Analytics.cs

For crashes it can be done in a single place as code is shared: https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/develop/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.Shared/Crashes.cs

**Comment by fredeil** [comment]
Would it be ok introduce the System.ValuTuple NuGet into the project? @guperrot

**Comment by guperrot** [comment]
Hi, we use only dependencies when we have no other reasonable choice for a required feature, but here it only add a syntax simplification for only 1 method. I'll talk to the rest of the team and let you know about the decision after the discussion.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
