### ISSUE TITLE
Crashes: Support TrackError with string instead of exception

### ISSUE THREAD

**Issue by dansiegel** [microsoft/appcenter-sdk-dotnet#822]
### **Description**

Some frameworks may include logging frameworks that require a string input with a flag that indicates that this particular log is an Exception. As an example you can look at Prism's [ILoggerFacade](https://github.com/PrismLibrary/Prism/blob/master/Source/Prism/Logging/ILoggerFacade.cs). In this case when the framework has encountered an exception it handles this by calling ToString() when logging the error. 

For these scenarios it would be fantastic if the Crashes API could handle these cases were we have a string that we expect to be an exception that has ToString() called on it.

#### Proposed API

- Crashes.TrackError(string exception, IDictionary<string, string> properties)

**Comment by guperrot** [comment]
Hi, thank for your feedback, I will forward.
Just a comment is that the backend can only process errors as exceptions, expecting a type and optionally a stack trace. It would also need changes in the backend to allow errors as just a message and nothing else.

Today the closest to that is to call `Crashes.TrackError(new Exception("single line"));` and this currently looks like:

<img width="864" alt="screen shot 2019-01-28 at 2 41 40 pm" src="https://user-images.githubusercontent.com/623672/51871300-dadbe500-230a-11e9-9812-0912bac5f42d.png">

**Comment by dansiegel** [comment]
I fully understand that this could be used improperly... but for the sake of argument let's assume that we are saying that the intended use case here is something like:

```cs
private void MethodA()
{
    try
    {
        throw new Exception("Something went wrong...");
    }
    catch(Exception ex)
    {
        LogException(ex.ToString());
    }
}

private void LogException(string exception)
{
    // Do stuff...
    Crashes.TrackError(exception);
}
```

I understand that there is obviously more particularly on the Platform level that needs to be done in order to properly handle this to log.

**Comment by guperrot** [comment]
Also logging a string message with properties is exactly what `Analytics.TrackEvent` does, maybe using Analytics is more suitable in that case? And it supports export to App Insights or a storage account.

**Comment by dansiegel** [comment]
That is extremely different in concept. Analytics are ultimately meant for PM's and PO's to determine how people flow through an application and make decisions based on that.

Crashes and Error handling are **NOT** Analytics Events. This are holistically developer focused. It is important to show key pieces of the Stack Trace to assist a developer in determining what went wrong. The sample above is meant to illustrate simply the idea that you may have to deal with an exception that is encountered deeper down than the code than you may have access to and that you would need to therefore try to be able to call the Crashes.TrackError API with a string rather than an Exception since ToString has already been called. For example this would be the output when you ToString the exception thrown in the DoFoo() method from a simple demo app. You'll notice this gives me the Type of Exception, as well as the Message from the Exception, and the full StackTrace... all information that belongs in the Crashes area of the App Center portal and contains information relevant to developers only.

```
System.Exception: Something went wrong
   at demo.FooUtility.DoFoo() in C:\Repos\demo\FooUtilitity.cs:line 9
   at demo.Program.Main(String[] args) in C:\Repos\demo\Program.cs:line 15
```

What you're talking about with using the Analytics API would be if I wanted to do something like:

```cs
Analytics.TrackEvent(ex.Message)
```

Where I would see in this example simply the "Something went wrong"... but in a real app we're going to almost instantly start polluting the Analytics with garbage where we say something like `Argument null 'source'` which will mean nothing to anybody.

**Comment by guperrot** [comment]
But this:
```

**Comment by dansiegel** [comment]
@guperrot look again at my original statement with the link... the point is that sometimes you need to handle logging from frameworks which do NOT support passing you the raw exception and which instead have called ToString before passing you the exception... so you now have a string to work with.

**Comment by guperrot** [comment]
Now I understand the use case and thanks for your patience.
Forwarding the feedback.

**Comment by winnieli1208** [comment]
Hi @dansiegel - thanks for the helpful feedback! I'm a PM on App Center and we have an item in our backlog to add custom properties for crashes. Unfortunately, due to other priorities, I don't have a clear timeline but will update this thread as soon as I have more details.

**Comment by bekir-ozturk** [comment]
I'm in need of the same functionality for my app.

In many cases, I'm detecting issues without there being an exception. For instance, I received a message from the server and it is badly formatted. There is no exception, the app logic has just determined that the format is bad.
``` csharp
int headerLength = BitConverter.ToInt32(buffer);
if (headerLength < 0)
{
    Crashes.TrackError(new System.Exception("Invalid data header."));
}
```

Constructing a new exception, just to get a string out of it isn't very nice here. But I can look past this.

My issue is setting the `stack trace`. .NET does not offer a way to set the stack trace string today as far as I could find. Options are:
- Possible but ugly: Throwing an exception and catching it immediately
- Not possible: inheriting from Exception type and overriding stack trace. Reason: stack trace member is not marked virtual.
- Possible but ugly: Using reflection to access the setter for stack trace

There is also a second issue here, which is very related. In the sample code above, you have seen that I threw "System.Exception". This will show up in the app center as "System.Exception", but I would very much prefer to see an "InvalidDataHeaderException". As you may guess, I can't `throw new InvalidDataHeaderException` because no such type exists. My only option is to create the type and inherit from `System.Exception` which requires too much work to pass a simple string to `Crashes.TrackError`.

## API Proposal

We don't need to change the data representation on the server side. These issues can simply be solved by accepting the data of an exception in the deconstructed format.

The following new method would be added:
``` csharp
namespace AppCenter
{
    public class Crashes
    {
        public static void TrackError(string exceptionName, string message, string stackTrace, IDictionary<string, string> properties = null, params ErrorAttachmentLog[] attachments);
    }
}
```

**Comment by DmitriyKirakosyan** [comment]
Hi @bekir-ozturk , thank you for the report and the details!
Here are the possible workarounds I can think of for your scenarios:
- **Sending stacktrace with `trackError`**
Send stacktrace string in attachments (file or text). Another option is throwing and catching an exception (you mentioned that).
- **Using a custom exception name.**
The best solution would be creating a custom Exception based class.
Another way to achieve that would be creating a helper class/method which would create a formatted exception message, eg:
```csharp
public string CreateFormattedErrorMessage(string name, string message)
{
    return $"[{name}] {message}";
}
```

As for the feature request, thank you for bumping it! The more upvotes we receive the faster we can prioritize it.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
