### ISSUE TITLE
[Push,Android] Application doesn't receive pushes from AppCenter if app is signed 

### ISSUE THREAD

**Issue by vlkam** [Microsoft/AppCenter-SDK-DotNet#830]
Application doesn't receive pushes from AppCenter console if app is signed but receives from Firebase console

If app starts in debug mode it receives messages from AppCenter console and Firebase console
But if app is signed it receives messages only from Firebase console

1. Xamarin Android
2. SDK version  1.13.0
4. Android 8.0.0  Android 6.0.1
5. Samsung Galaxy S7, Samsung Galaxy J1
6. List of packages is attached
[packages.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2841651/packages.txt)
7. logs are attached. I sent 2 pushes one from Appcenter and second from Firebase console
[logcat_full.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2841643/logcat_full.txt)
[logcat_appcenter_msg_only.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2841644/logcat_appcenter_msg_only.txt)

**Comment by dtrabo** [comment]
Hi @vlkam , thanks for reporting this! 

Can you provide detailed steps of how you configured sdk?
Does this problem occur only on SDK version 1.13.0 or on previous versions too?
Does this problem occur only on Galaxy S7, Galaxy J1 or you've tested only on these devices? 
Please, try completely deleting your app from device and installing it again. Tell me if it helps.

Thanks!

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
