### ISSUE TITLE
Silent push for iOS without UI

### ISSUE THREAD

**Issue by pfedotovsky** [Microsoft/AppCenter-SDK-DotNet#831]
### **Description**

I'd like to send a silent push to iOS devices using App Center SDK, without showing a notification to the user.

My app needs to update a local database silently and there're two options:

1. Only update app data and don't show anything to a user
2. Update app data and **only if** update is successful, show notification to a user. After the click, the user should go to a page with new data.

Update process requires downloading data (text & binary) from the Azure Function, so it's not fast enough to update in the foreground. That's why I need background update without user interruption.

### **Repro Steps**

I've set up App Center Push SDK as described in the documentation: https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios:

```
            // This should come before AppCenter.Start() is called
            // Avoid duplicate event registration:
            if (!AppCenter.Configured)
            {
                Push.PushNotificationReceived += (sender, e) =>
                {
                    // Add the notification message and title to the message
                    var summary = $"Push notification received:" +
                                        $"\n\tNotification title: {e.Title}" +
                                        $"\n\tMessage: {e.Message}";

                    // If there is custom data associated with the notification,
                    // print the entries
                    if (e.CustomData != null)
                    {
                        summary += "\n\tCustom data:\n";
                        foreach (var key in e.CustomData.Keys)
                        {
                            summary += $"\t\t{key} : {e.CustomData[key]}\n";
                        }
                    }

                    Logger.Track("PushReceived for iOS app");
                };
            }

            AppCenter.Start(
                $"ios={config.AppCenteriOSKey};android={config.AppCenterAndroidKey};",
                typeof(Analytics),
                typeof(Crashes),
                typeof(Push));
```

1. Send a notification using App Center and tick "silent" checkbox
2. Notification is shown to a user

### **Details**

Xamarin.Forms 3.5.0, .NET Standard, 
Microsoft.AppCenter.Push 1.13.0

For details, see GitHub repo: https://github.com/DotNetRu/App

**Comment by MatkovIvan** [comment]
Hi Pavel,

Duplicate the answer here:
The setup process for silent notifications is documented in [[Optional] Enable silent notifications](https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios#optional-enable-silent-notifications) section. Please let us know if this doesn't work for you.

Thanks,
Ivan

**Comment by MatkovIvan** [comment]
I'll add a note with a clarification to the doc about it.
Closing this issue as duplicate.
