### ISSUE TITLE
Identify installations and get Install ID 

### ISSUE THREAD

**Issue by amrutha786** [Microsoft/AppCenter-SDK-DotNet#845]
[Log Level.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2898504/Log.Level.txt)

### **Description**

I am trying to get identify the users and get the Install ID 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.Using this documentation: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#identify-installations 
2.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
Xamarin iOS 
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - e.g. .NET standard 2.0.
2. Which SDK version are you using?
    - e.g. Visual Studio 7.7.4 
4. Which OS version did you experience the issue on?
    - e.g. iOS 12
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone XS Max physical device
6. What third party libraries are you using? 
    - example
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before you
[Log Level.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2898503/Log.Level.txt)
r call to `AppCenter.Start(...)` and include the logs here:

**Comment by elamalani** [comment]
Hi @amrutha786 - you can use the [GetInstallIdAsync()](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#identify-installations) API if you want to get the installation id for the device.

You can use the [SetUserId()](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#identify-users) API if you want to associate your crash reports with user information. Please note that the SetUserId() API can only be used with crash reports for now.
