### ISSUE TITLE
[UWP SDK] Log Trace Messages

### ISSUE THREAD

**Issue by mieliespoor** [microsoft/appcenter-sdk-dotnet#849]
Please allow us to log trace messages to AppCenter for UWP. HockeyApp provides the method, TrackTrace(…), which allows us to track trace messages.

It would be great if these message are then visible in AppCenter on the Analytics / Log flow screen. I don't really see the need to see this elsewhere in AppCenter itself, but I want to search for these in Application Insights if a link has been set up.

Platform: UWP
Current SDK: 1.13

**Comment by elamalani** [comment]
Hi @mieliespoor - Thanks for using App Center. We don't support this feature right now but I'll track it as a  feature request and let you know once we plan to support it in the product.

**Comment by DmitriyKirakosyan** [comment]
Hi @mieliespoor ,

I would like to refresh the status of this feature request.
We have [TrackError](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#handled-errors) API for tracking handled errors. Does it resolve your issue?

**Comment by mieliespoor** [comment]
I'd say that TrackError would be used in a different situation as you will then be tracking a specific error message and related data whereas TrackTrace would allow the developer to send additional trace data in that might not be an error but may add additional debugging context in certain situations.

**Comment by AnastasiaKubova** [comment]
Hi @mieliespoor ! You can send additional info in attaches like:

```
try {
    // your code goes here.
} catch (Exception exception) {
    var attachments = new ErrorAttachmentLog[]
    {
        ErrorAttachmentLog.AttachmentWithText("Hello world!", "hello.txt"),
        ErrorAttachmentLog.AttachmentWithBinary(Encoding.UTF8.GetBytes("Fake image"), "fake_image.jpeg", "image/jpeg")
    };
    Crashes.TrackError(exception, attachments: attachments);
}
```

Does this solve your issue?

**Comment by mieliespoor** [comment]
I get that but why register an error for something that isn't an error?

Using TrackError will show up as an error on the dashboards and will then count towards the crashes/errors KPI for an app. So you then may be inflating that KPI for things that aren't errors.

**Comment by AnastasiaKubova** [comment]
@mieliespoor, you can use[ Analytics.TrackEvent](https://docs.microsoft.com/en-us/appcenter/sdk/analytics/windows#custom-events) API for tracking it if you don't need to track it as an error.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
