### ISSUE TITLE
I've encountered this exception a few times recently...

### ISSUE THREAD

**Issue by jwallra** [Microsoft/AppCenter-SDK-DotNet#851]
_Originally posted by @dfoulk in https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/826#issuecomment-471768758_

I've encountered this exception a few times recently...

> Unhandled Exception: Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService; occurred

To remedy this, I have to:

1. Close Visual Studio
2. Delete all **obj** and **bin** folders in the solution
3. Clear NuGet cache (using `nuget locals all -clear`)
4. Open Visual Studio
5. Build my app again

And... voila! No more exception. @guperrot I have everything configured properly, however I am a couple of releases behind (I'm using **Microsoft.AppCenter.*** **v1.12.0**).

Any idea why my little to-do list fixes the exception (temporary as it may/may not be)?

**Comment by guperrot** [comment]
It's a problem of build cache being stale, there is unfortunately nothing we can do on App Center side to prevent Xamarin build cache issues in general. Cleaning thoroughly is the only solution for this kind of issues.

**Comment by dfoulk** [comment]
@guperrot - Could you (pretty please) tell me the path (on Windows) of the "Xamarin Build Cache"? We have a custom built VS extension that "deep cleans" solutions/projects. I'd like to add this build cache to the list of items to be deleted optionally.

I found **C:\Users\Me\AppData\Local\Xamarin\Cache**, but it doesn't seem to be the right directory...

We are using VS2017 if that matters, thank you!

**Comment by guperrot** [comment]
Hi, I never went that far into cleaning to resolve Firebase issues so I don't know the answer. Usually manually cleaning obj and bin folders while Visual Studio is closed is enough. By Xamarin build cache I referred to obj and bin folders within the project that are generated by Xamarin build.

**Comment by guperrot** [comment]
Hey!

We haven’t heard from you in a while, do you have any more questions? If so, please let us know.  

Thanks for using App Center!

**Comment by dfoulk** [comment]
Yeah, that was my only question. Thanks.
