### ISSUE TITLE
Is Crashes.GetErrorAttachments too late to call AppCenter.SetUserId?

### ISSUE THREAD

**Issue by nathanielcook** [Microsoft/AppCenter-SDK-DotNet#861]
### **Description**

This issue is a question.

Is the `Microsoft.AppCenter.AppCenter.Crashes.GetErrorAttachments` event handler too late to call `AppCenter.SetUserId`?

### **Repro Steps**

Not Applicable

### **Details**

Setting the user id in the `AppCenter.Crashes.GetErrorAttachments` event handler is a way of lazily loading the user id, and also it ensures that the user id is set at the time of reporting a crash. But it's possible that doing it in that event handler could cause problems if the dev team has not anticipated such a thing, so I wanted to ask about it.

**Comment by guperrot** [comment]
Yes it is too late as the crash happens before restart and the user ID is the one set and saved from the previous run where the crash occurred. The get attachments callback is called after restart while processing the report.

**Comment by nathanielcook** [comment]
> the user ID is the one set and saved from the previous run where the crash occurred

Got it, thank you! Closing
