### ISSUE TITLE
Distribution detection page overridden by my apps login page

### ISSUE THREAD

**Issue by helzgate** [Microsoft/AppCenter-SDK-DotNet#863]
### **Description**

While trying to use the Distribution feature the callback is never handled in Xamarin.Forms because I have a login process that also opens up a web page to authenticate the user on application launch.  The browser OIDC login page appears to prevent the previous Distribution detection page from working.  I have no way of waiting on the Distribution detection page to finish it's process first.

I know that the distribution is still working though because if, while on Android, I view the open browsers in the background I still find the detection page for distribution running in the background frozen at 1 second.  When I hit the button "continue to app" it sends me back to the app and it detects that I have an upgrade and presents the prompt to me.

Distribution detection still "kind of" works on iOS.  At least the dialog to update the app stays on the screen for the user to click but the dialog inviting the user to download the latest version gets all screwed up and appears at the top left corner of the screen instead of in the center after the user logs into my app.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use distribution plugin
2. Implement a browser based auto-login method that your app uses on startup

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    -  Xamarin.Forms on Android and iOS.
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    -  .NET standard 2.0.
2. Which SDK version are you using?
    -  1.13.2
4. Which OS version did you experience the issue on?
    - iOS 11, Android 8.0.0
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    -  iPhone 6 physical device, Samsung Galaxy S7

**Comment by guperrot** [comment]
Hi, having 2 web logins at the same time is not ideal. Would it work for you to delay in-app updates after your own login? You can remove `typeof(Distribute)` from the main `Start` line and have a separate call to `AppCenter.Start(typeof(Distribute))` when suitable to do so (after login, without the appSecret when calling start later).

**Comment by helzgate** [comment]
@guperrot I think I have it working where the detection runs after the login and I'd like to share my code with others who may need it as a reference but I'm not 100% sure it's working.

let  me explain..

* I get the browser distribution detection page and it sends me back to the app.
* My app tells me I have an update available but I close the app without doing anything.
* I uninstall my app, then reinstall the same older version
* I launch the app and now the browser detection page won't show back up.  Sometimes it will if I restart device, or clear Chrome cache, or uninstall my app and reinstall.  It just seems so random.  I can't tell if it's something wrong in my app or if AppCenter is purposefully not launching the Distribution browser page because it only does it every so often.  I can't prove it but it feels like its the SDK purposefully not showing me the distribution detection page.   Are you familiar with any mechanics like this?

**Comment by guperrot** [comment]
The browser is a 1 time setup to know whether you installed from a public distribution group or if you installed the app while you were logged in to the AppCenter portal. After that we save the distribution group id and the in-app-update token (if you installed while logged in).

After the 1 time browser setup, the in-app updates checks are just silent API calls, and will show a native dialog only if there is a new version available for the distribution group you installed from (or all groups you have access to while you were logged in when installing the app from the browser).

If you uninstall, the browser should open up again as the SDK lost its local storage.

If that does not work as I described we would need you to distribute a build with verbose logging enabled (`AppCenter.LogLevel = LogLevel.Verbose` before `AppCenter.Start`) and extract logs from the device after the bug is reproduced (all logs that have a tag starting with AppCenter) using `Console` for iOS or `adb bugreport` for Android.

**Comment by helzgate** [comment]
@guperrot It seems to be working fine now.  This is the code I ended up using for reference.

Following is how I got the Distribution detection page to come up AFTER my login page. 

* App.xaml.cs

```
protected override void OnStart()
{
    base.OnStart();

    
    if (!AppCenter.Configured)
    {                
        Distribute.ReleaseAvailable = OnReleaseAvailable;
        AppCenter.Start("ios=<...>android=<...>", typeof(Analytics), typeof(Crashes), typeof(Distribute));
        Distribute.SetEnabledAsync(false);
    }
}
```

* Home Page

```
public partial class Home : ContentPage
{
    public Home()
    {
        InitializeComponent();
        Distribute.SetEnabledAsync(true);
    }
}

**Comment by guperrot** [comment]
You should do the following as SetEnabledAsync can delete cached data and is not meant for delayed start use case (and also it's persisting the disabled state across runs).

The correct usage would be:

```
protected override void OnStart()
{
    base.OnStart();

    
    if (!AppCenter.Configured)
    {                
        Distribute.ReleaseAvailable = OnReleaseAvailable;

        // skip distribute start
        AppCenter.Start("ios=<...>android=<...>", typeof(Analytics), typeof(Crashes));
    }
}
```

```
public partial class Home : ContentPage
{
    public Home()
    {
        InitializeComponent();
        AppCenter.Start(typeof(Distribute)) // no appsecret
    }
}
```

**Comment by helzgate** [comment]
@guperrot Perfect!  That's what I'll do.  Thanks for taking the time to be so helpful!

**Comment by guperrot** [comment]
Hi, thanks for the feedback. Can you confirm though that your Home page is not the very first loaded in your app? Did you check the execution order with breakpoint? As `OnStart` must happen before `Home` page constructor.

**Comment by helzgate** [comment]
@guperrot The home page is not the first page loaded in my app, the login page is.  OnStart is loading within the App.xaml.cs before any pages load.

**Comment by guperrot** [comment]
Ok that's why it works then, if someone else reads this they need to keep that in mind as the solution will not work on a vanilla forms project with Home page being the main one.

Thanks for your patience and for using AppCenter.

**Comment by helzgate** [comment]
It still doesn't work on Android.  I have to minimize/maximize to get app to detect there is an update.

Here is the behavior
1. Run the app.
2. Login
3. After login I'm sent to Home page and it is supposed to kickoff the `AppCenter.Start(typeof(Distribute))` that is in my ContentPage but nothing appears to happen
4. I navigate to other pages in my app and come back to the home page but still nothing.
5. I minimize the app without closing, then re-maximize the app, then it launches the detection webpage and tells me I have an update.

I created a basic example app that shows this behavior, you can find it [HERE](https://github.com/helzgate/AppCenterFail)

**Comment by guperrot** [comment]
That's probably because we miss the foreground (activity resume) event with that delayed start model.

What about if you go back to https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/863#issuecomment-477820227 solution? It should get the current activity pointer with that solution, then remain dormant with the setEnabled(false) and should resume with setEnabled(true). Less ideal but it should work.

**Comment by helzgate** [comment]
Ok, I tested this successfully on Android and iOS.  Thanks again!

**Comment by guperrot** [comment]
Glad it worked for you and thanks for using AppCenter.
