### ISSUE TITLE
Mapping push device id to user

### ISSUE THREAD

**Issue by Giorgi** [Microsoft/AppCenter-SDK-DotNet#864]
As I understood from the documentation when I start the Push service the app automatically gets registered with the push service and device id is generated. Is is possible to set custom property (such as user id) so that I know which device belongs to which user? I need this to send push notifications to specific users only so I need a way to have mapping between user id and device id

**Comment by jwargo** [comment]
@Giorgi This is supported in the Push to User feature we're working on. You can see a proposed UI for this (although I need to update it) here: https://github.com/Microsoft/appcenter/issues/15.

**Comment by jwargo** [comment]
@Giorgi The push to user feature just went live (or will be live today); learn how to use it (and set the User ID via the SDK) here: https://docs.microsoft.com/en-us/appcenter/push/push-to-user.

**Comment by jwargo** [comment]
@guperrot can you close this?
