### ISSUE TITLE
No badge with number of unread messages for android 9

### ISSUE THREAD

**Issue by isabellemartin2** [Microsoft/AppCenter-SDK-DotNet#868]
I've implemented push notification via App Center Push for my xamarin.forms project. On my android 9 device "Honor P 10 lite" the counter for the unread messages is not visible any more. The badge with badge count for unread messages is shown correctly when I install the same app  on a Android 8 device (Samsung Galaxy S7).
I know that with android 9 so called "notification dots" were introduced. 
If this is enabled via Settings  the dot above the app icon is visible when new messages arrived. And by long press on the app icon I can see the notification and also the correct notification count is shown on the right. 
If i switch to "Badge display mode: "Unread messages" and afterwards send a push notification to my app, the badge counter doesn't get visible (altough the notification is appearing on the screen)

I've tried to set the badge count in code (notificationChannel.SetNumer()); and also tried to set the target android version to the highest API level.

Expected result: Show a badge with the correct number of unread messages on the app icon. Actual result: No badge is shown when new push notifications were send to the device.

Tested Devices
Honor 10 Lite | Android Version: 9 | Launcher: Default (Huawei Home)
Huawei 8X | Android Version: 9 | Launcher: Default (Huawei Home)

**Comment by MatkovIvan** [comment]
Hi @isabellemartin2,

The badges with numbers feature is a launcher dependent thing. AppCenter SDK doesn't provide any API to set this number.

It may be a bug with Huawei Launcher.
Another option here is to use a separate library that takes care of custom launchers to set this value directly.

Thanks,
Ivan

**Comment by isabellemartin2** [comment]
Hi @MatkovIvan,

thanks for your fast response. I'll do some further research.

Thanks for your help,
Isabelle

**Comment by dhei** [comment]
Hi @isabellemartin2,

We haven't heard from you in a while so I'm closing this issue. Please comment if you have more questions about this.
