### ISSUE TITLE
Issue with MacOS 10.14.4 when running UITest in Visual studio for mac

### ISSUE THREAD

**Issue by samueljoos** [Microsoft/AppCenter-SDK-DotNet#869]
### **Description**

I was sent here from following issue: https://github.com/xamarin/xamarin-macios/issues/5816
The app build's but can't be launched because of following error: **This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.**

![Screen Shot 2019-04-04 at 16 36 21](https://user-images.githubusercontent.com/1914071/55607111-9beb6500-577b-11e9-9c2e-0129ed6f7431.png)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Run an iOS UITest
2. Check the test results

### **Details**

1. What is your app platform
    -  Xamarin.iOS 
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - e.g. .NET standard 2.0.
3. Which SDK version are you using?
    - The issue doesn't really happen in AppCenter but I was sent to post my issue here: https://github.com/xamarin/xamarin-macios/issues/5816
4. Which OS version did you experience the issue on?
    - e.g. iOS 12.2
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone X physical device

**Comment by MatkovIvan** [comment]
As we mentioned in the GitHub Issue template:

> If your issue is not related to using our .NET **SDK** but rather about the product experience like the portal or CI, please create a ticket using the blue chat button on any page of the https://appcenter.ms portal instead.

So, that's not a bug in the **SDK**, but fortunately, I'm aware of this problem since the folks who sit on the next table are working on this one 😄 

Anyway, please contact our support via intercom about it.

JFYI Here is in progress PR to fix one of the internal tools that are used underhood: https://github.com/calabash/FBSimulatorControl/pull/47

Thanks,
Ivan
