### ISSUE TITLE
[Android] SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by Seuleuzeuh** [Microsoft/AppCenter-SDK-DotNet#870]
### **Description**

App Crash when AppCenter call com.microsoft.appcenter.utils.storage.DatabaseManager.getMaxSize.

### **Repro Steps**

No repro steps found, it's a Diagnostics from AppCenter

### **Details**

1. Xamarin.Forms 3.4.0.1009999
2. Using .NET standard 2.0.
2. AppCenter SDK 1.13.0
4. Android 7.1.1
5. Physical device :
Manufacturer: Honeywell
Model: EDA50
6. packages.config attached
[packages.config.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/3047412/packages.config.txt)
7. VerboseLog is not activated (app in production) but i've attach the log found in AppCenter.
[report-2518481212919599999-dbea078c-be6f-41b6-9e77-8e1e51550cec.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/3047407/report-2518481212919599999-dbea078c-be6f-41b6-9e77-8e1e51550cec.txt)

**Comment by MatkovIvan** [comment]
Hi @Seuleuzeuh,

This has already been fixed in `1.13.2`. Please update the SDK to the latest version.

Thanks,
Ivan
