### ISSUE TITLE
User Id not being set for Xamarin in iOS if calling `NotifyUserConfirmation` without actually using `ShouldAwaitUserConfirmation`

### ISSUE THREAD

**Issue by Jhultink** [microsoft/AppCenter-SDK-DotNet#871]
### **Description**
I have a Xamarin Forms project that is setting the User ID for both Android and iOS. Android works as expected, but when I look an iOS Crash in AppCenter the User ID is N/A and the User ID is set is displayed as an Attachment, and is not searchable. The User ID shows up successfully for Errors.

### **Repro Steps**
1. Set UserId with `Microsoft.AppCenter.AppCenter.SetUserId(userId);`
2. Generate a crash and check the iOS App Center. User ID is not being set.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    Xamarin.Forms on Android and iOS
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    PCL 4.5 - Profile111
2. Which SDK version are you using?
    1.14.0
4. Which OS version did you experience the issue on?
    iOS 12.1
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    Physical and emulator, iPhone 8 Plus and iPhone XS Max
6. What third party libraries are you using?
    None in the library where the issue is occurring
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
[AppCenter] VERBOSE: -[MSSessionContext clearSessionHistoryAndKeepCurrentSession:]/85 Cleared old sessions.
[AppCenter] VERBOSE: -[MSUserIdContext clearUserIdHistory]/108 Cleared old userIds while keeping current userId.
[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/115 Log is stored with id: '204'
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/498 Deleting a log from buffer with id 8611E544-465D-41DB-B1C9-A5C623CD572A
[AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/169 Saving log, type: startService, flags: 1.
[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/115 Log is stored with id: '205'
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/498 Deleting a log from buffer with id AFD6EFF6-AA7F-45C9-B0DE-F9CCAFFA1123
[AppCenter] VERBOSE: -[MSUserIdContext setUserId:]/88 Stored new userId:87014344:bodykeyapp+t5@gmail.com and timestamp: 2019-04-05 18:20:25 +0000.
[AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '204' as batch Id:0EE23C9F-DA9D-497A-AAB7-F668EFE8CAC5
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: Analytics, batch Id: 0EE23C9F-DA9D-497A-AAB7-F668EFE8CAC5, session Id: 7F07763F-0E86-45FA-9AA3-F8F90DFB65F1, payload:
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 3A69C24B-1E78-4844-A58E-13DB63F92C25, App-Secret = ****************************6e64c83b, Content-Type = application/json
[AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '205' as batch Id:711A6D7C-B024-4306-8CBB-742E1C199F43
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: AppCenter, batch Id: 711A6D7C-B024-4306-8CBB-742E1C199F43, session Id: (null), payload:
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 3A69C24B-1E78-4844-A58E-13DB63F92C25, App-Secret = ****************************6e64c83b, Content-Type = application/json
[AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:0EE23C9F-DA9D-497A-AAB7-F668EFE8CAC5.
[AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:0EE23C9F-DA9D-497A-AAB7-F668EFE8CAC5 from pending calls:{
[AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/322 Deletion of log(s) by id with value(s) '204' succeeded.
[AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
[AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:711A6D7C-B024-4306-8CBB-742E1C199F43 from pending calls:{
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:711A6D7C-B024-4306-8CBB-742E1C199F43.
[AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/322 Deletion of log(s) by id with value(s) '205' succeeded.
[AppCenterCrashes] ERROR: +[MSWrapperLogger MSWrapperLog:tag:level:]/7 Unhandled Exception:
[AppCenterCrashes] INFO: +[MSWrapperLogger MSWrapperLog:tag:level:]/7 Saving wrapper exception...
[AppCenterCrashes] INFO: +[MSWrapperLogger MSWrapperLog:tag:level:]/7 Saved wrapper exception.
[AppCenter] VERBOSE: -[MSDelegateForwarder addTraceBlock:]_block_invoke_2/83 Start buffering traces.
[AppCenter] DEBUG: -[MSDelegateForwarder setEnabledFromPlistForKey:]_block_invoke/273 Delegate forwarder for info.plist key 'AppCenterAppDelegateForwarderEnabled' enabled. It may use swizzling.
[AppCenter] VERBOSE: +[MSDelegateForwarder flushTraceBuffer]/101 Stop buffering traces, flushed.
[AppCenterXamarin] DEBUG: +[MSWrapperLogger MSWrapperLog:tag:level:]/7 No named identifier found in appSecret; using as-is
[AppCenter] DEBUG: -[MSSessionContext init]/39 1 session(s) in the history.
[AppCenter] VERBOSE: -[MSSessionContext setSessionId:]/63 Stored new session with id:(null) and timestamp: 2019-04-05 18:21:39 +0000.
[AppCenter] DEBUG: -[MSUserIdContext init]/50 1 userId(s) in the history.
[AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/309 Internet connection is up.
[AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/309 Internet connection is up.
[AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/309 Internet connection is up.
[AppCenter] INFO: -[MSAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/271 App Center SDK configured successfully.
[AppCenter] VERBOSE: -[MSAppCenter start:withServices:fromApplication:]/289 Start services MSCrashes, MSAnalytics from an application
[AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/568 EnableUncaughtExceptionHandler is set to NO, we're running in a Xamarin runtime.
[AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/611 Exception handler successfully initialized but it has not been registered due to the wrapper SDK.
[AppCenterCrashes] INFO: -[MSCrashes applyEnabledState:]/336 Crashes service has been enabled.
[AppCenterCrashes] VERBOSE: -[MSCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/375 Started crash service.
[AppCenter] VERBOSE: -[MSSessionContext setSessionId:]/63 Stored new session with id:04BDBD2E-BD45-4759-A896-2C30118F6B63 and timestamp: 2019-04-05 18:21:40 +0000.
[AppCenterAnalytics] INFO: -[MSSessionTracker renewSessionId]/46 New session ID: 04BDBD2E-BD45-4759-A896-2C30118F6B63
[AppCenter] VERBOSE: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/447 Identifying object <MSAnalytics: 0x2818120d0> removed from pause lane for channel Analytics.
[AppCenter] DEBUG: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/449 Resume channel Analytics.
[AppCenter] VERBOSE: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/447 Identifying object <MSAnalytics: 0x2818120d0> removed from pause lane for channel Analytics/one.
[AppCenter] DEBUG: -[MSChannelUnitDefault resumeWithIdentifyingObjectSync:]/449 Resume channel Analytics/one.
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/445 Storing a log to Crashes Buffer: (sid: 04BDBD2E-BD45-4759-A896-2C30118F6B63, type: startSession)
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/456 Found an empty buffer position.
[AppCenterAnalytics] INFO: -[MSAnalytics applyEnabledState:]/143 Analytics service has been enabled.
[AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/169 Saving log, type: startSession, flags: 1.
[AppCenterAnalytics] VERBOSE: -[MSAnalytics startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/96 Started Analytics service.
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/445 Storing a log to Crashes Buffer: (sid: (null), type: startService)
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/468 Remembering index 0 for oldest timestamp 1554488500.016584.
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:internalId:flags:]/456 Found an empty buffer position.
[AppCenter] VERBOSE: -[MSSessionContext clearSessionHistoryAndKeepCurrentSession:]/85 Cleared old sessions.
[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/115 Log is stored with id: '206'
[AppCenter] VERBOSE: -[MSUserIdContext clearUserIdHistory]/108 Cleared old userIds while keeping current userId.
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/498 Deleting a log from buffer with id A124B909-BC36-4A72-9FAF-51049C59A1E0
[AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/169 Saving log, type: startService, flags: 1.
[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/115 Log is stored with id: '207'
[AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:internalId:]/498 Deleting a log from buffer with id 04CB14A9-6734-484D-AD66-77EA322FF29D
[AppCenter] VERBOSE: -[MSUserIdContext setUserId:]/88 Stored new userId:87014344:bodykeyapp+t5@gmail.com and timestamp: 2019-04-05 18:21:40 +0000.
[AppCenterCrashes] DEBUG: -[MSCrashes startCrashProcessing]/660 Start delayed CrashManager processing
[AppCenterCrashes] VERBOSE: -[MSCrashes processCrashReports]/719 Crash reports found
[AppCenterCrashes] DEBUG: -[MSCrashes processCrashReports]/729 shouldProcessErrorReport is not implemented or returned YES, processing the crash report: <MSPLCrashReport: 0x2856242a0>
[AppCenterCrashes] DEBUG: -[MSCrashes sendCrashReportsOrAwaitUserConfirmation]/1057 The flag for user confirmation is set to MSUserConfirmationAlways, continue sending logs
[AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/169 Saving log, type: appleError, flags: 2.
[AppCenter] VERBOSE: -[MSSessionContext clearSessionHistoryAndKeepCurrentSession:]/85 Cleared old sessions.
[AppCenter] VERBOSE: -[MSUserIdContext clearUserIdHistory]/108 Cleared old userIds while keeping current userId.
[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/115 Log is stored with id: '208'
[AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '208' as batch Id:3FA15CF0-9F2A-4DF8-B78F-96B07FC99834
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: Crashes, batch Id: 3FA15CF0-9F2A-4DF8-B78F-96B07FC99834, session Id: (null), payload:
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Content-Encoding = gzip, Install-ID = 3A69C24B-1E78-4844-A58E-13DB63F92C25, App-Secret = ****************************6e64c83b, Content-Type = application/json
[AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:flags:]_block_invoke/169 Saving log, type: errorAttachment, flags: 1.
[AppCenter] VERBOSE: -[MSLogDBStorage saveLog:withGroupId:flags:]_block_invoke/115 Log is stored with id: '209'
[AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '209' as batch Id:DC0A903F-A9C3-49F9-9FEB-8776D29E4EA0
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: Crashes, batch Id: DC0A903F-A9C3-49F9-9FEB-8776D29E4EA0, session Id: 04BDBD2E-BD45-4759-A896-2C30118F6B63, payload:
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 3A69C24B-1E78-4844-A58E-13DB63F92C25, App-Secret = ****************************6e64c83b, Content-Type = application/json
[AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
[AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:3FA15CF0-9F2A-4DF8-B78F-96B07FC99834 from pending calls:{
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:3FA15CF0-9F2A-4DF8-B78F-96B07FC99834.
[AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/322 Deletion of log(s) by id with value(s) '208' succeeded.
[AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
[AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:DC0A903F-A9C3-49F9-9FEB-8776D29E4EA0 from pending calls:{
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:DC0A903F-A9C3-49F9-9FEB-8776D29E4EA0.
[AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/322 Deletion of log(s) by id with value(s) '209' succeeded.
[AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '206' as batch Id:42DB34A1-BBE6-4D54-94E0-3CA234024EF2
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: Analytics, batch Id: 42DB34A1-BBE6-4D54-94E0-3CA234024EF2, session Id: 04BDBD2E-BD45-4759-A896-2C30118F6B63, payload:
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 3A69C24B-1E78-4844-A58E-13DB63F92C25, App-Secret = ****************************6e64c83b, Content-Type = application/json
[AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '207' as batch Id:77000BF4-E5C2-4773-BE72-B5ECF637B6F7
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: AppCenter, batch Id: 77000BF4-E5C2-4773-BE72-B5ECF637B6F7, session Id: (null), payload:
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
[AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 3A69C24B-1E78-4844-A58E-13DB63F92C25, App-Secret = ****************************6e64c83b, Content-Type = application/json
[AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:77000BF4-E5C2-4773-BE72-B5ECF637B6F7.
[AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:77000BF4-E5C2-4773-BE72-B5ECF637B6F7 from pending calls:{
[AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
[AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:42DB34A1-BBE6-4D54-94E0-3CA234024EF2 from pending calls:{
[AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/322 Deletion of log(s) by id with value(s) '207' succeeded.
[AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:42DB34A1-BBE6-4D54-94E0-3CA234024EF2.
[AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/322 Deletion of log(s) by id with value(s) '206' succeeded.

**Comment by guperrot** [comment]
(ping for webhook)

**Comment by annakocheshkova** [comment]
Hi there! I tested the SDK and it seems to attach User ID to crashes for me. Can you share with me the code you are using to configure the SDK and set user Id?

**Comment by guperrot** [comment]
I don't know if that will help but please note the userId associated with a crash is the userId that was set before the crash occurred on the same run (and thus before application restart whereas the SDK sends the crash after restart and will use the userId set in the previous process and ignore current process value if any). The userId also needs to be set every time the process restarts.

**Comment by annakocheshkova** [comment]
@Jhultink is it possible that you have the same issue as Atryom: https://github.com/Microsoft/appcenter/issues/301#issuecomment-481652549 ?

**Comment by annakocheshkova** [comment]
Hi @Jhultink just a friendly pind, do you have any updates?

**Comment by Jhultink** [comment]
Yes, removing `Crashes.NotifyUserConfirmation(UserConfirmation.AlwaysSend);` fixed it for me. Thanks!

**Comment by guperrot** [comment]
This bug has been fixed in version [2.0.0](https://github.com/microsoft/AppCenter-SDK-DotNet/releases/tag/2.0.0).

Using the `notifyUserConfirmation` method when the service is not expecting that call will now be ignored and print an error in console if error logging is enabled.
