### ISSUE TITLE
Crashes not showing on portal

### ISSUE THREAD

**Issue by mhalt** [Microsoft/AppCenter-SDK-DotNet#873]
Based on my research, it would seem that App Center for Xamarin doesn’t support reporting for unhandled exceptions like in [Unity](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/unity#unhandled-exceptions-in-unity). 

It would be very useful to be able to use “Crashes.ReportUnhandledExceptions(true)”.

**Comment by guperrot** [comment]
Hi, Unity does not crash the app on unhandled exception, but on Xamarin the app definitely crashes if you don't catch an exception. Thus our SDK already supports reporting crashes.

Can you clarify what is the case where you have an unhandled exception on Xamarin that is not crashing the application?

**Comment by mhalt** [comment]
I'm seeing a lot of unhandled errors in my log flow, which do not get reported under Diagnostics > Issues > Errors. Can you provide some insight on this?

**UNHANDLEDERROR - {"errorId":"dc63c279-4197-4a92-be03-a2b8d1d3c95a","blobReference":"ce1f86b8-0b13-4832-8ee5-0bc18b6cab38/unhandled/raw/dc63c279-4197-4a92-be03-a2b8d1d3c95a.json"}

61c1d483 | UNHANDLEDERROR - {"errorId":"dc63c279-4197-4a92-be03-a2b8d1d3c95a","blobReference":"ce1f86b8-0b13-4832-8ee5-0bc18b6cab38/unhandled/raw/dc63c279-4197-4a92-be03-a2b8d1d3c95a.json"} | 14:24:38**

**Comment by guperrot** [comment]
Those are actual crashes aka unhandled exceptions, not handled errors.
That means the SDK correctly reports crashes but there is a problem in processing them backend side. The server team needs to be involved. We can keep the ticket here and I can try to ping them but ideally non SDK issues would get better support on https://appcenter.ms using the chat button.

**Comment by guperrot** [comment]
I'm curious though as errors and crashes used to be separate pages, but the submenus disappeared and now it's only 1 unified `crashes/errors` (end of url) page.

**Comment by mhalt** [comment]
@guperrot Do you need anything else from me going forward or will the server team report back to you?

**Comment by guperrot** [comment]
Hi, you should create a ticket on https://appcenter.ms using the feedback/chat button to get a faster engagement for this issue from the server team.

**Comment by dtrabo** [comment]
Hi @mhalt! This is not SDK issue, so I close it. If you have any questions, please let us know.
