### ISSUE TITLE
Xamarin Forms Push.PushNotificationReceived fires twice

### ISSUE THREAD

**Issue by james1301** [Microsoft/AppCenter-SDK-DotNet#874]
### **Description**

When I am receiving a PushNotification from App Center the PushNotificationReceived event in my Xamarin Forms application is called twice when running the iOS application.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Wire up App Center Push Notifications - Sandbox
2. Running iOS Application
3. Add break point in Push.PushNotificationReceived

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms (3.6) > iOS app
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    NET standard 2.0.
2. Which SDK version are you using?
    - 1.14
4. Which OS version did you experience the issue on?
    - iOS 12.2
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPod Touch
6. What third party libraries are you using? 
    - N/A
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
[logs.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/3063410/logs.txt)

**Comment by annakocheshkova** [comment]
Hi @james1301 can you share with me how you configure your app? You can post a gist on GH. Thanks!

**Comment by james1301** [comment]
Well here is a project I was using to test. Removed the app center unique id bit.

[TestListView.zip](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/3063781/TestListView.zip)

**Comment by annakocheshkova** [comment]
Alright thanks a lot, this is a lot of help! Let me take a look right now.

**Comment by annakocheshkova** [comment]
@james1301 I see that you have calls to `DidReceiveRemoteNotification` inside your `AppDelegate`, but your SDK version is `1.14`. Starting with version 1.11.0, calling `Push.DidReceiveRemoteNotification(...)` within a `UNUserNotificationCenterDelegate` is no longer necessary. Please refer to this doc to migrate: https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/xamarin-ios

**Comment by james1301** [comment]
Oh cool, so that is what's causing the duplication. I had seen that change and did mean to test it I think, but I was struggling to get the Push Notifications to come through earlier so I messed about and put it back in at some stage.

Thanks for your help, will close this issue.
