### ISSUE TITLE
WPF Support

### ISSUE THREAD

**Issue by rheuser** [Microsoft/AppCenter-SDK-DotNet#879]
### **Description**

Can I put the App Center SDK into my WPF app and start using custom events now? Or do I have to wait for WPF support in App Center?

**Comment by annakocheshkova** [comment]
@rheuser there's no official support of WPF now, you can either wait for it or use the unofficial beta. This is the [feature request](https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/620) where you can find all the relevant information and links.

**Comment by annakocheshkova** [comment]
And I'm closing this one as duplicate, feel free to ask any additional questions on that thread.
