### ISSUE TITLE
UWP store submission fails because of AppCenter SDK

### ISSUE THREAD

**Issue by SamuelDebruyn** [microsoft/AppCenter-SDK-DotNet#941]
We are using Microsoft.AppCenter for Analytics and Crashes in a UWP app. The root NuGet package (Microsoft.AppCenter) has a reference to sqlite-net-pcl which causes our store submission to fail.

The certification tests on our local machine work without issues. But when we upload our package to the store, the WACK test fails with a lot of errors regarding e_sqlite3.dll:

```
API sqlite3_aggregate_context in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
API sqlite3_aggregate_count in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
API sqlite3_backup_finish in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
API sqlite3_backup_init in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
API sqlite3_backup_pagecount in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
API sqlite3_backup_remaining in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
API sqlite3_backup_step in e_sqlite3.dll is not supported for this application type. BingelRaketPupil.dll calls this API.
```

Why would the AppCenter package need SQLite to work? I've read in another issue that I can exclude dependencies, but is this a safe thing to do? I suppose that it is there for a reason?

We're using v1.13 and the SQLite reference is present in this version and up.

I'd appreciate any help on this as this is a very urgent issue for us.

**Comment by dhei** [comment]
Hi @SamuelDebruyn, 

Thanks for getting in touch.

What architectures are you supporting in the UWP app? Note that we don't yet support ARM64 architecture in UWP (feature request tracked in https://github.com/microsoft/AppCenter-SDK-DotNet/issues/727).

Regarding your question about excluding SQLite dependency, App Center SDK **does** use SQLite to persist logs, so SQLite is definitely needed.

**Comment by woutermeuwis** [comment]
We support x64, x86, ARM and ARM64 in this project

**Comment by dhei** [comment]
@woutermeuwis, I believe the SQLite errors are related to ARM64 architectures and we don't yet support ARM64 on UWP. Will talk to PM about it. In the meanwhile, let's track this feature request in #727 and close this issue for now.

**Comment by SamuelDebruyn** [comment]
This was indeed the cause of our issue. Thanks for the quick response, the app is now live!
