### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList

### ISSUE THREAD

**Issue by SandipAhluwalia** [microsoft/appcenter-sdk-dotnet#953]
### **Description**

Xamarin.Android app (developed via Xamarin.Forms) crashing on app launch with
missing FirebaseMessagingService class despite Xamarin.Firebase.Messaging.dll being confirmed to be in the apk so doesn't seem to be a linking issue.

Incidentally, my app doesn't crash when deployed via the Visual Studio 2017 on Windows debugger in either debug or release mode. The issue above occurs when I install the app via our TFS 2017 on premise build CI system. I think I have tried almost everything with Proguard originally disabled and then enabled (with -keep class com.google.firebase.** { *; }) to see if that makes a difference. Linking in release mode is set to "Sdk Assemblies Only", but I even disabled this to see if that made a difference and it didn't. I also added following to no avail:
   
`<AndroidLinkSkip>Xamarin.Firebase.Common;Xamarin.Firebase.Iid;Xamarin.Firebase.Messaging</AndroidLinkSkip>`

I also double checked things suggested in potentially the 2 following related issues, #851 and #826, but nothing suggested resolves my issue.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Set up the Appcenter push notification service as per the official documentation for Xamarin.Forms and then start the service in code like:
AppCenter.Start("android=[Android app secret];" +
                            "ios=[OS app secret]",
                            typeof(Analytics), typeof(Crashes), typeof(Push));

2. Build app in release mode using following commands as per a typical build CI system like TFS 2017 on premise does:

- nuget restore 
- msbuild
- jarsigner (signs the app with your keystore)
- zipalign (package the app)

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?

Xamarin.Forms on 2 platforms (Android and iOS).

2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?

Using NET standard 2.0.

2. Which SDK version are you using?

1.14.0

4. Which OS version did you experience the issue on?

Android 6.0 and Android 8.0

5. What device version did you see this error on?  Were you using an emulator or a physical device?

One Plus 3T and Huawei P9 Lite physical devices

6. What third party libraries are you using? 

`<package id="akavache" version="6.0.20" targetFramework="monoandroid81" />
  <package id="akavache.core" version="6.0.20" targetFramework="monoandroid81" />
  <package id="akavache.sqlite3" version="6.0.20" targetFramework="monoandroid81" />
  <package id="BottomNavigationBar" version="1.1.2" targetFramework="monoandroid71" />
  <package id="CarouselView.FormsPlugin" version="5.2.0" targetFramework="monoandroid80" />
  <package id="CommonServiceLocator" version="2.0.4" targetFramework="monoandroid81" />
  <package id="DLToolkit.Forms.Controls.FlowListView" version="2.0.9" targetFramework="monoandroid71" />
  <package id="dotMorten.Xamarin.Forms.AutoSuggestBox" version="0.1.0" targetFramework="monoandroid81" />
  <package id="HtmlAgilityPack" version="1.6.10" targetFramework="monoandroid80" />
  <package id="Microsoft.AppCenter" version="1.14.0" targetFramework="monoandroid90" />
  <package id="Microsoft.AppCenter.Analytics" version="1.14.0" targetFramework="monoandroid90" />
  <package id="Microsoft.AppCenter.Crashes" version="1.14.0" targetFramework="monoandroid90" />
  <package id="Microsoft.AppCenter.Push" version="1.14.0" targetFramework="monoandroid90" />
  <package id="Microsoft.CSharp" version="4.3.0" targetFramework="monoandroid71" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="monoandroid71" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="NETStandard.Library" version="2.0.3" targetFramework="monoandroid81" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="monoandroid71" />
  <package id="Plugin.CurrentActivity" version="2.1.0.4" targetFramework="monoandroid90" />
  <package id="Plugin.Fingerprint" version="1.4.9" targetFramework="monoandroid90" />
  <package id="Plugin.Permissions" version="3.0.0.12" targetFramework="monoandroid81" />
  <package id="Plugin.Share" version="7.1.1" targetFramework="monoandroid80" />
  <package id="Prism.Core" version="7.0.0.396" targetFramework="monoandroid80" />
  <package id="Prism.Forms" version="7.0.0.396" targetFramework="monoandroid80" />
  <package id="Prism.Unity.Forms" version="7.0.0.396" targetFramework="monoandroid80" />
  <package id="Refractored.XamForms.PullToRefresh" version="2.2.2" targetFramework="monoandroid81" />
  <package id="Rx-Core" version="2.2.5" targetFramework="monoandroid71" />
  <package id="Rx-Interfaces" version="2.2.5" targetFramework="monoandroid71" />
  <package id="Rx-Linq" version="2.2.5" targetFramework="monoandroid71" />
  <package id="Rx-Main" version="2.2.5" targetFramework="monoandroid71" />
  <package id="Rx-PlatformServices" version="2.2.5" targetFramework="monoandroid71" />
  <package id="Splat" version="4.0.2" targetFramework="monoandroid81" />
  <package id="sqlite-net-pcl" version="1.3.3" targetFramework="monoandroid90" />
  <package id="SQLitePCLRaw.bundle_e_sqlite3" version="1.1.11" targetFramework="monoandroid81" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.5" targetFramework="monoandroid80" />
  <package id="SQLitePCLRaw.core" version="1.1.11" targetFramework="monoandroid81" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.android" version="1.1.11" targetFramework="monoandroid81" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.android" version="1.1.11" targetFramework="monoandroid81" />
  <package id="System.AppContext" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Console" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Http" version="4.3.2" targetFramework="monoandroid80" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reactive" version="4.0.0" targetFramework="monoandroid81" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.InteropServices.WindowsRuntime" version="4.3.0" targetFramework="monoandroid81" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Serialization.Formatters" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="monoandroid71" />
  <package id="System.Xml.XPath" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XPath.XmlDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="ThriveGmbH.BottomNavigationBar.XF" version="1.0.2" targetFramework="monoandroid71" />
  <package id="Unity" version="5.5.5" targetFramework="monoandroid80" />
  <package id="Xam.Plugin.Connectivity" version="3.2.0" targetFramework="monoandroid90" />
  <package id="Xam.Plugin.DeviceInfo" version="4.0.0.13" targetFramework="monoandroid90" />
  <package id="Xam.Plugin.HtmlLabel" version="2.2.0" targetFramework="monoandroid80" />
  <package id="Xam.Plugins.Messaging" version="5.0.0" targetFramework="monoandroid71" />
  <package id="Xam.Plugins.Notifier" version="3.0.1-pr42-build30" targetFramework="monoandroid90" />
  <package id="Xam.Plugins.Settings" version="3.0.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Android.Arch.Core.Common" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Core.Runtime" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.Common" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.LiveData" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.LiveData.Core" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.Runtime" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Arch.Lifecycle.ViewModel" version="1.1.1.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.CirclePageIndicator" version="1.0.2" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.ShortcutBadger" version="1.1.809" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Annotations" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.AsyncLayoutInflater" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Collections" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Compat" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CoordinaterLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Core.UI" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Core.Utils" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CursorAdapter" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CustomTabs" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.CustomView" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Design" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.DocumentFile" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.DrawerLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Fragment" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Interpolator" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Loader" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.LocalBroadcastManager" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Media.Compat" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Print" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.SlidingPaneLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.SwipeRefreshLayout" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Transition" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.v4" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.v7.CardView" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.v7.Palette" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.VersionedParcelable" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Support.ViewPager" version="28.0.0.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.VerticalViewPager" version="1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Build.Download" version="0.4.9" targetFramework="monoandroid90" />
  <package id="Xamarin.FFImageLoading" version="2.2.25" targetFramework="monoandroid80" />
  <package id="Xamarin.FFImageLoading.Forms" version="2.2.25" targetFramework="monoandroid90" />
  <package id="Xamarin.FFImageLoading.Transformations" version="2.2.25" targetFramework="monoandroid80" />
  <package id="Xamarin.Firebase.Common" version="60.1142.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Iid" version="60.1142.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Firebase.Messaging" version="60.1142.1" targetFramework="monoandroid90" />
  <package id="Xamarin.Forms" version="3.6.0.264807" targetFramework="monoandroid90" />
  <package id="Xamarin.Forms.Contacts" version="1.0.5" targetFramework="monoandroid81" />
  <package id="Xamarin.Forms.InputKit" version="2.3.8" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Basement" version="60.1142.1" targetFramework="monoandroid90" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="60.1142.1" targetFramework="monoandroid90" />`

7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

See attachment [AppLaunchCrash8.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/3212101/AppLaunchCrash8.txt) - This logging is based on Proguard being enabled with config as follows:

`-dontwarn com.microsoft.appcenter.**
-dontwarn com.google.android.gms.**
-dontwarn com.samsung.android.sdk.pass.**
-keep class com.google.firebase.** { *; }
-keep class com.microsoft.appcenter.push.TokenService
-keep class com.microsoft.appcenter.push.PushMessagingService
-keep class android.support.**`

**Comment by dtrabo** [comment]
Hi, did you try this solution https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/826#issuecomment-471768758 ? If it didn't help please share your AndroidManifes.xml, packages.config (if any, or project.json if any) and the csproj files.

**Comment by SandipAhluwalia** [comment]
Hi @dtrabo , as I mentioned the issue happens when the app is installed from our CI build system, so each build downloads the git-based source code and builds it from scratch on a clean drive so I guess effectively the manual steps mentioned in #826 are covered. 

Note: Incidentally, I have also sometimes (not every time like the build system) observed those missing com.google.firebase.messaging.FirebaseMessagingService class error messages in the logcat when deploying the app via Visual Studio in release mode, but it does crash the app in this case so don't know what that means.

Since my posting, I have disabled ProGuard again to rule out those type of linking issues and updated the AppCenter SDKs to latest version of 2.0.0, but still seeing same result.

AndroidManifes.xml, packages.config and the csproj files as requested:

[953.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/3213041/953.zip)

**Comment by dtrabo** [comment]
Please, try to enable multidex https://developer.android.com/studio/build/multidex#mdex-gradle
and share with me the results of it.

**Comment by SandipAhluwalia** [comment]
Hi @dtrabo , Multi-Dex is already enabled as shown in the csproj file I shared previously:

`<AndroidEnableMultiDex>true</AndroidEnableMultiDex>`

**Comment by MatkovIvan** [comment]
Hi @SandipAhluwalia!

Does the build on CI have any warnings or so? Could you please share the build log too?

**Comment by SandipAhluwalia** [comment]
Hi @MatkovIvan , no warnings that were relevant to this issue. Another key thing is if I don't start the Appcenter push service in the AppCenter.Start() method then there is no crash.

Attached are the CI build and device logcat logs giving more details of the issue.

Device logcat output: [AppLaunchCrash9.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/3216377/AppLaunchCrash9.txt)

CI build results: [logs_545.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/3216382/logs_545.zip)

**Comment by MatkovIvan** [comment]
Thanks for the logs. The reason isn't clear yet, we are looking at it.

The most suspicious lines in the build logs that I found are
```
2019-05-23T15:10:20.2281534Z _XamarinAndroidBuildAarRestore:
2019-05-23T15:10:20.2281534Z   Reference has already had resources merged, skipping due to: C:\MyDAFOutput\90\XbdMerge\Xamarin.GooglePlayServices.Basement.dll.stamp
2019-05-23T15:10:20.2594051Z   Reference has already had resources merged, skipping due to: C:\MyDAFOutput\90\XbdMerge\Xamarin.GooglePlayServices.Tasks.dll.stamp
2019-05-23T15:10:20.2906543Z   Reference has already had resources merged, skipping due to: C:\MyDAFOutput\90\XbdMerge\Xamarin.Firebase.Common.dll.stamp
2019-05-23T15:10:20.3219168Z   Reference has already had resources merged, skipping due to: C:\MyDAFOutput\90\XbdMerge\Xamarin.Firebase.Iid.dll.stamp
2019-05-23T15:10:20.3375354Z   Reference has already had resources merged, skipping due to: C:\MyDAFOutput\90\XbdMerge\Xamarin.Firebase.Messaging.dll.stamp
```

But I'm not sure that this is the reason for it.

**Comment by Jamminroot** [comment]
As for logs - can you kindly provide output of this command when launching app to exclude irrelevant output?
`adb -d logcat *:S AppCenterPush:V AppCenter:V` (or `adb -d logcat '*':S AppCenterPush:V AppCenter:V` for some specific shells which won't allow `*` alone)
That would help us clarify what's going on

**Comment by Jamminroot** [comment]
As for different behaviour (VS<>TFS), did you clear app cache and make it a clean build? Different toolchain version might cause Dex file being recognized as invalid, thus causing this exception:
```
05-23 16:31:13.033  6334  6419 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.FirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.lotusgroup.DialAFlight-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lotusgroup.DialAFlight-1/lib/arm, /data/app/com.lotusgroup.DialAFlight-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
```
Can you please check, whether issue remains on clean install?

**Comment by SandipAhluwalia** [comment]
Hi @Jamminroot , I tried providing the filtered logcat output as you instructed but got errors when trying to run either of your 2 logcat commands that you gave. However, still got a little output from the first logcat command you gave in the attached log so let me know if that is okay. Note: I am using a cmd.exe shell for the logcat commands on a Windows machine.

[AppLaunchCrash10.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/3228093/AppLaunchCrash10.txt)

Regarding VS vs TFS, each TFS CI build is a clean build from scratch with all source code downloaded every time from the GIT repo. On device, I always uninstall old version of app before testing the new one so yes, app cache is clear if that is what you meant?

As the TFS build logs that I previously shared show, I also do a Nuget restore on the solution file before doing a msbuild on the Xamarin.Android csproj file.

Regarding the `compileSdkVersion` and `buildToolsVersion` from my gradle, I am not using the gradle build tool as I am using Xamarin and TFS to build. Based on the csproj settings, the compile SDK version is 9.0 and from what I can see in the build logs, I am using v27.0.3 of the build tools.

I agree with your analyis over the Dex file based on the exceptions in the logcat output I previously provided, but still not sure why.

**Comment by SandipAhluwalia** [comment]
Also, just seen a related issue that some people observed on the flutter platform: https://github.com/flutter/flutter/issues/24435#issuecomment-441431470. Might be related to my issue on Xamarin, but not sure how their resolution applies here.

**Comment by SandipAhluwalia** [comment]
Hi all, further to my previous 2 comments, I ran the TFS commands locally on an new clone of the remote GIT repo and it surprisingly worked without any issues, so it does seem like a caching issue as @Jamminroot previously suggested.

In my Android csproj file, I set the IntermediateOutputPath because Android support library filenames can be very long, which in turn fails the build so adding the IntermediateOutputPath set to root drive helps. I set it as follows:

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
<IntermediateOutputPath>C:\MyDAFOutput</IntermediateOutputPath>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
<IntermediateOutputPath>C:\MyDAFOutput</IntermediateOutputPath>
</PropertyGroup>
```

So I then added a TFS build step to remove the IntermediateOutputPath (C:\MyDAFOutput) folder before each build, which is the right thing to do anyway for a CI build, and it resolves the problem, i.e. no crash on app launch. 

Still unclear why it is crashing via the CI build if I don't clear this directory because deploying via Visual Studio, I never had to clean the IntermediateOutputPath directory for it to work and when I replicated the CI build on my local machine, I never had to clean the C:\MyDAFOutput directory for it to work correctly too.

Issue can be closed as I now have a solution or workaround, but still feel there could be something wrong in the SDK that gets highlighted with those build messages like "Reference has already had resources merged, skipping due to: C:\MyDAFOutput\90\XbdMerge\Xamarin.Firebase.Messaging.dll.stamp".

**Comment by AnastasiaKubova** [comment]
Thank you for your answer. Please contact us if you will have any other questions.

**Comment by WinniNew** [comment]
i also have same issue please anybody can help me

**Comment by russelarms** [comment]
@WinniNew could you please provide more details on the issue.
What error do you get?
Do you also get this error from CI builds?
Did you clear app cache and make it a clean build?

**Comment by jedicoder88** [comment]
I am getting the same issue for CI builds via Azure DevOps Pipelines, is there a solution yet? Local builds in release and debug word fine.

**Comment by jedicoder88** [comment]
As it is a CI build, we don't have access to app cache clearing etc. Please assist

**Comment by MatkovIvan** [comment]
@jedicoder88 please open separate issue and fill the template (logs, versions, ...)

**Comment by jedicoder88** [comment]
@MatkovIvan So found the issue, was not related to the CI issue after all, we had a very large repo merge and the Microsoft.App.Push nuget package reference got lost. The local builds still had it in the cache so could compile. Readded it and everything worked fine after.
